<?php
/* 
// J5
// Code is Poetry */
# # C # R # N # R # S # T # N # : : # # ##
#
# CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
#
# DATE GENERATED: 2022-08-28 16:20:02.010008
# FILE NAME: primary_nav_seriesblue00_120x120_close_x_hvr.php
# FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/base64/primary_nav_seriesblue00_120x120_close_x_hvr.php
# FILE SERIAL: 1001100101110010111011010000011100010000101010101010001010110100
#
# SERVER IP: 172.16.225.139
# CLIENT IP: 172.16.225.1 (172.16.225.1)
# PHPSESSION: qkuh0gsqn5rnn4ffr3c7t177a1
# GENERATING SERVER INFORMATION: Ubuntu 18.04.1 LTS, Apache v2.4.29, MySQLi v5.7.39, php v7.0.33, OpenSSL v1.1.1, NuSOAP0.9.5
#
# # # # #
# PNG FILE (ORIGINAL) :: primary_nav_seriesblue00_120x120_close_x_hvr.png
# PNG IMAGE DIMENSIONS: 120 pixels in width X 120 pixels in height.
# PNG FILE EXTENSION: png
# PNG FILE MIME TYPE: image/png
# PNG FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/png/primary_nav_seriesblue00_120x120_close_x_hvr.png
# PNG FILE SIZE: 7.06738 KiB
# PNG FILE LAST MODIFIED: 2022-07-06 05:57:16
# PNG FILE MD5: 92f0408f0f8d2e1e59b4cc57e6e4c093
# PNG FILE SHA1: 6917593182acb4baf8da0f79aef0850c251d50b6
# PNG FILE ENCODED LENGTH (BASE64): 9,674 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
# JPEG FILE (ORIGINAL) :: 
# JPEG IMAGE DIMENSIONS:  pixels in width X  pixels in height.
# JPEG FILE EXTENSION: 
# JPEG FILE MIME TYPE: 
# JPEG FILE PATH: 
# JPEG FILE SIZE: 0 bytes
# JPEG FILE LAST MODIFIED: 1969-12-31 19:00:00
# JPEG FILE MD5: 
# JPEG FILE SHA1: 
# JPEG FILE ENCODED LENGTH (BASE64): 0 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
/*
 _______  ______    __    _  ______    _______  _______  __    _    ___   ___  
|       ||    _ |  |  |  | ||    _ |  |       ||       ||  |  | |  |   | |   | 
|       ||   | ||  |   |_| ||   | ||  |  _____||_     _||   |_| |  |___| |___| 
|       ||   |_||_ |       ||   |_||_ | |_____   |   |  |       |   ___   ___  
|      _||    __  ||  _    ||    __  ||_____  |  |   |  |  _    |  |   | |   | 
|     |_ |   |  | || | |   ||   |  | | _____| |  |   |  | | |   |  |___| |___| 
|_______||___|  |_||_|  |__||___|  |_||_______|  |___|  |_|  |__|              
                                                                                                                                                                                                                                                                                                                                                                                                                            
        
        
        
<!-- 
ASCII ARTWORK GENERATED BY CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
ARTWORK TITLE :: Modular
TIMESTAMP :: 2022-08-28 16:20:02.009705

CREATIVE SOURCE :: http://patorjk.com/software/taag/#p=display&f=Modular&t=CRNRSTN%20%3A%3A
DATE :: Sunday, Jul 31, 2022 @ 0949 hrs ::  
-->      
*/


$system_file_serial = '1001100101110010111011010000011100010000101010101010001010110100';

switch(self::$image_output_mode){
    case CRNRSTN_UI_IMG_BASE64_JPEG_HTML_WRAPPED:
    case CRNRSTN_UI_IMG_BASE64_JPEG:
            
        //
        // BASE64 ENCODE OF JPG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_JPEG'] = '2022-08-28 16:20:02.015840';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64'] = '';

    break;
    default:
    
        //
        // BASE64 ENCODE OF PNG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_PNG'] = '2022-08-28 16:20:02.015799';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_PNG][self::$request_salt][$system_file_serial]['base64'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAB4CAIAAAC2BqGFAAAFaWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjEyMCIKICAgZXhpZjpQaXhlbFlEaW1lbnNpb249IjEyMCIKICAgZXhpZjpDb2xvclNwYWNlPSI2NTUzNSIKICAgdGlmZjpJbWFnZVdpZHRoPSIxMjAiCiAgIHRpZmY6SW1hZ2VMZW5ndGg9IjEyMCIKICAgdGlmZjpSZXNvbHV0aW9uVW5pdD0iMiIKICAgdGlmZjpYUmVzb2x1dGlvbj0iOTYvMSIKICAgdGlmZjpZUmVzb2x1dGlvbj0iOTYvMSIKICAgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIKICAgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9IkRpc3BsYXkiCiAgIHhtcDpNb2RpZnlEYXRlPSIyMDIyLTA3LTA2VDA1OjU3OjE2LTA0OjAwIgogICB4bXA6TWV0YWRhdGFEYXRlPSIyMDIyLTA3LTA2VDA1OjU3OjE2LTA0OjAwIj4KICAgPGRjOnRpdGxlPgogICAgPHJkZjpBbHQ+CiAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ij5zcXVhcmVfdGVtcGxhdGVfY2xvc2VfeF9CTFVFMDBfaHZyPC9yZGY6bGk+CiAgICA8L3JkZjpBbHQ+CiAgIDwvZGM6dGl0bGU+CiAgIDx4bXBNTTpIaXN0b3J5PgogICAgPHJkZjpTZXE+CiAgICAgPHJkZjpsaQogICAgICBzdEV2dDphY3Rpb249InByb2R1Y2VkIgogICAgICBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZmZpbml0eSBEZXNpZ25lciAxLjEwLjUiCiAgICAgIHN0RXZ0OndoZW49IjIwMjItMDctMDZUMDU6NTc6MTYtMDQ6MDAiLz4KICAgIDwvcmRmOlNlcT4KICAgPC94bXBNTTpIaXN0b3J5PgogIDwvcmRmOkRlc2NyaXB0aW9uPgogPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KPD94cGFja2V0IGVuZD0iciI/PtfQc2EAAAxSaUNDUERpc3BsYXkAAEiJpVd3WFPJFp9bUklogQhICb0JIkiXEkKLICAdbIQkkECIMSGI2JVFBdcuKljRVRFF1wKIHbG7KPa+WFBZWRcLNlTehAR09Xvvn3e+b+795cyZ3yk5994ZAHR2Svh5ClQXgDxpvjw+IoSVmpbOIj0FCDAH2sAV4Dy+QsaOi4sGUPrv/5Z3N6A1lKsuKq6f5/+n6AmECj4ASBzE+QIFPw/iZgDwYr5Mng8AMRLqrSfny1RYArGBHAYI8SwVzlbjFSqcqcbb+2wS4zkQHwaATOPx5NkAaJ+FelYBPxvyaD+H2E0qEEsB0DGCOJAv4gkgToV4SF7eRBUuhtgh8zue7H9xZg5w8njZA1idS5+QQ8UKmYQ3pT9PMggFYqAAMiABPDCg/v8lT6Ls92kHB00kj4xX1QDW8VbuxCgVpkHcKc2MiYVYH+IPYkGfPcQoVaSMTFLbo6Z8BQfWEDAhdhPwQqMgNoU4XCqJidboM7PE4VyIYcegheJ8bqJm7XyhIixBw7lWPjE+th9nyTlszdpanrzPr8q+WZmbxNbw3xIJuf38b4tEiSnqmDFqgTg5BmJtiJmK3IQotQ1mUyTixPTbyJXxqvhtIPYTSiNC1PzY+Cx5eLzGXq7pShgPNl8k5sZocEW+KDFSw7OTz+uLH/YD1iCUspP6eYSK1Oj+XATC0DB17thloTRJky/WJssPidesfS2TxGnscapQEqHSW0FsqihI0KzFA/Nhg6r58RhZflyiOk48M4c3Mk4dD14IogEH9gwLKOHIBBNBDhC3dNZ3wl/qmXDYR3KQDYTARaPpX5HSNyOF1wRQBP6GSAg7r39dSN+sEBRA/ZcBrfrqArL6Zgv6VuSCpxDngSjYs0IYh2qVdMBbMngCNeKfvPNhrBI4VHM/69hQE63RKPt5WTr9lsQwYigxkhhOdMRN8EDcH4+G12A43HEf3Lc/2m/2hKeEVsIjwnVCG+H2BPEc+Q/5sMAo0AY9hGtyzvw+Z9wOsnriIXgA5IfcOBM3AS74cOiJjQdB355Qy9FErsr+R+5/5fBd1TV2FDcKShlECaY4/LhS20nbc4BFVdPvK6SONXOgrpyBmR/9c76rtADeo360xOZj+7Az2AnsHHYYqwcs7BjWgF3EjqjwQBc96euifm/xffHkQh7xT/54Gp+qSircatw63D6r5/KFhfmqB4wzUTZFLs4W5bPYMplEyOJK+a5DWO5u7u4AqL4r6tfUG2bf9wJhnv+mm7segID9vb29h77pohoB2FcGAPXmN539dPg6OAHA2Uq+Ul6g1uGqCwFQgQ58oozhd8saOMB83IEX8AfBIAyMBLEgEaSB8bDKItjPcjAZTAOzQQkoA0vASlABNoDNYDvYBfaCenAYnACnwQVwGVwHd2H3tIMXoAu8Az0IgpAQOsJAjBELxBZxRtwRHyQQCUOikXgkDclAshEpokSmIXORMmQZUoFsQqqR35GDyAnkHNKK3EYeIh3Ia+QTiqE01AA1Q+3QoagPykaj0ER0HJqNTkKL0GJ0EboarUJ3onXoCfQCeh1tQ1+g3RjAtDAmZom5YD4YB4vF0rEsTI7NwEqxcqwKq8Ua4f98FWvDOrGPOBFn4CzcBXZwJJ6E8/FJ+Ax8IV6Bb8fr8Gb8Kv4Q78K/EugEU4IzwY/AJaQSsgmTCSWEcsJWwgHCKfg0tRPeEYlEJtGe6A2fxjRiDnEqcSFxHXE38TixlfiY2E0ikYxJzqQAUiyJR8onlZDWkHaSjpGukNpJH8haZAuyOzmcnE6WkueQy8k7yEfJV8jPyD0UXYotxY8SSxFQplAWU7ZQGimXKO2UHqoe1Z4aQE2k5lBnU1dTa6mnqPeob7S0tKy0fLVGa4m1Zmmt1tqjdVbrodZHmj7NicahjaUpaYto22jHabdpb+h0uh09mJ5Oz6cvolfTT9If0D9oM7RdtbnaAu2Z2pXaddpXtF/qUHRsddg643WKdMp19ulc0unUpeja6XJ0ebozdCt1D+re1O3WY+gN04vVy9NbqLdD75zec32Svp1+mL5Av1h/s/5J/ccMjGHN4DD4jLmMLYxTjHYDooG9Adcgx6DMYJdBi0GXob7hcMNkw0LDSsMjhm1MjGnH5DIlzMXMvcwbzE+DzAaxBwkHLRhUO+jKoPdGg42CjYRGpUa7ja4bfTJmGYcZ5xovNa43vm+CmziZjDaZbLLe5JRJ52CDwf6D+YNLB+8dfMcUNXUyjTedarrZ9KJpt5m5WYSZzGyN2UmzTnOmebB5jvkK86PmHRYMi0ALscUKi2MWf7EMWWyWhLWa1czqsjS1jLRUWm6ybLHssbK3SrKaY7Xb6r411drHOst6hXWTdZeNhc0om2k2NTZ3bCm2PrYi21W2Z2zf29nbpdjNs6u3e25vZM+1L7Kvsb/nQHcIcpjkUOVwzZHo6OOY67jO8bIT6uTpJHKqdLrkjDp7OYud1zm3DiEM8R0iHVI15KYLzYXtUuBS4/LQleka7TrHtd715VCboelDlw49M/Srm6ebxG2L291h+sNGDpszrHHYa3cnd757pfs1D7pHuMdMjwaPV8OdhwuHrx9+y5PhOcpznmeT5xcvby+5V61Xh7eNd4b3Wu+bPgY+cT4Lfc76EnxDfGf6Hvb96Ofll++31+8ffxf/XP8d/s9H2I8Qjtgy4nGAVQAvYFNAWyArMCNwY2BbkGUQL6gq6FGwdbAgeGvwM7YjO4e9k/0yxC1EHnIg5D3HjzOdczwUC40ILQ1tCdMPSwqrCHsQbhWeHV4T3hXhGTE14ngkITIqcmnkTa4Zl8+t5naN9B45fWRzFC0qIaoi6lG0U7Q8unEUOmrkqOWj7sXYxkhj6mNBLDd2eez9OPu4SXGHRhNHx42uHP00flj8tPgzCYyECQk7Et4lhiQuTryb5JCkTGpK1kkem1yd/D4lNGVZSlvq0NTpqRfSTNLEaQ3ppPTk9K3p3WPCxqwc0z7Wc2zJ2Bvj7McVjjs33mS8ZPyRCToTeBP2ZRAyUjJ2ZHzmxfKqeN2Z3My1mV18Dn8V/4UgWLBC0CEMEC4TPssKyFqW9Tw7IHt5docoSFQu6hRzxBXiVzmRORty3ufG5m7L7ZWkSHbnkfMy8g5K9aW50uaJ5hMLJ7bKnGUlsrZJfpNWTuqSR8m3KhDFOEVDvgHcwF9UOih/UT4sCCyoLPgwOXnyvkK9QmnhxSlOUxZMeVYUXvTbVHwqf2rTNMtps6c9nM6evmkGMiNzRtNM65nFM9tnRczaPps6O3f2H3Pc5iyb83ZuytzGYrPiWcWPf4n4paZEu0RecnOe/7wN8/H54vktCzwWrFnwtVRQer7Mray87PNC/sLzvw77dfWvvYuyFrUs9lq8fglxiXTJjaVBS7cv01tWtOzx8lHL61awVpSueLtywspz5cPLN6yirlKualsdvbphjc2aJWs+V4gqrleGVO5ea7p2wdr36wTrrqwPXl+7wWxD2YZPG8Ubb22K2FRXZVdVvpm4uWDz0y3JW8785vNb9VaTrWVbv2yTbmvbHr+9udq7unqH6Y7FNWiNsqZj59idl3eF7mqodandtJu5u2wP2KPc89fvGb/f2Bu1t2mfz77a/bb71x5gHCitQ+qm1HXVi+rbGtIaWg+OPNjU6N944JDroW2HLQ9XHjE8svgo9Wjx0d5jRce6j8uOd57IPvG4aULT3ZOpJ681j25uORV16uzp8NMnz7DPHDsbcPbwOb9zB8/7nK+/4HWh7qLnxQN/eP5xoMWrpe6S96WGy76XG1tHtB69EnTlxNXQq6evca9duB5zvfVG0o1bN8febLsluPX8tuT2qzsFd3ruzrpHuFd6X/d++QPTB1V/Ov65u82r7cjD0IcXHyU8uvuY//jFE8WTz+3FT+lPy59ZPKt+7v78cEd4x+W/xvzV/kL2oqez5G+9v9e+dHi5/5/gfy52pXa1v5K/6n298I3xm21vh79t6o7rfvAu713P+9IPxh+2f/T5eOZTyqdnPZM/kz6v/uL4pfFr1Nd7vXm9vTKenNe3FcDgQLOyAHi9DQB6GgCMy3D/MEZ97usTRH1W7UPgv2H12bBPvACohTfVdp1zHIA9cNgFQ254V23VE4MB6uExMDSiyPJwV3PR4ImH8KG3940ZACS4n/ki7+3tWdfb+2ULDPY2AMcnqc+bKiHCs8FGNxW6YrEP/Cj/AcbthH7Ojsj0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAKJElEQVR4nO2c+3NU1R3Av+fevft+REDAgCINTXmJUBwEEUGEyivYduwMU1tHO1rstNbxPQp/SGc60x/6myOoVUQRH7U17wRISIiYTUICSciDzW527717H+ec/rAMtWbvJQnZ792h5/Pj7p09Zz9z9jy+3+9Z8pu/jIGg9Ehed+D/BSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCSEaCR9aS4mwtHaJopm8Z9Se1Blau1OJh6Sqhb6wn3QMWhkNqScYognAoc2RvetChAAAaCZ/p1H98kIeoempPXl0dfDQg5GQnwAA53CyXX+nQeWlb1ped+CNUrex7/7QLx8IFywDgCKTDcv8sgRdQ1apm/4+BODJTeFDD0YU+XpXCIHqxUre4t0jdqlbL/kcTQAeWx2c+voTPw0f2hwhU98oWTcObYkc3BCe+tbO1UGEbpRctOIjC+Ny0bf23R/67dYoKf23JASefji6b12o6LuLErLiK3knSi7atHk277jg7F4bfHZbaV0TAr97JLprTZFfVYFJnZl2yWdpjO3d6Q63de/RVcHnd8Sk0riWCPx+R2zHSkfLAPB5J8ayXHLREgHD4v++6PZltlUHXtgZk+e6L7IEf9gZe7g64PLMV135sUk6xw0Xo+SiGYeuIWs4Tb/+1s31lhWBPz4W881dd3wS/GlXfPMKR8sc4PNOfTRDe8ZKvuUAnO1dWmOGBdEAGZlky+903LkvucO3bIGvuc9ktzxhKjL588/iG+/1Oz3AAU536Kkca7lkXs3cFiO6QP81u23AHM/Szzt1l8c2LPO/8njMf2t7AL+PvLwnvmGZs2UOp9r1CUTLgBnrGEjRswPmtRw7dd7N9X13+1/dGw/M1nVQIa/ujd+3VHF6gHP4pF1Pa6ypD88yIAeVrqTo2X4zrbJP2txcr65U3tgfL5ySZ0TIT17fF19d6Wb54zZtUmdNveYoyhp4A+zo3eAEbe03J3X28TndZSquXqy8uT8RnonrSIC8uT9RvdjRMuNw4pyW1XlTrzGWRbUMnoRJh9O05ZKZy7OPzmrcWXbVQt9bNYno9I7H0SB560CiaqHjSss4fHRWy+ULlj2IHXoTj76aoc19pmbwD8+4ub53ge/tA4l46CadjIekt2sSyxY4W2bwjzOaZvDGXmM8502E1rPA/8gkbeo1dZN/0Orm+u75viM1iYqwYz8rwtKRmsTd8xwtUwYfnNF0kzf0GNc8sgzeZljGsrSxz8hb/L0WzWXvXHmHfORgYl6kSFfnR6WjBxOVdxQPWgEAZfB+q5o3eUOPkVK9zDZ4nMoaz7LGXsO0+fFmlTl7WJyQjz6RWBD7H6F3xuSjBxOLEm6W32tRDYvX9xgTnloGz0UDwLUca+gxLArHmlXqbOMHWhcl5CMHf6j++9gMjjerps3rk2YaK1/lgveiASClFlzzY01urudHpSM1icoKubJCPnowMT/q2Hmb8uNNqmnzuqSZ8TQ/eQNSPv8SVhGWNlf5ZYk8uSniEl3KGQyARAOO2z6L8uPNmk15fdKcdA6FI1MWI7pAWmP1SdOm/N1G1aKOi2M0ILlYNik/1qRZlNcljfKxDGUlGgAyOqtPmpTxd5u0WWQ9DOu/lrN5hNT2DCgv0QAwmWd1SaPg2piJa928PmPUJY1cmVmGMhQNANk8r+s2KOPHmlTdnJYyzeTvtaiFsawaZWcZylM0AOQMXpc0bAbHW1T7ZokAm8L7LapFoWwtQ9mKBgDV4HXdhmEB5zeJKzHO8xbUJQ1tesPfE8pXNACsXqI8sy2qOB5KruP3kWe2RV3C0OVA+YreXBV4cXd8mqlxWYIXd8cfrHJLeHsLXjXpjNhaHTi8IzajwhpZgkIevbbbKFm/Zk85jujtK4OHH52Z5QKEwOGdse2u5TJeUXaid60JPrc96iK5Z8S6mnGsxCAAz22PFi2r9Jbymjr2rAs9tSXi8sD5y2bXkGVTvmNVyCUM/cy2qCKTT13T7ciU0YiuWX8Ty2cumV1DVnLUzhn8qy69f9ytwuiphyIH1hcvH/UEjEqlm0IAfrEx/OQmN8uNPUbfmN05aHWP2EMTdEFMHs2yUIDMiziO67VL/QBwcRi13N0J70UTgF9tivx8Y5ES8QIcoPa7/JUUbbtsXhqnAMA4DKVpRVhKq1yRiUv4f1WlIsvQNei9a49FE4Bfb4nsd/6Ncw5ff5sfTtMz/eaVCfr914fTNBqUNINzTlwSWj+5Swn6SccVj117uRgSAk9vdSsRZwy+7NLHs6y5r0hhEeNwdsC0mQIEbMY2LHM8rexdF1Jk8vfanEu6vdR4Jloi8OwjUZcScZvBF516Kscaex3LBDiH9suWTYEAWBQ2/cjR9a41QZ8Mf/uXZ669ES1L8Pz22FbnEnGL8tMd+QmVNvTcPLV6YcgqZGQsG1w+c8fKoE8if/1n9tbLgmeBB3O0LMELO2MP/djRiGHxU+f1CZXVJc1pXv1MqcyiEFLIeI7d61yydM98310J+Uy/iT+usUUXCvFdfuO6ed1ybffMgstpjekmjwalqxm6fKHidLZcOs+3dJ6vtc9AHteoBxZFJi89Hn9guWOJeC7PPm3XUyr7pns2weXLKdp6ybyWZZ+16y5j9oHl/pcej9+41okDnmi/j7yyJ77+HkfLGZ2dOq+P5+g33UbemuV4G07Txl4zpbKTbbpLicj6e/wv74nf4tWCGYEkOqiQ1/bG1zoX4qdy7PR5fTzL6pPmLd76G8vShh4jo7GTbZrtXLZw31Lltb3xoOMcM8dgiPZJ8Pq++CrnDMjoJP3igj4ySet7DJeKjumTUlld0sho7ONzussHrqpUXt8Xn8OrYC5gNFKzIexSiD+Upl935YcmaFOv6fJjnykZndUmjYzOTpzVDeeJqHqxUlPsgvicgyF691rHU8nANfubi/mBFG3tn4Nbbz8gl+e13UZGZyfOaS5Lq8vRdA4puWi/j8SCxVvpHbUbkkbfmN02UKqNrWby2m4jrbGT57ScQ4VYPCQhrIolF23ZvOj9p4vDVkuf8d1Vu2NwtjuM6ZG3eF3STKmscOtt6gMjGWrdBpfuOcAXU/5spuOK2TZgXhi0Ll7FCKqZNq/vMcaz7LPz+tSwyZcXMArIME6GyRHbr5AVi5RCvrVz0LowaN0ILuNQCGHHQ9LoJL0zLkcCUuHFk+36B60aQgfw6qMTYWnNEkUz+HiOGRbz5g4agaqFvrTOl1TI4QDpRPzzqjIqRL+9KaPk7O2NEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI2EEI3EfwDM7bdproMAhQAAAABJRU5ErkJggg==';

    break;
    
}

//
// BASE64 LAST MODIFIED
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_PNG][self::$request_salt][$system_file_serial]['lastmodified_base64_PNG'] = '2022-08-28 16:20:02.017466';
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_JPEG][self::$request_salt][$system_file_serial]['lastmodified_base64_JPEG'] = '2022-08-28 16:20:02.019086';

//
// BASE64 HASH/CHECKSUM
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_crc'] = '745535945';
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_md5'] = '488bd7556d67e95faeaf92671021c53c';

self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_crc'] = '0';
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_md5'] = 'd41d8cd98f00b204e9800998ecf8427e';

//
// HASHES FOR BASE64 SOURCE PNG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_PNG][self::$request_salt][$system_file_serial]['md5'] = '92f0408f0f8d2e1e59b4cc57e6e4c093';
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_PNG][self::$request_salt][$system_file_serial]['sha1'] = '6917593182acb4baf8da0f79aef0850c251d50b6';

//
// HASHES FOR BASE64 SOURCE JPEG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_JPEG][self::$request_salt][$system_file_serial]['md5'] = '';
self::$image_filesystem_meta_ARRAY[CRNRSTN_UI_IMG_BASE64_JPEG][self::$request_salt][$system_file_serial]['sha1'] = '';


# # # # # 
# # # # # END OF CRNRSTN :: GENERATED SYSTEM FILE
# # # # # [2022-08-28 16:20:02.019218] [rtime 0.941253] 
