<?php
#  CRNRSTN :: An Advanced PHP Class Library for Enterprise
#  Copyright (C) 2012 Jonathan 'J5' Harris.
#  VERSION :: 3.0.0
#  AUTHOR :: J5
#  URI :: http://jony5.com/crnrstn/
#  OVERVIEW :: All configuration parameters for initialization of environmentally specific variables for the application in all environments. Currently, there is 
#               support for 12 variables across up to 7 environemnts. I have also wired in support for up to 4 unique databases (each DB...potentially...having it's own unique 
#               handle for USER,PORT,HOST and PWD).
#  LICENSE :: This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program. This license can also be downloaded from
#  my web site at (http://www.jony5.com/crnrstn/license.txt).  
#  If not, see <http://www.gnu.org/licenses/>

//
// CONNECTION MANAGEMENT
class crnrstn_EnvironmentalAwareness { 
   
   private $_LOCALHOST_FILEROOT_HTTP;
   private $_STAGE_FILEROOT_HTTP;
   private $_PREPROD_FILEROOT_HTTP; 
   private $_PROD0_FILEROOT_HTTP; 
   private $_PROD1_FILEROOT_HTTP; 
   private $_PROD2_FILEROOT_HTTP; 
   private $_PROD3_FILEROOT_HTTP;
   
   private $_LOCALHOST_FILEROOT_NONHTTP;
   private $_STAGE_FILEROOT_NONHTTP;
   private $_PREPROD_FILEROOT_NONHTTP; 
   private $_PROD0_FILEROOT_NONHTTP; 
   private $_PROD1_FILEROOT_NONHTTP; 
   private $_PROD2_FILEROOT_NONHTTP; 
   private $_PROD3_FILEROOT_NONHTTP;
   
   private $_LOCALHOST_HTTP;
   private $_STAGE_HTTP;
   private $_PREPROD_HTTP;
   private $_PROD0_HTTP;
   private $_PROD1_HTTP;
   private $_PROD2_HTTP;
   private $_PROD3_HTTP;
   
   private $_LOCALHOST_NAMESPACE;
   private $_STAGE_NAMESPACE;
   private $_PREPROD_NAMESPACE;
   private $_PROD0_NAMESPACE;
   private $_PROD1_NAMESPACE;
   private $_PROD2_NAMESPACE;
   private $_PROD3_NAMESPACE;
   
   private $_LOCALHOST_DBNAME0;
   private $_STAGE_DBNAME0;
   private $_PREPROD_DBNAME0;
   private $_PROD0_DBNAME0;
   private $_PROD1_DBNAME0;
   private $_PROD2_DBNAME0;
   private $_PROD3_DBNAME0;
   
   private $_LOCALHOST_DBNAME1;
   private $_STAGE_DBNAME1;
   private $_PREPROD_DBNAME1;
   private $_PROD0_DBNAME1;
   private $_PROD1_DBNAME1;
   private $_PROD2_DBNAME1;
   private $_PROD3_DBNAME1;
   
   private $_LOCALHOST_DBNAME2;
   private $_STAGE_DBNAME2;
   private $_PREPROD_DBNAME2;
   private $_PROD0_DBNAME2;
   private $_PROD1_DBNAME2;
   private $_PROD2_DBNAME2;
   private $_PROD3_DBNAME2;
   
   private $_LOCALHOST_DBNAME3;
   private $_STAGE_DBNAME3;
   private $_PREPROD_DBNAME3;
   private $_PROD0_DBNAME3;
   private $_PROD1_DBNAME3;
   private $_PROD2_DBNAME3;
   private $_PROD3_DBNAME3;
   
   private $_LOCALHOST_DBNAME4;
   private $_STAGE_DBNAME4;
   private $_PREPROD_DBNAME4;
   private $_PROD0_DBNAME4;
   private $_PROD1_DBNAME4;
   private $_PROD2_DBNAME4;
   private $_PROD3_DBNAME4;
   
   private $_LOCALHOST_DBUSER0;
   private $_STAGE_DBUSER0;
   private $_PREPROD_DBUSER0;
   private $_PROD0_DBUSER0;
   private $_PROD1_DBUSER0;
   private $_PROD2_DBUSER0;
   private $_PROD3_DBUSER0;
   
   private $_LOCALHOST_DBUSER1;
   private $_STAGE_DBUSER1;
   private $_PREPROD_DBUSER1;
   private $_PROD0_DBUSER1;
   private $_PROD1_DBUSER1;
   private $_PROD2_DBUSER1;
   private $_PROD3_DBUSER1;
   
   private $_LOCALHOST_DBUSER2;
   private $_STAGE_DBUSER2;
   private $_PREPROD_DBUSER2;
   private $_PROD0_DBUSER2;
   private $_PROD1_DBUSER2;
   private $_PROD2_DBUSER2;
   private $_PROD3_DBUSER2;
   
   private $_LOCALHOST_DBUSER3;
   private $_STAGE_DBUSER3;
   private $_PREPROD_DBUSER3;
   private $_PROD0_DBUSER3;
   private $_PROD1_DBUSER3;
   private $_PROD2_DBUSER3;
   private $_PROD3_DBUSER3;
   
   private $_LOCALHOST_DBUSER4;
   private $_STAGE_DBUSER4;
   private $_PREPROD_DBUSER4;
   private $_PROD0_DBUSER4;
   private $_PROD1_DBUSER4;
   private $_PROD2_DBUSER4;
   private $_PROD3_DBUSER4;
   
   private $_LOCALHOST_DBPORT0;
   private $_STAGE_DBPORT0;
   private $_PREPROD_DBPORT0;
   private $_PROD0_DBPORT0;
   private $_PROD1_DBPORT0;
   private $_PROD2_DBPORT0;
   private $_PROD3_DBPORT0;
  
   private $_LOCALHOST_DBPORT1;
   private $_STAGE_DBPORT1;
   private $_PREPROD_DBPORT1;
   private $_PROD0_DBPORT1;
   private $_PROD1_DBPORT1;
   private $_PROD2_DBPORT1;
   private $_PROD3_DBPORT1;
   
   private $_LOCALHOST_DBPORT2;
   private $_STAGE_DBPORT2;
   private $_PREPROD_DBPORT2;
   private $_PROD0_DBPORT2;
   private $_PROD1_DBPORT2;
   private $_PROD2_DBPORT2;
   private $_PROD3_DBPORT2;
   
   private $_LOCALHOST_DBPORT3;
   private $_STAGE_DBPORT3;
   private $_PREPROD_DBPORT3;
   private $_PROD0_DBPORT3;
   private $_PROD1_DBPORT3;
   private $_PROD2_DBPORT3;
   private $_PROD3_DBPORT3;
   
   private $_LOCALHOST_DBPORT4;
   private $_STAGE_DBPORT4;
   private $_PREPROD_DBPORT4;
   private $_PROD0_DBPORT4;
   private $_PROD1_DBPORT4;
   private $_PROD2_DBPORT4;
   private $_PROD3_DBPORT4;
   
   private $_LOCALHOST_DBHOST0;
   private $_STAGE_DBHOST0;
   private $_PREPROD_DBHOST0;
   private $_PROD0_DBHOST0;
   private $_PROD1_DBHOST0;
   private $_PROD2_DBHOST0;
   private $_PROD3_DBHOST0;
   
   private $_LOCALHOST_DBHOST1;
   private $_STAGE_DBHOST1;
   private $_PREPROD_DBHOST1;
   private $_PROD0_DBHOST1;
   private $_PROD1_DBHOST1;
   private $_PROD2_DBHOST1;
   private $_PROD3_DBHOST1;
   
   private $_LOCALHOST_DBHOST2;
   private $_STAGE_DBHOST2;
   private $_PREPROD_DBHOST2;
   private $_PROD0_DBHOST2;
   private $_PROD1_DBHOST2;
   private $_PROD2_DBHOST2;
   private $_PROD3_DBHOST2;
   
   private $_LOCALHOST_DBHOST3;
   private $_STAGE_DBHOST3;
   private $_PREPROD_DBHOST3;
   private $_PROD0_DBHOST3;
   private $_PROD1_DBHOST3;
   private $_PROD2_DBHOST3;
   private $_PROD3_DBHOST3;
   
   private $_LOCALHOST_DBHOST4;
   private $_STAGE_DBHOST4;
   private $_PREPROD_DBHOST4;
   private $_PROD0_DBHOST4;
   private $_PROD1_DBHOST4;
   private $_PROD2_DBHOST4;
   private $_PROD3_DBHOST4;
   
   private $_LOCALHOST_DBPWD0;
   private $_STAGE_DBPWD0;
   private $_PREPROD_DBPWD0;
   private $_PROD0_DBPWD0;
   private $_PROD1_DBPWD0;
   private $_PROD2_DBPWD0;
   private $_PROD3_DBPWD0;
   
   private $_LOCALHOST_DBPWD1;
   private $_STAGE_DBPWD1;
   private $_PREPROD_DBPWD1;
   private $_PROD0_DBPWD1;
   private $_PROD1_DBPWD1;
   private $_PROD2_DBPWD1;
   private $_PROD3_DBPWD1;
   
   private $_LOCALHOST_DBPWD2;
   private $_STAGE_DBPWD2;
   private $_PREPROD_DBPWD2;
   private $_PROD0_DBPWD2;
   private $_PROD1_DBPWD2;
   private $_PROD2_DBPWD2;
   private $_PROD3_DBPWD2;
   
   private $_LOCALHOST_DBPWD3;
   private $_STAGE_DBPWD3;
   private $_PREPROD_DBPWD3;
   private $_PROD0_DBPWD3;
   private $_PROD1_DBPWD3;
   private $_PROD2_DBPWD3;
   private $_PROD3_DBPWD3;
   
   private $_LOCALHOST_DBPWD4;
   private $_STAGE_DBPWD4;
   private $_PREPROD_DBPWD4;
   private $_PROD0_DBPWD4;
   private $_PROD1_DBPWD4;
   private $_PROD2_DBPWD4;
   private $_PROD3_DBPWD4;
   
   private $_LOCALHOST_MISC_PARAM_A;
   private $_STAGE_MISC_PARAM_A;
   private $_PREPROD_MISC_PARAM_A;
   private $_PROD0_MISC_PARAM_A;
   private $_PROD1_MISC_PARAM_A;
   private $_PROD2_MISC_PARAM_A;
   private $_PROD3_MISC_PARAM_A;
   
   private $_LOCALHOST_MISC_PARAM_B;
   private $_STAGE_MISC_PARAM_B;
   private $_PREPROD_MISC_PARAM_B;
   private $_PROD0_MISC_PARAM_B;
   private $_PROD1_MISC_PARAM_B;
   private $_PROD2_MISC_PARAM_B;
   private $_PROD3_MISC_PARAM_B;
   
   private $_LOCALHOST_MISC_PARAM_C;
   private $_STAGE_MISC_PARAM_C;
   private $_PREPROD_MISC_PARAM_C;
   private $_PROD0_MISC_PARAM_C;
   private $_PROD1_MISC_PARAM_C;
   private $_PROD2_MISC_PARAM_C;
   private $_PROD3_MISC_PARAM_C;
   
   private $_LOCALHOST_MISC_PARAM_D;
   private $_STAGE_MISC_PARAM_D;
   private $_PREPROD_MISC_PARAM_D;
   private $_PROD0_MISC_PARAM_D;
   private $_PROD1_MISC_PARAM_D;
   private $_PROD2_MISC_PARAM_D;
   private $_PROD3_MISC_PARAM_D;
   
   private $_LOCALHOST_MISC_PARAM_E;
   private $_STAGE_MISC_PARAM_E;
   private $_PREPROD_MISC_PARAM_E;
   private $_PROD0_MISC_PARAM_E;
   private $_PROD1_MISC_PARAM_E;
   private $_PROD2_MISC_PARAM_E;
   private $_PROD3_MISC_PARAM_E;
   
   private $_LOCALHOST_MISC_PARAM_F;
   private $_STAGE_MISC_PARAM_F;
   private $_PREPROD_MISC_PARAM_F;
   private $_PROD0_MISC_PARAM_F;
   private $_PROD1_MISC_PARAM_F;
   private $_PROD2_MISC_PARAM_F;
   private $_PROD3_MISC_PARAM_F;
   
   private $_LOCALHOST_MISC_PARAM_G;
   private $_STAGE_MISC_PARAM_G;
   private $_PREPROD_MISC_PARAM_G;
   private $_PROD0_MISC_PARAM_G;
   private $_PROD1_MISC_PARAM_G;
   private $_PROD2_MISC_PARAM_G;
   private $_PROD3_MISC_PARAM_G;
   
   private $_LOCALHOST_LOGGING_CHANNEL;
   private $_STAGE_LOGGING_CHANNEL;
   private $_PREPROD_LOGGING_CHANNEL;
   private $_PROD0_LOGGING_CHANNEL;
   private $_PROD1_LOGGING_CHANNEL;
   private $_PROD2_LOGGING_CHANNEL;
   private $_PROD3_LOGGING_CHANNEL;
   
   private $_LOCALHOST_EMAIL_LOGGING;
   private $_STAGE_EMAIL_LOGGING;
   private $_PREPROD_EMAIL_LOGGING;
   private $_PROD0_EMAIL_LOGGING;
   private $_PROD1_EMAIL_LOGGING;
   private $_PROD2_EMAIL_LOGGING;
   private $_PROD3_EMAIL_LOGGING;
   
   private $_LOCALHOST_CUSTOM_LOG_PATH;
   private $_STAGE_CUSTOM_LOG_PATH;
   private $_PREPROD_CUSTOM_LOG_PATH;
   private $_PROD0_CUSTOM_LOG_PATH;
   private $_PROD1_CUSTOM_LOG_PATH;
   private $_PROD2_CUSTOM_LOG_PATH;
   private $_PROD3_CUSTOM_LOG_PATH;
   
   private $_LOCALHOST_CUSTOM_LOG_FILENAME;
   private $_STAGE_CUSTOM_LOG_FILENAME;
   private $_PREPROD_CUSTOM_LOG_FILENAME;
   private $_PROD0_CUSTOM_LOG_FILENAME;
   private $_PROD1_CUSTOM_LOG_FILENAME;
   private $_PROD2_CUSTOM_LOG_FILENAME;
   private $_PROD3_CUSTOM_LOG_FILENAME;
   
   private $_LOCALHOST_LOG_SERVICE_URI;
   private $_STAGE_LOG_SERVICE_URI;
   private $_PREPROD_LOG_SERVICE_URI;
   private $_PROD0_LOG_SERVICE_URI;
   private $_PROD1_LOG_SERVICE_URI;
   private $_PROD2_LOG_SERVICE_URI;
   private $_PROD3_LOG_SERVICE_URI;
   
   private $_LOCALHOST_LOG_SERVICE_USERNAME;
   private $_STAGE_LOG_SERVICE_USERNAME;
   private $_PREPROD_LOG_SERVICE_USERNAME;
   private $_PROD0_LOG_SERVICE_USERNAME;
   private $_PROD1_LOG_SERVICE_USERNAME;
   private $_PROD2_LOG_SERVICE_USERNAME;
   private $_PROD3_LOG_SERVICE_USERNAME;
   
   private $_LOCALHOST_LOG_SERVICE_PASSWORD;
   private $_STAGE_LOG_SERVICE_PASSWORD;
   private $_PREPROD_LOG_SERVICE_PASSWORD;
   private $_PROD0_LOG_SERVICE_PASSWORD;
   private $_PROD1_LOG_SERVICE_PASSWORD;
   private $_PROD2_LOG_SERVICE_PASSWORD;
   private $_PROD3_LOG_SERVICE_PASSWORD;
   
   private $_LOCALHOST_LOG_SERVICE_TOKEN;
   private $_STAGE_LOG_SERVICE_TOKEN;
   private $_PREPROD_LOG_SERVICE_TOKEN;
   private $_PROD0_LOG_SERVICE_TOKEN;
   private $_PROD1_LOG_SERVICE_TOKEN;
   private $_PROD2_LOG_SERVICE_TOKEN;
   private $_PROD3_LOG_SERVICE_TOKEN;
   
   
   public $_CURR_FILEROOT;
   
   public $_Log;
   
   public function __construct() {
	#
	# INITIALIZE VARIABLES FROM GLOBAL
	$LOCALHOST_FILEROOT_HTTP=__CRNRSTN_LOCALHOST_FILEROOT_HTTP;
	$STAGE_FILEROOT_HTTP=__CRNRSTN_STAGE_FILEROOT_HTTP;
	$PREPROD_FILEROOT_HTTP=__CRNRSTN_PREPROD_FILEROOT_HTTP;
	$PROD0_FILEROOT_HTTP=__CRNRSTN_PROD0_FILEROOT_HTTP;
	$PROD1_FILEROOT_HTTP=__CRNRSTN_PROD1_FILEROOT_HTTP;
	$PROD2_FILEROOT_HTTP=__CRNRSTN_PROD2_FILEROOT_HTTP;
	$PROD3_FILEROOT_HTTP=__CRNRSTN_PROD3_FILEROOT_HTTP;
	
	$LOCALHOST_FILEROOT_NONHTTP=__CRNRSTN_LOCALHOST_FILEROOT_NONHTTP;
	$STAGE_FILEROOT_NONHTTP=__CRNRSTN_STAGE_FILEROOT_NONHTTP;
	$PREPROD_FILEROOT_NONHTTP=__CRNRSTN_PREPROD_FILEROOT_NONHTTP;
	$PROD0_FILEROOT_NONHTTP=__CRNRSTN_PROD0_FILEROOT_NONHTTP;
	$PROD1_FILEROOT_NONHTTP=__CRNRSTN_PROD1_FILEROOT_NONHTTP;
	$PROD2_FILEROOT_NONHTTP=__CRNRSTN_PROD2_FILEROOT_NONHTTP;
	$PROD3_FILEROOT_NONHTTP=__CRNRSTN_PROD3_FILEROOT_NONHTTP;
	
	$LOCALHOST_HTTP=__CRNRSTN_LOCALHOST_HTTP;
	$STAGE_HTTP=__CRNRSTN_STAGE_HTTP;
	$PREPROD_HTTP=__CRNRSTN_PREPROD_HTTP;
	$PROD0_HTTP=__CRNRSTN_PROD0_HTTP;
	$PROD1_HTTP=__CRNRSTN_PROD1_HTTP;
	$PROD2_HTTP=__CRNRSTN_PROD2_HTTP;
	$PROD3_HTTP=__CRNRSTN_PROD3_HTTP;
	
	$LOCALHOST_NAMESPACE=__CRNRSTN_LOCALHOST_NAMESPACE;
	$STAGE_NAMESPACE=__CRNRSTN_STAGE_NAMESPACE;
	$PREPROD_NAMESPACE=__CRNRSTN_PREPROD_NAMESPACE;
	$PROD0_NAMESPACE=__CRNRSTN_PROD0_NAMESPACE;
	$PROD1_NAMESPACE=__CRNRSTN_PROD1_NAMESPACE;
	$PROD2_NAMESPACE=__CRNRSTN_PROD2_NAMESPACE;
	$PROD3_NAMESPACE=__CRNRSTN_PROD3_NAMESPACE;
	
	$LOCALHOST_DBNAME0=__CRNRSTN_LOCALHOST_DBNAME0;
	$STAGE_DBNAME0=__CRNRSTN_STAGE_DBNAME0;
	$PREPROD_DBNAME0=__CRNRSTN_PREPROD_DBNAME0;
	$PROD0_DBNAME0=__CRNRSTN_PROD0_DBNAME0;
	$PROD1_DBNAME0=__CRNRSTN_PROD1_DBNAME0;
	$PROD2_DBNAME0=__CRNRSTN_PROD2_DBNAME0;
	$PROD3_DBNAME0=__CRNRSTN_PROD3_DBNAME0;
	
	$LOCALHOST_DBNAME1=__CRNRSTN_LOCALHOST_DBNAME1;
	$STAGE_DBNAME1=__CRNRSTN_STAGE_DBNAME1;
	$PREPROD_DBNAME1=__CRNRSTN_PREPROD_DBNAME1;
	$PROD0_DBNAME1=__CRNRSTN_PROD0_DBNAME1;
	$PROD1_DBNAME1=__CRNRSTN_PROD1_DBNAME1;
	$PROD2_DBNAME1=__CRNRSTN_PROD2_DBNAME1;
	$PROD3_DBNAME1=__CRNRSTN_PROD3_DBNAME1;
	
	$LOCALHOST_DBNAME2=__CRNRSTN_LOCALHOST_DBNAME2;
	$STAGE_DBNAME2=__CRNRSTN_STAGE_DBNAME2;
	$PREPROD_DBNAME2=__CRNRSTN_PREPROD_DBNAME2;
	$PROD0_DBNAME2=__CRNRSTN_PROD0_DBNAME2;
	$PROD1_DBNAME2=__CRNRSTN_PROD1_DBNAME2;
	$PROD2_DBNAME2=__CRNRSTN_PROD2_DBNAME2;
	$PROD3_DBNAME2=__CRNRSTN_PROD3_DBNAME2;
	
	$LOCALHOST_DBNAME3=__CRNRSTN_LOCALHOST_DBNAME3;
	$STAGE_DBNAME3=__CRNRSTN_STAGE_DBNAME3;
	$PREPROD_DBNAME3=__CRNRSTN_PREPROD_DBNAME3;
	$PROD0_DBNAME3=__CRNRSTN_PROD0_DBNAME3;
	$PROD1_DBNAME3=__CRNRSTN_PROD1_DBNAME3;
	$PROD2_DBNAME3=__CRNRSTN_PROD2_DBNAME3;
	$PROD3_DBNAME3=__CRNRSTN_PROD3_DBNAME3;
	
	$LOCALHOST_DBNAME4=__CRNRSTN_LOCALHOST_DBNAME4;
	$STAGE_DBNAME4=__CRNRSTN_STAGE_DBNAME4;
	$PREPROD_DBNAME4=__CRNRSTN_PREPROD_DBNAME4;
	$PROD0_DBNAME4=__CRNRSTN_PROD0_DBNAME4;
	$PROD1_DBNAME4=__CRNRSTN_PROD1_DBNAME4;
	$PROD2_DBNAME4=__CRNRSTN_PROD2_DBNAME4;
	$PROD3_DBNAME4=__CRNRSTN_PROD3_DBNAME4;
	
	$LOCALHOST_DBUSER0=__CRNRSTN_LOCALHOST_DBUSER0;
	$STAGE_DBUSER0=__CRNRSTN_STAGE_DBUSER0;
	$PREPROD_DBUSER0=__CRNRSTN_PREPROD_DBUSER0;
	$PROD0_DBUSER0=__CRNRSTN_PROD0_DBUSER0;
	$PROD1_DBUSER0=__CRNRSTN_PROD1_DBUSER0;
	$PROD2_DBUSER0=__CRNRSTN_PROD2_DBUSER0;
	$PROD3_DBUSER0=__CRNRSTN_PROD3_DBUSER0;
	
	$LOCALHOST_DBUSER1=__CRNRSTN_LOCALHOST_DBUSER1;
	$STAGE_DBUSER1=__CRNRSTN_STAGE_DBUSER1;
	$PREPROD_DBUSER1=__CRNRSTN_PREPROD_DBUSER1;
	$PROD0_DBUSER1=__CRNRSTN_PROD0_DBUSER1;
	$PROD1_DBUSER1=__CRNRSTN_PROD1_DBUSER1;
	$PROD2_DBUSER1=__CRNRSTN_PROD2_DBUSER1;
	$PROD3_DBUSER1=__CRNRSTN_PROD3_DBUSER1;
	
	$LOCALHOST_DBUSER2=__CRNRSTN_LOCALHOST_DBUSER2;
	$STAGE_DBUSER2=__CRNRSTN_STAGE_DBUSER2;
	$PREPROD_DBUSER2=__CRNRSTN_PREPROD_DBUSER2;
	$PROD0_DBUSER2=__CRNRSTN_PROD0_DBUSER2;
	$PROD1_DBUSER2=__CRNRSTN_PROD1_DBUSER2;
	$PROD2_DBUSER2=__CRNRSTN_PROD2_DBUSER2;
	$PROD3_DBUSER2=__CRNRSTN_PROD3_DBUSER2;
	
	$LOCALHOST_DBUSER3=__CRNRSTN_LOCALHOST_DBUSER3;
	$STAGE_DBUSER3=__CRNRSTN_STAGE_DBUSER3;
	$PREPROD_DBUSER3=__CRNRSTN_PREPROD_DBUSER3;
	$PROD0_DBUSER3=__CRNRSTN_PROD0_DBUSER3;
	$PROD1_DBUSER3=__CRNRSTN_PROD1_DBUSER3;
	$PROD2_DBUSER3=__CRNRSTN_PROD2_DBUSER3;
	$PROD3_DBUSER3=__CRNRSTN_PROD3_DBUSER3;
	
	$LOCALHOST_DBUSER4=__CRNRSTN_LOCALHOST_DBUSER4;
	$STAGE_DBUSER4=__CRNRSTN_STAGE_DBUSER4;
	$PREPROD_DBUSER4=__CRNRSTN_PREPROD_DBUSER4;
	$PROD0_DBUSER4=__CRNRSTN_PROD0_DBUSER4;
	$PROD1_DBUSER4=__CRNRSTN_PROD1_DBUSER4;
	$PROD2_DBUSER4=__CRNRSTN_PROD2_DBUSER4;
	$PROD3_DBUSER4=__CRNRSTN_PROD3_DBUSER4;
	
	$LOCALHOST_DBPORT0=__CRNRSTN_LOCALHOST_DBPORT0;
	$STAGE_DBPORT0=__CRNRSTN_STAGE_DBPORT0;
	$PREPROD_DBPORT0=__CRNRSTN_PREPROD_DBPORT0;
	$PROD0_DBPORT0=__CRNRSTN_PROD0_DBPORT0;
	$PROD1_DBPORT0=__CRNRSTN_PROD1_DBPORT0;
	$PROD2_DBPORT0=__CRNRSTN_PROD2_DBPORT0;
	$PROD3_DBPORT0=__CRNRSTN_PROD3_DBPORT0;
	
	$LOCALHOST_DBPORT1=__CRNRSTN_LOCALHOST_DBPORT1;
	$STAGE_DBPORT1=__CRNRSTN_STAGE_DBPORT1;
	$PREPROD_DBPORT1=__CRNRSTN_PREPROD_DBPORT1;
	$PROD0_DBPORT1=__CRNRSTN_PROD0_DBPORT1;
	$PROD1_DBPORT1=__CRNRSTN_PROD1_DBPORT1;
	$PROD2_DBPORT1=__CRNRSTN_PROD2_DBPORT1;
	$PROD3_DBPORT1=__CRNRSTN_PROD3_DBPORT1;
	
	$LOCALHOST_DBPORT2=__CRNRSTN_LOCALHOST_DBPORT2;
	$STAGE_DBPORT2=__CRNRSTN_STAGE_DBPORT2;
	$PREPROD_DBPORT2=__CRNRSTN_PREPROD_DBPORT2;
	$PROD0_DBPORT2=__CRNRSTN_PROD0_DBPORT2;
	$PROD1_DBPORT2=__CRNRSTN_PROD1_DBPORT2;
	$PROD2_DBPORT2=__CRNRSTN_PROD2_DBPORT2;
	$PROD3_DBPORT2=__CRNRSTN_PROD3_DBPORT2;
	
	$LOCALHOST_DBPORT3=__CRNRSTN_LOCALHOST_DBPORT3;
	$STAGE_DBPORT3=__CRNRSTN_STAGE_DBPORT3;
	$PREPROD_DBPORT3=__CRNRSTN_PREPROD_DBPORT3;
	$PROD0_DBPORT3=__CRNRSTN_PROD0_DBPORT3;
	$PROD1_DBPORT3=__CRNRSTN_PROD1_DBPORT3;
	$PROD2_DBPORT3=__CRNRSTN_PROD2_DBPORT3;
	$PROD3_DBPORT3=__CRNRSTN_PROD3_DBPORT3;
	
	$LOCALHOST_DBPORT4=__CRNRSTN_LOCALHOST_DBPORT4;
	$STAGE_DBPORT4=__CRNRSTN_STAGE_DBPORT4;
	$PREPROD_DBPORT4=__CRNRSTN_PREPROD_DBPORT4;
	$PROD0_DBPORT4=__CRNRSTN_PROD0_DBPORT4;
	$PROD1_DBPORT4=__CRNRSTN_PROD1_DBPORT4;
	$PROD2_DBPORT4=__CRNRSTN_PROD2_DBPORT4;
	$PROD3_DBPORT4=__CRNRSTN_PROD3_DBPORT4;
	
	$LOCALHOST_DBHOST0=__CRNRSTN_LOCALHOST_DBHOST0;
	$STAGE_DBHOST0=__CRNRSTN_STAGE_DBHOST0;
	$PREPROD_DBHOST0=__CRNRSTN_PREPROD_DBHOST0;
	$PROD0_DBHOST0=__CRNRSTN_PROD0_DBHOST0;
	$PROD1_DBHOST0=__CRNRSTN_PROD1_DBHOST0;
	$PROD2_DBHOST0=__CRNRSTN_PROD2_DBHOST0;
	$PROD3_DBHOST0=__CRNRSTN_PROD3_DBHOST0;
	
	$LOCALHOST_DBHOST1=__CRNRSTN_LOCALHOST_DBHOST1;
	$STAGE_DBHOST1=__CRNRSTN_STAGE_DBHOST1;
	$PREPROD_DBHOST1=__CRNRSTN_PREPROD_DBHOST1;
	$PROD0_DBHOST1=__CRNRSTN_PROD0_DBHOST1;
	$PROD1_DBHOST1=__CRNRSTN_PROD1_DBHOST1;
	$PROD2_DBHOST1=__CRNRSTN_PROD2_DBHOST1;
	$PROD3_DBHOST1=__CRNRSTN_PROD3_DBHOST1;
	
	$LOCALHOST_DBHOST2=__CRNRSTN_LOCALHOST_DBHOST2;
	$STAGE_DBHOST2=__CRNRSTN_STAGE_DBHOST2;
	$PREPROD_DBHOST2=__CRNRSTN_PREPROD_DBHOST2;
	$PROD0_DBHOST2=__CRNRSTN_PROD0_DBHOST2;
	$PROD1_DBHOST2=__CRNRSTN_PROD1_DBHOST2;
	$PROD2_DBHOST2=__CRNRSTN_PROD2_DBHOST2;
	$PROD3_DBHOST2=__CRNRSTN_PROD3_DBHOST2;
	
	$LOCALHOST_DBHOST3=__CRNRSTN_LOCALHOST_DBHOST3;
	$STAGE_DBHOST3=__CRNRSTN_STAGE_DBHOST3;
	$PREPROD_DBHOST3=__CRNRSTN_PREPROD_DBHOST3;
	$PROD0_DBHOST3=__CRNRSTN_PROD0_DBHOST3;
	$PROD1_DBHOST3=__CRNRSTN_PROD1_DBHOST3;
	$PROD2_DBHOST3=__CRNRSTN_PROD2_DBHOST3;
	$PROD3_DBHOST3=__CRNRSTN_PROD3_DBHOST3;
	
	$LOCALHOST_DBHOST4=__CRNRSTN_LOCALHOST_DBHOST4;
	$STAGE_DBHOST4=__CRNRSTN_STAGE_DBHOST4;
	$PREPROD_DBHOST4=__CRNRSTN_PREPROD_DBHOST4;
	$PROD0_DBHOST4=__CRNRSTN_PROD0_DBHOST4;
	$PROD1_DBHOST4=__CRNRSTN_PROD1_DBHOST4;
	$PROD2_DBHOST4=__CRNRSTN_PROD2_DBHOST4;
	$PROD3_DBHOST4=__CRNRSTN_PROD3_DBHOST4;
	
	$LOCALHOST_DBPWD0=__CRNRSTN_LOCALHOST_DBPWD0;
	$STAGE_DBPWD0=__CRNRSTN_STAGE_DBPWD0;
	$PREPROD_DBPWD0=__CRNRSTN_PREPROD_DBPWD0;
	$PROD0_DBPWD0=__CRNRSTN_PROD0_DBPWD0;
	$PROD1_DBPWD0=__CRNRSTN_PROD1_DBPWD0;
	$PROD2_DBPWD0=__CRNRSTN_PROD2_DBPWD0;
	$PROD3_DBPWD0=__CRNRSTN_PROD3_DBPWD0;
	
	$LOCALHOST_DBPWD1=__CRNRSTN_LOCALHOST_DBPWD1;
	$STAGE_DBPWD1=__CRNRSTN_STAGE_DBPWD1;
	$PREPROD_DBPWD1=__CRNRSTN_PREPROD_DBPWD1;
	$PROD0_DBPWD1=__CRNRSTN_PROD0_DBPWD1;
	$PROD1_DBPWD1=__CRNRSTN_PROD1_DBPWD1;
	$PROD2_DBPWD1=__CRNRSTN_PROD2_DBPWD1;
	$PROD3_DBPWD1=__CRNRSTN_PROD3_DBPWD1;
	
	$LOCALHOST_DBPWD2=__CRNRSTN_LOCALHOST_DBPWD2;
	$STAGE_DBPWD2=__CRNRSTN_STAGE_DBPWD2;
	$PREPROD_DBPWD2=__CRNRSTN_PREPROD_DBPWD2;
	$PROD0_DBPWD2=__CRNRSTN_PROD0_DBPWD2;
	$PROD1_DBPWD2=__CRNRSTN_PROD1_DBPWD2;
	$PROD2_DBPWD2=__CRNRSTN_PROD2_DBPWD2;
	$PROD3_DBPWD2=__CRNRSTN_PROD3_DBPWD2;
	
	$LOCALHOST_DBPWD3=__CRNRSTN_LOCALHOST_DBPWD3;
	$STAGE_DBPWD3=__CRNRSTN_STAGE_DBPWD3;
	$PREPROD_DBPWD3=__CRNRSTN_PREPROD_DBPWD3;
	$PROD0_DBPWD3=__CRNRSTN_PROD0_DBPWD3;
	$PROD1_DBPWD3=__CRNRSTN_PROD1_DBPWD3;
	$PROD2_DBPWD3=__CRNRSTN_PROD2_DBPWD3;
	$PROD3_DBPWD3=__CRNRSTN_PROD3_DBPWD3;
	
	$LOCALHOST_DBPWD4=__CRNRSTN_LOCALHOST_DBPWD4;
	$STAGE_DBPWD4=__CRNRSTN_STAGE_DBPWD4;
	$PREPROD_DBPWD4=__CRNRSTN_PREPROD_DBPWD4;
	$PROD0_DBPWD4=__CRNRSTN_PROD0_DBPWD4;
	$PROD1_DBPWD4=__CRNRSTN_PROD1_DBPWD4;
	$PROD2_DBPWD4=__CRNRSTN_PROD2_DBPWD4;
	$PROD3_DBPWD4=__CRNRSTN_PROD3_DBPWD4;
	
	$LOCALHOST_MISC_PARAM_A=__CRNRSTN_LOCALHOST_MISC_PARAM_A;
	$STAGE_MISC_PARAM_A=__CRNRSTN_STAGE_MISC_PARAM_A;
	$PREPROD_MISC_PARAM_A=__CRNRSTN_PREPROD_MISC_PARAM_A;
	$PROD0_MISC_PARAM_A=__CRNRSTN_PROD0_MISC_PARAM_A;
	$PROD1_MISC_PARAM_A=__CRNRSTN_PROD1_MISC_PARAM_A;
	$PROD2_MISC_PARAM_A=__CRNRSTN_PROD2_MISC_PARAM_A;
	$PROD3_MISC_PARAM_A=__CRNRSTN_PROD3_MISC_PARAM_A;
	
	$LOCALHOST_MISC_PARAM_B=__CRNRSTN_LOCALHOST_MISC_PARAM_B;
	$STAGE_MISC_PARAM_B=__CRNRSTN_STAGE_MISC_PARAM_B;
	$PREPROD_MISC_PARAM_B=__CRNRSTN_PREPROD_MISC_PARAM_B;
	$PROD0_MISC_PARAM_B=__CRNRSTN_PROD0_MISC_PARAM_B;
	$PROD1_MISC_PARAM_B=__CRNRSTN_PROD1_MISC_PARAM_B;
	$PROD2_MISC_PARAM_B=__CRNRSTN_PROD2_MISC_PARAM_B;
	$PROD3_MISC_PARAM_B=__CRNRSTN_PROD3_MISC_PARAM_B;
	
	$LOCALHOST_MISC_PARAM_C=__CRNRSTN_LOCALHOST_MISC_PARAM_C;
	$STAGE_MISC_PARAM_C=__CRNRSTN_STAGE_MISC_PARAM_C;
	$PREPROD_MISC_PARAM_C=__CRNRSTN_PREPROD_MISC_PARAM_C;
	$PROD0_MISC_PARAM_C=__CRNRSTN_PROD0_MISC_PARAM_C;
	$PROD1_MISC_PARAM_C=__CRNRSTN_PROD1_MISC_PARAM_C;
	$PROD2_MISC_PARAM_C=__CRNRSTN_PROD2_MISC_PARAM_C;
	$PROD3_MISC_PARAM_C=__CRNRSTN_PROD3_MISC_PARAM_C;
	
	$LOCALHOST_MISC_PARAM_D=__CRNRSTN_LOCALHOST_MISC_PARAM_D;
	$STAGE_MISC_PARAM_D=__CRNRSTN_STAGE_MISC_PARAM_D;
	$PREPROD_MISC_PARAM_D=__CRNRSTN_PREPROD_MISC_PARAM_D;
	$PROD0_MISC_PARAM_D=__CRNRSTN_PROD0_MISC_PARAM_D;
	$PROD1_MISC_PARAM_D=__CRNRSTN_PROD1_MISC_PARAM_D;
	$PROD2_MISC_PARAM_D=__CRNRSTN_PROD2_MISC_PARAM_D;
	$PROD3_MISC_PARAM_D=__CRNRSTN_PROD3_MISC_PARAM_D;
	
	$LOCALHOST_MISC_PARAM_E=__CRNRSTN_LOCALHOST_MISC_PARAM_E;
	$STAGE_MISC_PARAM_E=__CRNRSTN_STAGE_MISC_PARAM_E;
	$PREPROD_MISC_PARAM_E=__CRNRSTN_PREPROD_MISC_PARAM_E;
	$PROD0_MISC_PARAM_E=__CRNRSTN_PROD0_MISC_PARAM_E;
	$PROD1_MISC_PARAM_E=__CRNRSTN_PROD1_MISC_PARAM_E;
	$PROD2_MISC_PARAM_E=__CRNRSTN_PROD2_MISC_PARAM_E;
	$PROD3_MISC_PARAM_E=__CRNRSTN_PROD3_MISC_PARAM_E;
	
	$LOCALHOST_MISC_PARAM_F=__CRNRSTN_LOCALHOST_MISC_PARAM_F;
	$STAGE_MISC_PARAM_F=__CRNRSTN_STAGE_MISC_PARAM_F;
	$PREPROD_MISC_PARAM_F=__CRNRSTN_PREPROD_MISC_PARAM_F;
	$PROD0_MISC_PARAM_F=__CRNRSTN_PROD0_MISC_PARAM_F;
	$PROD1_MISC_PARAM_F=__CRNRSTN_PROD1_MISC_PARAM_F;
	$PROD2_MISC_PARAM_F=__CRNRSTN_PROD2_MISC_PARAM_F;
	$PROD3_MISC_PARAM_F=__CRNRSTN_PROD3_MISC_PARAM_F;
	
	$LOCALHOST_MISC_PARAM_G=__CRNRSTN_LOCALHOST_MISC_PARAM_G;
	$STAGE_MISC_PARAM_G=__CRNRSTN_STAGE_MISC_PARAM_G;
	$PREPROD_MISC_PARAM_G=__CRNRSTN_PREPROD_MISC_PARAM_G;
	$PROD0_MISC_PARAM_G=__CRNRSTN_PROD0_MISC_PARAM_G;
	$PROD1_MISC_PARAM_G=__CRNRSTN_PROD1_MISC_PARAM_G;
	$PROD2_MISC_PARAM_G=__CRNRSTN_PROD2_MISC_PARAM_G;
	$PROD3_MISC_PARAM_G=__CRNRSTN_PROD3_MISC_PARAM_G;
	
	$LOCALHOST_LOGGING_CHANNEL=__CRNRSTN_LOCALHOST_LOGGING_CHANNEL;
	$STAGE_LOGGING_CHANNEL=__CRNRSTN_STAGE_LOGGING_CHANNEL;
	$PREPROD_LOGGING_CHANNEL=__CRNRSTN_PREPROD_LOGGING_CHANNEL;
	$PROD0_LOGGING_CHANNEL=__CRNRSTN_PROD0_LOGGING_CHANNEL;
	$PROD1_LOGGING_CHANNEL=__CRNRSTN_PROD1_LOGGING_CHANNEL;
	$PROD2_LOGGING_CHANNEL=__CRNRSTN_PROD2_LOGGING_CHANNEL;
	$PROD3_LOGGING_CHANNEL=__CRNRSTN_PROD3_LOGGING_CHANNEL;
	
	$LOCALHOST_EMAIL_LOGGING=__CRNRSTN_LOCALHOST_EMAIL_LOGGING;
	$STAGE_EMAIL_LOGGING=__CRNRSTN_STAGE_EMAIL_LOGGING;
	$PREPROD_EMAIL_LOGGING=__CRNRSTN_PREPROD_EMAIL_LOGGING;
	$PROD0_EMAIL_LOGGING=__CRNRSTN_PROD0_EMAIL_LOGGING;
	$PROD1_EMAIL_LOGGING=__CRNRSTN_PROD1_EMAIL_LOGGING;
	$PROD2_EMAIL_LOGGING=__CRNRSTN_PROD2_EMAIL_LOGGING;
	$PROD3_EMAIL_LOGGING=__CRNRSTN_PROD3_EMAIL_LOGGING;
	
	$LOCALHOST_CUSTOM_LOG_PATH=__CRNRSTN_LOCALHOST_CUSTOM_LOG_PATH;
	$STAGE_CUSTOM_LOG_PATH=__CRNRSTN_STAGE_CUSTOM_LOG_PATH;
	$PREPROD_CUSTOM_LOG_PATH=__CRNRSTN_PREPROD_CUSTOM_LOG_PATH;
	$PROD0_CUSTOM_LOG_PATH=__CRNRSTN_PROD0_CUSTOM_LOG_PATH;
	$PROD1_CUSTOM_LOG_PATH=__CRNRSTN_PROD1_CUSTOM_LOG_PATH;
	$PROD2_CUSTOM_LOG_PATH=__CRNRSTN_PROD2_CUSTOM_LOG_PATH;
	$PROD3_CUSTOM_LOG_PATH=__CRNRSTN_PROD3_CUSTOM_LOG_PATH;
	
	$LOCALHOST_CUSTOM_LOG_FILENAME=__CRNRSTN_LOCALHOST_CUSTOM_LOG_FILENAME;
	$STAGE_CUSTOM_LOG_FILENAME=__CRNRSTN_STAGE_CUSTOM_LOG_FILENAME;
	$PREPROD_CUSTOM_LOG_FILENAME=__CRNRSTN_PREPROD_CUSTOM_LOG_FILENAME;
	$PROD0_CUSTOM_LOG_FILENAME=__CRNRSTN_PROD0_CUSTOM_LOG_FILENAME;
	$PROD1_CUSTOM_LOG_FILENAME=__CRNRSTN_PROD1_CUSTOM_LOG_FILENAME;
	$PROD2_CUSTOM_LOG_FILENAME=__CRNRSTN_PROD2_CUSTOM_LOG_FILENAME;
	$PROD3_CUSTOM_LOG_FILENAME=__CRNRSTN_PROD3_CUSTOM_LOG_FILENAME;
	
	$LOCALHOST_LOG_SERVICE_URI=__CRNRSTN_LOCALHOST_LOG_SERVICE_URI;
	$STAGE_LOG_SERVICE_URI=__CRNRSTN_STAGE_LOG_SERVICE_URI;
	$PREPROD_LOG_SERVICE_URI=__CRNRSTN_PREPROD_LOG_SERVICE_URI;
	$PROD0_LOG_SERVICE_URI=__CRNRSTN_PROD0_LOG_SERVICE_URI;
	$PROD1_LOG_SERVICE_URI=__CRNRSTN_PROD1_LOG_SERVICE_URI;
	$PROD2_LOG_SERVICE_URI=__CRNRSTN_PROD2_LOG_SERVICE_URI;
	$PROD3_LOG_SERVICE_URI=__CRNRSTN_PROD3_LOG_SERVICE_URI;
	
	$LOCALHOST_LOG_SERVICE_USERNAME=__CRNRSTN_LOCALHOST_LOG_SERVICE_USERNAME;
	$STAGE_LOG_SERVICE_USERNAME=__CRNRSTN_STAGE_LOG_SERVICE_USERNAME;
	$PREPROD_LOG_SERVICE_USERNAME=__CRNRSTN_PREPROD_LOG_SERVICE_USERNAME;
	$PROD0_LOG_SERVICE_USERNAME=__CRNRSTN_PROD0_LOG_SERVICE_USERNAME;
	$PROD1_LOG_SERVICE_USERNAME=__CRNRSTN_PROD1_LOG_SERVICE_USERNAME;
	$PROD2_LOG_SERVICE_USERNAME=__CRNRSTN_PROD2_LOG_SERVICE_USERNAME;
	$PROD3_LOG_SERVICE_USERNAME=__CRNRSTN_PROD3_LOG_SERVICE_USERNAME;
	
	$LOCALHOST_LOG_SERVICE_PASSWORD=__CRNRSTN_LOCALHOST_LOG_SERVICE_PASSWORD;
	$STAGE_LOG_SERVICE_PASSWORD=__CRNRSTN_STAGE_LOG_SERVICE_PASSWORD;
	$PREPROD_LOG_SERVICE_PASSWORD=__CRNRSTN_PREPROD_LOG_SERVICE_PASSWORD;
	$PROD0_LOG_SERVICE_PASSWORD=__CRNRSTN_PROD0_LOG_SERVICE_PASSWORD;
	$PROD1_LOG_SERVICE_PASSWORD=__CRNRSTN_PROD1_LOG_SERVICE_PASSWORD;
	$PROD2_LOG_SERVICE_PASSWORD=__CRNRSTN_PROD2_LOG_SERVICE_PASSWORD;
	$PROD3_LOG_SERVICE_PASSWORD=__CRNRSTN_PROD3_LOG_SERVICE_PASSWORD;
	
	$LOCALHOST_LOG_SERVICE_TOKEN=__CRNRSTN_LOCALHOST_LOG_SERVICE_TOKEN;
	$STAGE_LOG_SERVICE_TOKEN=__CRNRSTN_STAGE_LOG_SERVICE_TOKEN;
	$PREPROD_LOG_SERVICE_TOKEN=__CRNRSTN_PREPROD_LOG_SERVICE_TOKEN;
	$PROD0_LOG_SERVICE_TOKEN=__CRNRSTN_PROD0_LOG_SERVICE_TOKEN;
	$PROD1_LOG_SERVICE_TOKEN=__CRNRSTN_PROD1_LOG_SERVICE_TOKEN;
	$PROD2_LOG_SERVICE_TOKEN=__CRNRSTN_PROD2_LOG_SERVICE_TOKEN;
	$PROD3_LOG_SERVICE_TOKEN=__CRNRSTN_PROD3_LOG_SERVICE_TOKEN;
	  
	$this->_LOCALHOST_FILEROOT_HTTP = addslashes($LOCALHOST_FILEROOT_HTTP);
	$this->_STAGE_FILEROOT_HTTP = addslashes($STAGE_FILEROOT_HTTP);
	$this->_PREPROD_FILEROOT_HTTP = addslashes($PREPROD_FILEROOT_HTTP);
	$this->_PROD0_FILEROOT_HTTP = addslashes($PROD0_FILEROOT_HTTP);
	$this->_PROD1_FILEROOT_HTTP = addslashes($PROD1_FILEROOT_HTTP);
	$this->_PROD2_FILEROOT_HTTP = addslashes($PROD2_FILEROOT_HTTP);
	$this->_PROD3_FILEROOT_HTTP = addslashes($PROD3_FILEROOT_HTTP);
	  
	$this->_LOCALHOST_FILEROOT_NONHTTP = addslashes($LOCALHOST_FILEROOT_NONHTTP);
	$this->_STAGE_FILEROOT_NONHTTP = addslashes($STAGE_FILEROOT_NONHTTP);
	$this->_PREPROD_FILEROOT_NONHTTP = addslashes($PREPROD_FILEROOT_NONHTTP);
	$this->_PROD0_FILEROOT_NONHTTP = addslashes($PROD0_FILEROOT_NONHTTP);
	$this->_PROD1_FILEROOT_NONHTTP = addslashes($PROD1_FILEROOT_NONHTTP);
	$this->_PROD2_FILEROOT_NONHTTP = addslashes($PROD2_FILEROOT_NONHTTP);
	$this->_PROD3_FILEROOT_NONHTTP = addslashes($PROD3_FILEROOT_NONHTTP);
	
	$this->_LOCALHOST_HTTP = addslashes($LOCALHOST_HTTP);
	$this->_STAGE_HTTP = addslashes($STAGE_HTTP);
	$this->_PREPROD_HTTP = addslashes($PREPROD_HTTP);
	$this->_PROD0_HTTP = addslashes($PROD0_HTTP);
	$this->_PROD1_HTTP = addslashes($PROD1_HTTP);
	$this->_PROD2_HTTP = addslashes($PROD2_HTTP);
	$this->_PROD3_HTTP = addslashes($PROD3_HTTP);
	  
	$this->_LOCALHOST_NAMESPACE = addslashes($LOCALHOST_NAMESPACE);
	$this->_STAGE_NAMESPACE = addslashes($STAGE_NAMESPACE);
	$this->_PREPROD_NAMESPACE = addslashes($PREPROD_NAMESPACE);
	$this->_PROD0_NAMESPACE = addslashes($PROD0_NAMESPACE);
	$this->_PROD1_NAMESPACE = addslashes($PROD1_NAMESPACE);
	$this->_PROD2_NAMESPACE = addslashes($PROD2_NAMESPACE);
	$this->_PROD3_NAMESPACE = addslashes($PROD3_NAMESPACE);
	
	$this->_LOCALHOST_DBNAME0 = addslashes($LOCALHOST_DBNAME0);
	$this->_STAGE_DBNAME0 = addslashes($STAGE_DBNAME0);
	$this->_PREPROD_DBNAME0 = addslashes($PREPROD_DBNAME0);
	$this->_PROD0_DBNAME0 = addslashes($PROD0_DBNAME0);
	$this->_PROD1_DBNAME0 = addslashes($PROD1_DBNAME0);
	$this->_PROD2_DBNAME0 = addslashes($PROD2_DBNAME0);
	$this->_PROD3_DBNAME0 = addslashes($PROD3_DBNAME0);
	
	$this->_LOCALHOST_DBNAME1 = addslashes($LOCALHOST_DBNAME1);
	$this->_STAGE_DBNAME1 = addslashes($STAGE_DBNAME1);
	$this->_PREPROD_DBNAME1 = addslashes($PREPROD_DBNAME1);
	$this->_PROD0_DBNAME1 = addslashes($PROD0_DBNAME1);
	$this->_PROD1_DBNAME1 = addslashes($PROD1_DBNAME1);
	$this->_PROD2_DBNAME1 = addslashes($PROD2_DBNAME1);
	$this->_PROD3_DBNAME1 = addslashes($PROD3_DBNAME1);
	
	$this->_LOCALHOST_DBNAME2 = addslashes($LOCALHOST_DBNAME2);
	$this->_STAGE_DBNAME2 = addslashes($STAGE_DBNAME2);
	$this->_PREPROD_DBNAME2 = addslashes($PREPROD_DBNAME2);
	$this->_PROD0_DBNAME2 = addslashes($PROD0_DBNAME2);
	$this->_PROD1_DBNAME2 = addslashes($PROD1_DBNAME2);
	$this->_PROD2_DBNAME2 = addslashes($PROD2_DBNAME2);
	$this->_PROD3_DBNAME2 = addslashes($PROD3_DBNAME2);
	
	$this->_LOCALHOST_DBNAME3 = addslashes($LOCALHOST_DBNAME3);
	$this->_STAGE_DBNAME3 = addslashes($STAGE_DBNAME3);
	$this->_PREPROD_DBNAME3 = addslashes($PREPROD_DBNAME3);
	$this->_PROD0_DBNAME3 = addslashes($PROD0_DBNAME3);
	$this->_PROD1_DBNAME3 = addslashes($PROD1_DBNAME3);
	$this->_PROD2_DBNAME3 = addslashes($PROD2_DBNAME3);
	$this->_PROD3_DBNAME3 = addslashes($PROD3_DBNAME3);
	
	$this->_LOCALHOST_DBNAME4 = addslashes($LOCALHOST_DBNAME4);
	$this->_STAGE_DBNAME4 = addslashes($STAGE_DBNAME4);
	$this->_PREPROD_DBNAME4 = addslashes($PREPROD_DBNAME4);
	$this->_PROD0_DBNAME4 = addslashes($PROD0_DBNAME4);
	$this->_PROD1_DBNAME4 = addslashes($PROD1_DBNAME4);
	$this->_PROD2_DBNAME4 = addslashes($PROD2_DBNAME4);
	$this->_PROD3_DBNAME4 = addslashes($PROD3_DBNAME4);
	  
	$this->_LOCALHOST_DBUSER0 = addslashes($LOCALHOST_DBUSER0);
	$this->_STAGE_DBUSER0 = addslashes($STAGE_DBUSER0);
	$this->_PREPROD_DBUSER0 = addslashes($PREPROD_DBUSER0);
	$this->_PROD0_DBUSER0 = addslashes($PROD0_DBUSER0);
	$this->_PROD1_DBUSER0 = addslashes($PROD1_DBUSER0);
	$this->_PROD2_DBUSER0 = addslashes($PROD2_DBUSER0);
	$this->_PROD3_DBUSER0 = addslashes($PROD3_DBUSER0);
	  
	$this->_LOCALHOST_DBUSER1 = addslashes($LOCALHOST_DBUSER1);
	$this->_STAGE_DBUSER1 = addslashes($STAGE_DBUSER1);
	$this->_PREPROD_DBUSER1 = addslashes($PREPROD_DBUSER1);
	$this->_PROD0_DBUSER1 = addslashes($PROD0_DBUSER1);
	$this->_PROD1_DBUSER1 = addslashes($PROD1_DBUSER1);
	$this->_PROD2_DBUSER1 = addslashes($PROD2_DBUSER1);
	$this->_PROD3_DBUSER1 = addslashes($PROD3_DBUSER1);
	  
	$this->_LOCALHOST_DBUSER2 = addslashes($LOCALHOST_DBUSER2);
	$this->_STAGE_DBUSER2 = addslashes($STAGE_DBUSER2);
	$this->_PREPROD_DBUSER2 = addslashes($PREPROD_DBUSER2);
	$this->_PROD0_DBUSER2 = addslashes($PROD0_DBUSER2);
	$this->_PROD1_DBUSER2 = addslashes($PROD1_DBUSER2);
	$this->_PROD2_DBUSER2 = addslashes($PROD2_DBUSER2);
	$this->_PROD3_DBUSER2 = addslashes($PROD3_DBUSER2);
	  
	$this->_LOCALHOST_DBUSER3 = addslashes($LOCALHOST_DBUSER3);
	$this->_STAGE_DBUSER3 = addslashes($STAGE_DBUSER3);
	$this->_PREPROD_DBUSER3 = addslashes($PREPROD_DBUSER3);
	$this->_PROD0_DBUSER3 = addslashes($PROD0_DBUSER3);
	$this->_PROD1_DBUSER3 = addslashes($PROD1_DBUSER3);
	$this->_PROD2_DBUSER3 = addslashes($PROD2_DBUSER3);
	$this->_PROD3_DBUSER3 = addslashes($PROD3_DBUSER3);
	  
	$this->_LOCALHOST_DBUSER4 = addslashes($LOCALHOST_DBUSER4);
	$this->_STAGE_DBUSER4 = addslashes($STAGE_DBUSER4);
	$this->_PREPROD_DBUSER4 = addslashes($PREPROD_DBUSER4);
	$this->_PROD0_DBUSER4 = addslashes($PROD0_DBUSER4);
	$this->_PROD1_DBUSER4 = addslashes($PROD1_DBUSER4);
	$this->_PROD2_DBUSER4 = addslashes($PROD2_DBUSER4);
	$this->_PROD3_DBUSER4 = addslashes($PROD3_DBUSER4);
	
	$this->_LOCALHOST_DBPORT0 = addslashes($LOCALHOST_DBPORT0);
	$this->_STAGE_DBPORT0 = addslashes($STAGE_DBPORT0);
	$this->_PREPROD_DBPORT0 = addslashes($PREPROD_DBPORT0);
	$this->_PROD0_DBPORT0 = addslashes($PROD0_DBPORT0);
	$this->_PROD1_DBPORT0 = addslashes($PROD1_DBPORT0);
	$this->_PROD2_DBPORT0 = addslashes($PROD2_DBPORT0);
	$this->_PROD3_DBPORT0 = addslashes($PROD3_DBPORT0);
	
	$this->_LOCALHOST_DBPORT1 = addslashes($LOCALHOST_DBPORT1);
	$this->_STAGE_DBPORT1 = addslashes($STAGE_DBPORT1);
	$this->_PREPROD_DBPORT1 = addslashes($PREPROD_DBPORT1);
	$this->_PROD0_DBPORT1 = addslashes($PROD0_DBPORT1);
	$this->_PROD1_DBPORT1 = addslashes($PROD1_DBPORT1);
	$this->_PROD2_DBPORT1 = addslashes($PROD2_DBPORT1);
	$this->_PROD3_DBPORT1 = addslashes($PROD3_DBPORT1);
	
	$this->_LOCALHOST_DBPORT2 = addslashes($LOCALHOST_DBPORT2);
	$this->_STAGE_DBPORT2 = addslashes($STAGE_DBPORT2);
	$this->_PREPROD_DBPORT2 = addslashes($PREPROD_DBPORT2);
	$this->_PROD0_DBPORT2 = addslashes($PROD0_DBPORT2);
	$this->_PROD1_DBPORT2 = addslashes($PROD1_DBPORT2);
	$this->_PROD2_DBPORT2 = addslashes($PROD2_DBPORT2);
	$this->_PROD3_DBPORT2 = addslashes($PROD3_DBPORT2);
	  
	$this->_LOCALHOST_DBPORT3 = addslashes($LOCALHOST_DBPORT3);
	$this->_STAGE_DBPORT3 = addslashes($STAGE_DBPORT3);
	$this->_PREPROD_DBPORT3 = addslashes($PREPROD_DBPORT3);
	$this->_PROD0_DBPORT3 = addslashes($PROD0_DBPORT3);
	$this->_PROD1_DBPORT3 = addslashes($PROD1_DBPORT3);
	$this->_PROD2_DBPORT3 = addslashes($PROD2_DBPORT3);
	$this->_PROD3_DBPORT3 = addslashes($PROD3_DBPORT3);
	  
	$this->_LOCALHOST_DBPORT4 = addslashes($LOCALHOST_DBPORT4);
	$this->_STAGE_DBPORT4 = addslashes($STAGE_DBPORT4);
	$this->_PREPROD_DBPORT4 = addslashes($PREPROD_DBPORT4);
	$this->_PROD0_DBPORT4 = addslashes($PROD0_DBPORT4);
	$this->_PROD1_DBPORT4 = addslashes($PROD1_DBPORT4);
	$this->_PROD2_DBPORT4 = addslashes($PROD2_DBPORT4);
	$this->_PROD3_DBPORT4 = addslashes($PROD3_DBPORT4);
	
	$this->_LOCALHOST_DBHOST0 = addslashes($LOCALHOST_DBHOST0);
	$this->_STAGE_DBHOST0 = addslashes($STAGE_DBHOST0);
	$this->_PREPROD_DBHOST0 = addslashes($PREPROD_DBHOST0);
	$this->_PROD0_DBHOST0 = addslashes($PROD0_DBHOST0);
	$this->_PROD1_DBHOST0 = addslashes($PROD1_DBHOST0);
	$this->_PROD2_DBHOST0 = addslashes($PROD2_DBHOST0);
	$this->_PROD3_DBHOST0 = addslashes($PROD3_DBHOST0);
	
	$this->_LOCALHOST_DBHOST1 = addslashes($LOCALHOST_DBHOST1);
	$this->_STAGE_DBHOST1 = addslashes($STAGE_DBHOST1);
	$this->_PREPROD_DBHOST1 = addslashes($PREPROD_DBHOST1);
	$this->_PROD0_DBHOST1 = addslashes($PROD0_DBHOST1);
	$this->_PROD1_DBHOST1 = addslashes($PROD1_DBHOST1);
	$this->_PROD2_DBHOST1 = addslashes($PROD2_DBHOST1);
	$this->_PROD3_DBHOST1 = addslashes($PROD3_DBHOST1);
	
	$this->_LOCALHOST_DBHOST2 = addslashes($LOCALHOST_DBHOST2);
	$this->_STAGE_DBHOST2 = addslashes($STAGE_DBHOST2);
	$this->_PREPROD_DBHOST2 = addslashes($PREPROD_DBHOST2);
	$this->_PROD0_DBHOST2 = addslashes($PROD0_DBHOST2);
	$this->_PROD1_DBHOST2 = addslashes($PROD1_DBHOST2);
	$this->_PROD2_DBHOST2 = addslashes($PROD2_DBHOST2);
	$this->_PROD3_DBHOST2 = addslashes($PROD3_DBHOST2);
	
 	$this->_LOCALHOST_DBHOST3 = addslashes($LOCALHOST_DBHOST3);
	$this->_STAGE_DBHOST3 = addslashes($STAGE_DBHOST3);
	$this->_PREPROD_DBHOST3 = addslashes($PREPROD_DBHOST3);
	$this->_PROD0_DBHOST3 = addslashes($PROD0_DBHOST3);
	$this->_PROD1_DBHOST3 = addslashes($PROD1_DBHOST3);
	$this->_PROD2_DBHOST3 = addslashes($PROD2_DBHOST3);
	$this->_PROD3_DBHOST3 = addslashes($PROD3_DBHOST3);
	
 	$this->_LOCALHOST_DBHOST4 = addslashes($LOCALHOST_DBHOST4);
	$this->_STAGE_DBHOST4 = addslashes($STAGE_DBHOST4);
	$this->_PREPROD_DBHOST4 = addslashes($PREPROD_DBHOST4);
	$this->_PROD0_DBHOST4 = addslashes($PROD0_DBHOST4);
	$this->_PROD1_DBHOST4 = addslashes($PROD1_DBHOST4);
	$this->_PROD2_DBHOST4 = addslashes($PROD2_DBHOST4);
	$this->_PROD3_DBHOST4 = addslashes($PROD3_DBHOST4);
	
	$this->_LOCALHOST_DBPWD0 = addslashes($LOCALHOST_DBPWD0);
	$this->_STAGE_DBPWD0 = addslashes($STAGE_DBPWD0);
	$this->_PREPROD_DBPWD0 = addslashes($PREPROD_DBPWD0);
	$this->_PROD0_DBPWD0 = addslashes($PROD0_DBPWD0);
	$this->_PROD1_DBPWD0 = addslashes($PROD1_DBPWD0);
	$this->_PROD2_DBPWD0 = addslashes($PROD2_DBPWD0);
	$this->_PROD3_DBPWD0 = addslashes($PROD3_DBPWD0);
	
	$this->_LOCALHOST_DBPWD1 = addslashes($LOCALHOST_DBPWD1);
	$this->_STAGE_DBPWD1 = addslashes($STAGE_DBPWD1);
	$this->_PREPROD_DBPWD1 = addslashes($PREPROD_DBPWD1);
	$this->_PROD0_DBPWD1 = addslashes($PROD0_DBPWD1);
	$this->_PROD1_DBPWD1 = addslashes($PROD1_DBPWD1);
	$this->_PROD2_DBPWD1 = addslashes($PROD2_DBPWD1);
	$this->_PROD3_DBPWD1 = addslashes($PROD3_DBPWD1);
	
	$this->_LOCALHOST_DBPWD2 = addslashes($LOCALHOST_DBPWD2);
	$this->_STAGE_DBPWD2 = addslashes($STAGE_DBPWD2);
	$this->_PREPROD_DBPWD2 = addslashes($PREPROD_DBPWD2);
	$this->_PROD0_DBPWD2 = addslashes($PROD0_DBPWD2);
	$this->_PROD1_DBPWD2 = addslashes($PROD1_DBPWD2);
	$this->_PROD2_DBPWD2 = addslashes($PROD2_DBPWD2);
	$this->_PROD3_DBPWD2 = addslashes($PROD3_DBPWD2);
	  
	$this->_LOCALHOST_DBPWD3 = addslashes($LOCALHOST_DBPWD3);
	$this->_STAGE_DBPWD3 = addslashes($STAGE_DBPWD3);
	$this->_PREPROD_DBPWD3 = addslashes($PREPROD_DBPWD3);
	$this->_PROD0_DBPWD3 = addslashes($PROD0_DBPWD3);
	$this->_PROD1_DBPWD3 = addslashes($PROD1_DBPWD3);
	$this->_PROD2_DBPWD3 = addslashes($PROD2_DBPWD3);
	$this->_PROD3_DBPWD3 = addslashes($PROD3_DBPWD3);
	  
	$this->_LOCALHOST_DBPWD4 = addslashes($LOCALHOST_DBPWD4);
	$this->_STAGE_DBPWD4 = addslashes($STAGE_DBPWD4);
	$this->_PREPROD_DBPWD4 = addslashes($PREPROD_DBPWD4);
	$this->_PROD0_DBPWD4 = addslashes($PROD0_DBPWD4);
	$this->_PROD1_DBPWD4 = addslashes($PROD1_DBPWD4);
	$this->_PROD2_DBPWD4 = addslashes($PROD2_DBPWD4);
	$this->_PROD3_DBPWD4 = addslashes($PROD3_DBPWD4);
	  
	$this->_LOCALHOST_LOGGING_CHANNEL = addslashes($LOCALHOST_LOGGING_CHANNEL);
	$this->_STAGE_LOGGING_CHANNEL = addslashes($STAGE_LOGGING_CHANNEL);
	$this->_PREPROD_LOGGING_CHANNEL = addslashes($PREPROD_LOGGING_CHANNEL);
	$this->_PROD0_LOGGING_CHANNEL = addslashes($PROD0_LOGGING_CHANNEL);
	$this->_PROD1_LOGGING_CHANNEL = addslashes($PROD1_LOGGING_CHANNEL);
	$this->_PROD2_LOGGING_CHANNEL = addslashes($PROD2_LOGGING_CHANNEL);
	$this->_PROD3_LOGGING_CHANNEL = addslashes($PROD3_LOGGING_CHANNEL);
	
	$this->_LOCALHOST_EMAIL_LOGGING = addslashes($LOCALHOST_EMAIL_LOGGING);
	$this->_STAGE_EMAIL_LOGGING = addslashes($STAGE_EMAIL_LOGGING);
	$this->_PREPROD_EMAIL_LOGGING = addslashes($PREPROD_EMAIL_LOGGING);
	$this->_PROD0_EMAIL_LOGGING = addslashes($PROD0_EMAIL_LOGGING);
	$this->_PROD1_EMAIL_LOGGING = addslashes($PROD1_EMAIL_LOGGING);
	$this->_PROD2_EMAIL_LOGGING = addslashes($PROD2_EMAIL_LOGGING);
	$this->_PROD3_EMAIL_LOGGING = addslashes($PROD3_EMAIL_LOGGING);
	
	$this->_LOCALHOST_CUSTOM_LOG_PATH = addslashes($LOCALHOST_CUSTOM_LOG_PATH);
	$this->_STAGE_CUSTOM_LOG_PATH = addslashes($STAGE_CUSTOM_LOG_PATH);
	$this->_PREPROD_CUSTOM_LOG_PATH = addslashes($PREPROD_CUSTOM_LOG_PATH);
	$this->_PROD0_CUSTOM_LOG_PATH = addslashes($PROD0_CUSTOM_LOG_PATH);
	$this->_PROD1_CUSTOM_LOG_PATH = addslashes($PROD1_CUSTOM_LOG_PATH);
	$this->_PROD2_CUSTOM_LOG_PATH = addslashes($PROD2_CUSTOM_LOG_PATH);
	$this->_PROD3_CUSTOM_LOG_PATH = addslashes($PROD3_CUSTOM_LOG_PATH);
	
	$this->_LOCALHOST_CUSTOM_LOG_FILENAME = addslashes($LOCALHOST_CUSTOM_LOG_FILENAME);
	$this->_STAGE_CUSTOM_LOG_FILENAME = addslashes($STAGE_CUSTOM_LOG_FILENAME);
	$this->_PREPROD_CUSTOM_LOG_FILENAME = addslashes($PREPROD_CUSTOM_LOG_FILENAME);
	$this->_PROD0_CUSTOM_LOG_FILENAME = addslashes($PROD0_CUSTOM_LOG_FILENAME);
	$this->_PROD1_CUSTOM_LOG_FILENAME = addslashes($PROD1_CUSTOM_LOG_FILENAME);
	$this->_PROD2_CUSTOM_LOG_FILENAME = addslashes($PROD2_CUSTOM_LOG_FILENAME);
	$this->_PROD3_CUSTOM_LOG_FILENAME = addslashes($PROD3_CUSTOM_LOG_FILENAME);
	
	$this->_LOCALHOST_LOG_SERVICE_URI = addslashes($LOCALHOST_LOG_SERVICE_URI);
	$this->_STAGE_LOG_SERVICE_URI = addslashes($STAGE_LOG_SERVICE_URI);
	$this->_PREPROD_LOG_SERVICE_URI = addslashes($PREPROD_LOG_SERVICE_URI);
	$this->_PROD0_LOG_SERVICE_URI = addslashes($PROD0_LOG_SERVICE_URI);
	$this->_PROD1_LOG_SERVICE_URI = addslashes($PROD1_LOG_SERVICE_URI);
	$this->_PROD2_LOG_SERVICE_URI = addslashes($PROD2_LOG_SERVICE_URI);
	$this->_PROD3_LOG_SERVICE_URI = addslashes($PROD3_LOG_SERVICE_URI);
	
	$this->_LOCALHOST_LOG_SERVICE_USERNAME = addslashes($LOCALHOST_LOG_SERVICE_USERNAME);
	$this->_STAGE_LOG_SERVICE_USERNAME = addslashes($STAGE_LOG_SERVICE_USERNAME);
	$this->_PREPROD_LOG_SERVICE_USERNAME = addslashes($PREPROD_LOG_SERVICE_USERNAME);
	$this->_PROD0_LOG_SERVICE_USERNAME = addslashes($PROD0_LOG_SERVICE_USERNAME);
	$this->_PROD1_LOG_SERVICE_USERNAME = addslashes($PROD1_LOG_SERVICE_USERNAME);
	$this->_PROD2_LOG_SERVICE_USERNAME = addslashes($PROD2_LOG_SERVICE_USERNAME);
	$this->_PROD3_LOG_SERVICE_USERNAME = addslashes($PROD3_LOG_SERVICE_USERNAME);
	
	$this->_LOCALHOST_LOG_SERVICE_PASSWORD = addslashes($LOCALHOST_LOG_SERVICE_PASSWORD);
	$this->_STAGE_LOG_SERVICE_PASSWORD = addslashes($STAGE_LOG_SERVICE_PASSWORD);
	$this->_PREPROD_LOG_SERVICE_PASSWORD = addslashes($PREPROD_LOG_SERVICE_PASSWORD);
	$this->_PROD0_LOG_SERVICE_PASSWORD = addslashes($PROD0_LOG_SERVICE_PASSWORD);
	$this->_PROD1_LOG_SERVICE_PASSWORD = addslashes($PROD1_LOG_SERVICE_PASSWORD);
	$this->_PROD2_LOG_SERVICE_PASSWORD = addslashes($PROD2_LOG_SERVICE_PASSWORD);
	$this->_PROD3_LOG_SERVICE_PASSWORD = addslashes($PROD3_LOG_SERVICE_PASSWORD);
	
	$this->_LOCALHOST_LOG_SERVICE_TOKEN = addslashes($LOCALHOST_LOG_SERVICE_TOKEN);
	$this->_STAGE_LOG_SERVICE_TOKEN = addslashes($STAGE_LOG_SERVICE_TOKEN);
	$this->_PREPROD_LOG_SERVICE_TOKEN = addslashes($PREPROD_LOG_SERVICE_TOKEN);
	$this->_PROD0_LOG_SERVICE_TOKEN = addslashes($PROD0_LOG_SERVICE_TOKEN);
	$this->_PROD1_LOG_SERVICE_TOKEN = addslashes($PROD1_LOG_SERVICE_TOKEN);
	$this->_PROD2_LOG_SERVICE_TOKEN = addslashes($PROD2_LOG_SERVICE_TOKEN);
	$this->_PROD3_LOG_SERVICE_TOKEN = addslashes($PROD3_LOG_SERVICE_TOKEN);
	  
	$this->_LOCALHOST_MISC_PARAM_A = addslashes($LOCALHOST_MISC_PARAM_A);
	$this->_STAGE_MISC_PARAM_A = addslashes($STAGE_MISC_PARAM_A);
	$this->_PREPROD_MISC_PARAM_A = addslashes($PREPROD_MISC_PARAM_A);
	$this->_PROD0_MISC_PARAM_A = addslashes($PROD0_MISC_PARAM_A);
	$this->_PROD1_MISC_PARAM_A = addslashes($PROD1_MISC_PARAM_A);
	$this->_PROD2_MISC_PARAM_A = addslashes($PROD2_MISC_PARAM_A);
	$this->_PROD3_MISC_PARAM_A = addslashes($PROD3_MISC_PARAM_A);
	
	$this->_LOCALHOST_MISC_PARAM_B = addslashes($LOCALHOST_MISC_PARAM_B);
	$this->_STAGE_MISC_PARAM_B = addslashes($STAGE_MISC_PARAM_B);
	$this->_PREPROD_MISC_PARAM_B = addslashes($PREPROD_MISC_PARAM_B);
	$this->_PROD0_MISC_PARAM_B = addslashes($PROD0_MISC_PARAM_B);
	$this->_PROD1_MISC_PARAM_B = addslashes($PROD1_MISC_PARAM_B);
	$this->_PROD2_MISC_PARAM_B = addslashes($PROD2_MISC_PARAM_B);
	$this->_PROD3_MISC_PARAM_B = addslashes($PROD3_MISC_PARAM_B);
	  
	$this->_LOCALHOST_MISC_PARAM_C = addslashes($LOCALHOST_MISC_PARAM_C);
	$this->_STAGE_MISC_PARAM_C = addslashes($STAGE_MISC_PARAM_C);
	$this->_PREPROD_MISC_PARAM_C = addslashes($PREPROD_MISC_PARAM_C);
	$this->_PROD0_MISC_PARAM_C = addslashes($PROD0_MISC_PARAM_C);
	$this->_PROD1_MISC_PARAM_C = addslashes($PROD1_MISC_PARAM_C);
	$this->_PROD2_MISC_PARAM_C = addslashes($PROD2_MISC_PARAM_C);
	$this->_PROD3_MISC_PARAM_C = addslashes($PROD3_MISC_PARAM_C);
	  
	$this->_LOCALHOST_MISC_PARAM_D = addslashes($LOCALHOST_MISC_PARAM_D);
	$this->_STAGE_MISC_PARAM_D = addslashes($STAGE_MISC_PARAM_D);
	$this->_PREPROD_MISC_PARAM_D = addslashes($PREPROD_MISC_PARAM_D);
	$this->_PROD0_MISC_PARAM_D = addslashes($PROD0_MISC_PARAM_D);
	$this->_PROD1_MISC_PARAM_D = addslashes($PROD1_MISC_PARAM_D);
	$this->_PROD2_MISC_PARAM_D = addslashes($PROD2_MISC_PARAM_D);
	$this->_PROD3_MISC_PARAM_D = addslashes($PROD3_MISC_PARAM_D);
	  
	$this->_LOCALHOST_MISC_PARAM_E = addslashes($LOCALHOST_MISC_PARAM_E);
	$this->_STAGE_MISC_PARAM_E = addslashes($STAGE_MISC_PARAM_E);
	$this->_PREPROD_MISC_PARAM_E = addslashes($PREPROD_MISC_PARAM_E);
	$this->_PROD0_MISC_PARAM_E = addslashes($PROD0_MISC_PARAM_E);
	$this->_PROD1_MISC_PARAM_E = addslashes($PROD1_MISC_PARAM_E);
	$this->_PROD2_MISC_PARAM_E = addslashes($PROD2_MISC_PARAM_E);
	$this->_PROD3_MISC_PARAM_E = addslashes($PROD3_MISC_PARAM_E);
	  
	$this->_LOCALHOST_MISC_PARAM_F = addslashes($LOCALHOST_MISC_PARAM_F);
	$this->_STAGE_MISC_PARAM_F = addslashes($STAGE_MISC_PARAM_F);
	$this->_PREPROD_MISC_PARAM_F = addslashes($PREPROD_MISC_PARAM_F);
	$this->_PROD0_MISC_PARAM_F = addslashes($PROD0_MISC_PARAM_F);
	$this->_PROD1_MISC_PARAM_F = addslashes($PROD1_MISC_PARAM_F);
	$this->_PROD2_MISC_PARAM_F = addslashes($PROD2_MISC_PARAM_F);
	$this->_PROD3_MISC_PARAM_F = addslashes($PROD3_MISC_PARAM_F);
	  
	$this->_LOCALHOST_MISC_PARAM_G = addslashes($LOCALHOST_MISC_PARAM_G);
	$this->_STAGE_MISC_PARAM_G = addslashes($STAGE_MISC_PARAM_G);
	$this->_PREPROD_MISC_PARAM_G = addslashes($PREPROD_MISC_PARAM_G);
	$this->_PROD0_MISC_PARAM_G = addslashes($PROD0_MISC_PARAM_G);
	$this->_PROD1_MISC_PARAM_G = addslashes($PROD1_MISC_PARAM_G);
	$this->_PROD2_MISC_PARAM_G = addslashes($PROD2_MISC_PARAM_G);
	$this->_PROD3_MISC_PARAM_G = addslashes($PROD3_MISC_PARAM_G);
	  
	$this->_CURR_FILEROOT=realpath(dirname($_SERVER['SCRIPT_FILENAME']));
   }

   // THIS WILL BE CALLED AUTOMATICALLY AT THE END OF SCOPE
   public function __destruct() {
      
   }
   
   public function FILEROOT_HTTP(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_FILEROOT_HTTP;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_FILEROOT_HTTP;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_FILEROOT_HTTP;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_FILEROOT_HTTP;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_FILEROOT_HTTP;
		break;
	   	case "STAGE":
			return $this->_STAGE_FILEROOT_HTTP;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_FILEROOT_HTTP;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function FILEROOT_NONHTTP(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_FILEROOT_NONHTTP;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_FILEROOT_NONHTTP;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_FILEROOT_NONHTTP;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_FILEROOT_NONHTTP;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_FILEROOT_NONHTTP;
		break;
	   	case "STAGE":
			return $this->_STAGE_FILEROOT_NONHTTP;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_FILEROOT_NONHTTP;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function HTTP(){
	   switch($this->getEnvironment()){
	   	case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_HTTP;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_HTTP;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_HTTP;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_HTTP;
		break;
		case "PREPROD":
			return $this->_PREPROD_HTTP;
		break;
		case "STAGE":
			return $this->_STAGE_HTTP;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_HTTP;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function NAMESPACE(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_NAMESPACE;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_NAMESPACE;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_NAMESPACE;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_NAMESPACE;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_NAMESPACE;
		break;
	   	case "STAGE":
			return $this->_STAGE_NAMESPACE;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_NAMESPACE;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function DBNAME0(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBNAME0;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBNAME0;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBNAME0;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBNAME0;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBNAME0;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBNAME0;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBNAME0;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBNAME1(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBNAME1;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBNAME1;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBNAME1;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBNAME1;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBNAME1;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBNAME1;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBNAME1;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBNAME2(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBNAME2;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBNAME2;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBNAME2;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBNAME2;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBNAME2;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBNAME2;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBNAME2;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBNAME3(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBNAME3;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBNAME3;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBNAME3;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBNAME3;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBNAME3;
		break;
		case "STAGE":
			return $this->_STAGE_DBNAME3;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBNAME3;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBNAME4(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBNAME4;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBNAME4;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBNAME4;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBNAME4;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBNAME4;
		break;
		case "STAGE":
			return $this->_STAGE_DBNAME4;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBNAME4;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBUSER0(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBUSER0;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBUSER0;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBUSER0;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBUSER0;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBUSER0;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBUSER0;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBUSER0;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBUSER1(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBUSER1;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBUSER1;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBUSER1;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBUSER1;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBUSER1;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBUSER1;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBUSER1;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBUSER2(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBUSER2;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBUSER2;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBUSER2;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBUSER2;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBUSER2;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBUSER2;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBUSER2;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBUSER3(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBUSER3;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBUSER3;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBUSER3;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBUSER3;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBUSER3;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBUSER3;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBUSER3;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBUSER4(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBUSER4;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBUSER4;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBUSER4;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBUSER4;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBUSER4;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBUSER4;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBUSER4;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBHOST0(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBHOST0;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBHOST0;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBHOST0;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBHOST0;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBHOST0;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBHOST0;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBHOST0;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBHOST1(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBHOST1;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBHOST1;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBHOST1;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBHOST1;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBHOST1;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBHOST1;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBHOST1;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBHOST2(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBHOST2;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBHOST2;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBHOST2;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBHOST2;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBHOST2;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBHOST2;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBHOST2;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBHOST3(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBHOST3;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBHOST3;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBHOST3;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBHOST3;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBHOST3;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBHOST3;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBHOST3;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBHOST4(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBHOST4;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBHOST4;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBHOST4;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBHOST4;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBHOST4;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBHOST4;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBHOST4;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }
   }
   
   public function DBPORT0(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPORT0;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPORT0;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPORT0;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPORT0;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPORT0;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPORT0;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBPORT0;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function DBPORT1(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPORT1;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPORT1;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPORT1;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPORT1;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPORT1;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPORT1;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBPORT1;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function DBPORT2(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPORT2;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPORT2;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPORT2;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPORT2;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPORT2;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPORT2;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBPORT2;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function DBPORT3(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPORT3;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPORT3;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPORT3;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPORT3;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPORT3;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPORT3;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBPORT3;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function DBPORT4(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPORT4;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPORT4;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPORT4;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPORT4;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPORT4;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPORT4;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_DBPORT4;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function DBPWD0(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPWD0;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPWD0;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPWD0;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPWD0;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPWD0;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPWD0;
		break;
	    case "LOCALHOST":
			return $this->_LOCALHOST_DBPWD0;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
   }
   
   public function DBPWD1(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPWD1;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPWD1;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPWD1;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPWD1;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPWD1;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPWD1;
		break;
	    case "LOCALHOST":
			return $this->_LOCALHOST_DBPWD1;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
   }
   
   public function DBPWD2(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPWD2;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPWD2;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPWD2;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPWD2;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPWD2;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPWD2;
		break;
	    case "LOCALHOST":
			return $this->_LOCALHOST_DBPWD2;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
   }
   
   public function DBPWD3(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPWD3;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPWD3;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPWD3;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPWD3;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPWD3;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPWD3;
		break;
	    case "LOCALHOST":
			return $this->_LOCALHOST_DBPWD3;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
   }
   
   public function DBPWD4(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_DBPWD4;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_DBPWD4;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_DBPWD4;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_DBPWD4;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_DBPWD4;
		break;
	   	case "STAGE":
			return $this->_STAGE_DBPWD4;
		break;
	    case "LOCALHOST":
			return $this->_LOCALHOST_DBPWD4;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
   }
   
   public function LOGGING_CHANNEL(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_LOGGING_CHANNEL;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_LOGGING_CHANNEL;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_LOGGING_CHANNEL;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_LOGGING_CHANNEL;
		break;
		case "PREPROD":
			return $this->_PREPROD_LOGGING_CHANNEL;
		break;
		case "STAGE":
			return $this->_STAGE_LOGGING_CHANNEL;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_LOGGING_CHANNEL;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}
   
	public function EMAIL_LOGGING(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_EMAIL_LOGGING;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_EMAIL_LOGGING;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_EMAIL_LOGGING;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_EMAIL_LOGGING;
		break;
		case "PREPROD":
			return $this->_PREPROD_EMAIL_LOGGING;
		break;
		case "STAGE":
			return $this->_STAGE_EMAIL_LOGGING;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_EMAIL_LOGGING;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}
	
	public function CUSTOM_LOG_PATH(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_CUSTOM_LOG_PATH;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_CUSTOM_LOG_PATH;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_CUSTOM_LOG_PATH;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_CUSTOM_LOG_PATH;
		break;
		case "PREPROD":
			return $this->_PREPROD_CUSTOM_LOG_PATH;
		break;
		case "STAGE":
			return $this->_STAGE_CUSTOM_LOG_PATH;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_CUSTOM_LOG_PATH;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}
	
	public function CUSTOM_LOG_FILENAME(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_CUSTOM_LOG_FILENAME;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_CUSTOM_LOG_FILENAME;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_CUSTOM_LOG_FILENAME;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_CUSTOM_LOG_FILENAME;
		break;
		case "PREPROD":
			return $this->_PREPROD_CUSTOM_LOG_FILENAME;
		break;
		case "STAGE":
			return $this->_STAGE_CUSTOM_LOG_FILENAME;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_CUSTOM_LOG_FILENAME;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}

	public function LOG_SERVICE_URI(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_LOG_SERVICE_URI;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_LOG_SERVICE_URI;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_LOG_SERVICE_URI;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_LOG_SERVICE_URI;
		break;
		case "PREPROD":
			return $this->_PREPROD_LOG_SERVICE_URI;
		break;
		case "STAGE":
			return $this->_STAGE_LOG_SERVICE_URI;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_LOG_SERVICE_URI;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}

	public function LOG_SERVICE_USERNAME(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_LOG_SERVICE_USERNAME;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_LOG_SERVICE_USERNAME;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_LOG_SERVICE_USERNAME;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_LOG_SERVICE_USERNAME;
		break;
		case "PREPROD":
			return $this->_PREPROD_LOG_SERVICE_USERNAME;
		break;
		case "STAGE":
			return $this->_STAGE_LOG_SERVICE_USERNAME;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_LOG_SERVICE_USERNAME;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}

	public function LOG_SERVICE_PASSWORD(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_LOG_SERVICE_PASSWORD;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_LOG_SERVICE_PASSWORD;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_LOG_SERVICE_PASSWORD;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_LOG_SERVICE_PASSWORD;
		break;
		case "PREPROD":
			return $this->_PREPROD_LOG_SERVICE_PASSWORD;
		break;
		case "STAGE":
			return $this->_STAGE_LOG_SERVICE_PASSWORD;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_LOG_SERVICE_PASSWORD;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}

	public function LOG_SERVICE_TOKEN(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_LOG_SERVICE_TOKEN;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_LOG_SERVICE_TOKEN;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_LOG_SERVICE_TOKEN;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_LOG_SERVICE_TOKEN;
		break;
		case "PREPROD":
			return $this->_PREPROD_LOG_SERVICE_TOKEN;
		break;
		case "STAGE":
			return $this->_STAGE_LOG_SERVICE_TOKEN;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_LOG_SERVICE_TOKEN;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   }     
	}

   public function MISC_PARAM_A(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_A;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_A;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_A;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_A;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_A;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_A;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_A;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function MISC_PARAM_B(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_B;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_B;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_B;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_B;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_B;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_B;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_B;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function MISC_PARAM_C(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_C;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_C;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_C;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_C;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_C;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_C;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_C;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function MISC_PARAM_D(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_D;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_D;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_D;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_D;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_D;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_D;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_D;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function MISC_PARAM_E(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_E;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_E;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_E;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_E;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_E;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_E;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_E;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function MISC_PARAM_F(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_F;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_F;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_F;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_F;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_F;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_F;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_F;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function MISC_PARAM_G(){
	   switch($this->getEnvironment()){
		case "PROD0_FILEROOT_HTTP":
			return $this->_PROD0_MISC_PARAM_G;
		break;
		case "PROD1_FILEROOT_HTTP":
			return $this->_PROD1_MISC_PARAM_G;
		break;
		case "PROD2_FILEROOT_HTTP":
			return $this->_PROD2_MISC_PARAM_G;
		break;
		case "PROD3_FILEROOT_HTTP":
			return $this->_PROD3_MISC_PARAM_G;
		break;
	   	case "PREPROD":
			return $this->_PREPROD_MISC_PARAM_G;
		break;
	   	case "STAGE":
			return $this->_STAGE_MISC_PARAM_G;
		break;
		case "LOCALHOST":
			return $this->_LOCALHOST_MISC_PARAM_G;
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	   } 
   }
   
   public function getEnvironment(){
	//
	// IN ORDER OF IMPORTANCE FROM GREATEST TO LEAST
	switch($this->_CURR_FILEROOT){
		case __CRNRSTN_PROD0_FILEROOT_HTTP: 	// PRODUCTION 0
			return "PROD0_FILEROOT_HTTP";
		break;
		case __CRNRSTN_PROD1_FILEROOT_HTTP:		// PRODUCTION 1
			return "PROD1_FILEROOT_HTTP";
		break;
		case __CRNRSTN_PROD2_FILEROOT_HTTP:		// PRODUCTION 2
			return "PROD2_FILEROOT_HTTP";
		break;
		case __CRNRSTN_PROD3_FILEROOT_HTTP:		// PRODUCTION 3
			return "PROD3_FILEROOT_HTTP";
		break;
		case __CRNRSTN_PREPROD_FILEROOT_HTTP:	// PREPRODUCTION
			return "PREPROD";
		break;
		case __CRNRSTN_STAGE_FILEROOT_HTTP:		// STAGE
			return "STAGE";
		break;
		case __CRNRSTN_LOCALHOST_FILEROOT_HTTP:	// LOCALHOST
			return "LOCALHOST";
		break;
		default:
			//
			// CATCH THIS SHIT AT CONFIGURATION INITIALIZATION. TOO LATE IF CAUGHT HERE.
		break;
	}
   }
   
	public function makeNACL(){
		$NACL = md5(uniqid(rand(), true));	
		return $NACL;
	}   
}

$__ENV = new crnrstn_EnvironmentalAwareness();
?>