<?php
#
# [INSERT HEADER FROM MOST RECENT DEVELOPMENT ON MAC BOOK PRO ONCE YOU GET THE DATA FROM THAT HARD DRIVE.]
#

class ipaccess {
	public static $iprestricted_ARRAY = array();
	public static $ipallowed_ARRAY = array();
	
	public function __construct() {
		//
		// 
		
	}
	
	//
	// BUILD METHOD TO BE INCLUSIVE OF ONLY THE PROVIDED IPADDRESSES...e.g. ONLY ALLOW INSTANCES FROM XXX.XX.XXX
	// - PERMISSIONS SHOULD BE ABLE TO BE SERVER/ENVIRONMENT SPECIFIC
	// - PROVIDE ABILITY TO DYNAMICALLY INCLUDE A STATIC FILE OF GOOD/BAD IPS TO AUGMENT THE APPLICATION
	// - ACCESS VIOLATION NOTICES (MESSAGE OR REDIRECT) SHOULD BE CUSTOMIZABLE AND ENVIRONMENTALLY SPECIFIC
	
	//
	// BUILD METHOD TO BE EXCLUSIVE OF ANY PROVIDED IPADDRESSES...e.g. EXCLUDE OCCURANCES OF THE FOLLOWING XXX.XX.XXX
	
	
	public function __destruct() {

	}
}




?>