		<br><br><h1>5 Video Suite</h1>
<div id="lbox">
	<div id="lnav"><blockquote>
			<div class="lmenu" style="margin-top:3px;"><a href="../fivevideo/myprofile.php">Public Profile</a></div>
			<div class="lmenu" style="margin-top:3px;"><a href="../fivevideo/newvideo.php">Create a new 5 Video</a></div><br>
			<div class="lmenu" style="margin-top:3px;"><a href="../fivevideo/changelogo.php?command=new">Change Top Image</a></div>
			<div class="lmenu" style="margin-top:3px;"><a href="../fivevideo/changecontact.php?command=new">Change Bottom Image</a></div><br>
			<div class="lmenu" style="margin-top:3px;"><a href="../fivevideo/myprofile.php">Campaigns - Edit, Create, Remove</a></div>
			<div class="lmenu" style="margin-top:3px;"><a href="../fivevideo/step1.php">Campaign Panels - Edit, Create, Remove</a></div>
	</blockquote></div>
</div>







