<div class="hidden"><h1>soap_manager</h1>
		<p>Inspired by the NuSOAP WSDLCLIENT4.PHP sample file, the <a href="../../../documentation/classes/soap_manager/" target="_self">soap_manager</a> :: class of the C<span class="the_R">R</span>NRSTN Suite :: sits directly on top of the NuSOAP (0.9.5) PHP Toolkit for web services (SOAP server/client) support and development. When the <a href="../../../documentation/classes/soap_manager/" target="_self">soap_manager</a> class is instantiated, an instance of a NuSOAP web services client (within the constructor of the soap_manager) will be created as well. This can be customized for different SOAP client (or connection) types as needed.<br />
<br />
Three (3) parameters within the C<span class="the_R">R</span>NRSTN Suite :: configuration file are used for successful instantiation of the NuSOAP web services client...WSDL_URI, WSDL_CACHE_TTL and NUSOAP_USECURL. If the running application has no need of web services, these <a href="../../../documentation/classes/crnrstn/defineenvresource/" target="_self">defineEnvResource()</a> method calls can be removed from the configuration file. <br />
<br />
As specified in the <a href="../../../documentation/classes/crnrstn/" target="_self">crnrstn</a> :: class documentation and examples, the NuSOAP.PHP and SOAP MGMT class definitions are optional and can be removed if desired.<br />
<br />
If the running application is using web services and another SOAP client configuration is desired, the C<span class="the_R">R</span>NRSTN <a href="../../../documentation/classes/soap_manager/" target="_self">soap_manager</a> :: class can be modified to suite the purposes at hand.<br />
<br />
Details for the default configuration of the <a href="../../../documentation/classes/soap_manager/" target="_self">soap_manager</a> :: class NuSOAP web services client are as follows:<ul><li>INSPIRATION :: WSDLCLIENT4.PHP,v 1.6 2005/05/12 21:42:06 SNICHOL EEP</li><li>WSDL CLIENT SAMPLE, BASED ON SOAP BUILDERS ROUND 2 INTEROP</li><li>SERVICE :: WSDL || PAYLOAD :: RPC/ENCODED || TRANSPORT :: HTTP || AUTHENTICATION :: NONE</li></ul></p>
		<p>Version: 1.0.0</p><h2>Technical Specifications:</h2><p>It is recommended that you upgrade to the latest version of PHP to take advantage of the latests gains in security and processing efficiency.</p><p>Currently tested on an ubuntu 4.2 server running PHP Version 5.2.6 and Apache 2.2.11</p><h2>Methods:</h2><p><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/__construct/">__construct()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returncontent/">returnContent()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returnfault/">returnFault()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returnerror/">returnError()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returnresult/">returnResult()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returnclientrequest/">returnClientRequest()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returnclientresponse/">returnClientResponse()</a><a href="http://crnrstn.jony5.com/documentation/classes/soap_manager/returnclientgetdebug/">returnClientGetDebug()</a></p><p>Last upated: 2017-04-11 02:27:10</p></div>