<?php
/* 
// J5
// Code is Poetry */
# # C # R # N # R # S # T # N # : : # # # #
#
# CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
#
# DATE GENERATED: 2022-08-28 16:20:02.867462
# FILE NAME: crnrstn_R_sm.php
# FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/base64/system/crnrstn_R_sm.php
# FILE SERIAL: 1100011010110000001101101111010010001100111011001001011111100100
#
# SERVER IP: 172.16.225.139
# CLIENT IP: 172.16.225.1 (172.16.225.1)
# PHPSESSION: qkuh0gsqn5rnn4ffr3c7t177a1
# GENERATING SERVER INFORMATION: Ubuntu 18.04.1 LTS, Apache v2.4.29, MySQLi v5.7.39, php v7.0.33, OpenSSL v1.1.1, NuSOAP0.9.5
#
# # # # #
# PNG FILE (ORIGINAL) :: crnrstn_R_sm.png
# PNG IMAGE DIMENSIONS: 44 pixels in width X 59 pixels in height.
# PNG FILE EXTENSION: png
# PNG FILE MIME TYPE: image/png
# PNG FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/png/system/crnrstn_R_sm.png
# PNG FILE SIZE: 5.07617 KiB
# PNG FILE LAST MODIFIED: 2022-07-27 12:46:36
# PNG FILE MD5: eed81b0cda988d2af59bc032d3ca8fec
# PNG FILE SHA1: 0db01e97bf66b441ffb9411798b5d56671414de6
# PNG FILE ENCODED LENGTH (BASE64): 6,954 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
# JPEG FILE (ORIGINAL) :: 
# JPEG IMAGE DIMENSIONS:  pixels in width X  pixels in height.
# JPEG FILE EXTENSION: 
# JPEG FILE MIME TYPE: 
# JPEG FILE PATH: 
# JPEG FILE SIZE: 0 bytes
# JPEG FILE LAST MODIFIED: 1969-12-31 19:00:00
# JPEG FILE MD5: 
# JPEG FILE SHA1: 
# JPEG FILE ENCODED LENGTH (BASE64): 0 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
/*
      ___           ___           ___           ___           ___                         ___              
     /\__\         /\  \         /\  \         /\  \         /\__\                       /\  \             
    /:/  /        /::\  \        \:\  \       /::\  \       /:/ _/_         ___          \:\  \          ___         ___
   /:/  /        /:/\:\__\        \:\  \     /:/\:\__\     /:/ /\  \       /\__\          \:\  \        /\__\       /\__\      
  /:/  /  ___   /:/ /:/  /    _____\:\  \   /:/ /:/  /    /:/ /::\  \     /:/  /      _____\:\  \       \/__/       \/__/          
 /:/__/  /\__\ /:/_/:/__/___ /::::::::\__\ /:/_/:/__/___ /:/_/:/\:\__\   /:/__/      /::::::::\__\         
 \:\  \ /:/  / \:\/:::::/  / \:\~~\~~\/__/ \:\/:::::/  / \:\/:/ /:/  /  /::\  \      \:\~~\~~\/__/       ___         ___
  \:\  /:/  /   \::/~~/~~~~   \:\  \        \::/~~/~~~~   \::/ /:/  /  /:/\:\  \      \:\  \            /\__\       /\__\         
   \:\/:/  /     \:\~~\        \:\  \        \:\~~\        \/_/:/  /   \/__\:\  \      \:\  \           \/__/       \/__/     
    \::/  /       \:\__\        \:\__\        \:\__\         /:/  /         \:\__\      \:\__\          
     \/__/         \/__/         \/__/         \/__/         \/__/           \/__/       \/__/      
	 
        
        
        
<!-- 
ASCII ARTWORK GENERATED BY CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
ARTWORK TITLE :: Isometric2
TIMESTAMP :: 2022-08-28 16:20:02.866677

CREATIVE SOURCE :: http://patorjk.com/software/taag/#p=display&f=Isometric2&t=CRNRSTN%20%3A%3A
DATE :: Sunday, Jul 31, 2022 @ 0949 hrs ::  
-->        
*/


$system_file_serial = '1100011010110000001101101111010010001100111011001001011111100100';

switch(self::$image_output_mode){
    case CRNRSTN_BASE64_JPEG:
            
        //
        // BASE64 ENCODE OF JPG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_JPEG'] = '2022-08-28 16:20:02.874050';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64'] = '';

    break;
    default:
    
        //
        // BASE64 ENCODE OF PNG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_PNG'] = '2022-08-28 16:20:02.873959';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAA7CAYAAAAAV2giAAAErWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjQ0IgogICBleGlmOlBpeGVsWURpbWVuc2lvbj0iNTkiCiAgIGV4aWY6Q29sb3JTcGFjZT0iNjU1MzUiCiAgIHRpZmY6SW1hZ2VXaWR0aD0iNDQiCiAgIHRpZmY6SW1hZ2VMZW5ndGg9IjU5IgogICB0aWZmOlJlc29sdXRpb25Vbml0PSIyIgogICB0aWZmOlhSZXNvbHV0aW9uPSI5Ni8xIgogICB0aWZmOllSZXNvbHV0aW9uPSI5Ni8xIgogICBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIgogICBwaG90b3Nob3A6SUNDUHJvZmlsZT0iRGlzcGxheSIKICAgeG1wOk1vZGlmeURhdGU9IjIwMjItMDctMjdUMTI6NDY6MzYtMDQ6MDAiCiAgIHhtcDpNZXRhZGF0YURhdGU9IjIwMjItMDctMjdUMTI6NDY6MzYtMDQ6MDAiPgogICA8eG1wTU06SGlzdG9yeT4KICAgIDxyZGY6U2VxPgogICAgIDxyZGY6bGkKICAgICAgc3RFdnQ6YWN0aW9uPSJwcm9kdWNlZCIKICAgICAgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWZmaW5pdHkgRGVzaWduZXIgMS4xMC41IgogICAgICBzdEV2dDp3aGVuPSIyMDIyLTA3LTI3VDEyOjQ2OjM2LTA0OjAwIi8+CiAgICA8L3JkZjpTZXE+CiAgIDwveG1wTU06SGlzdG9yeT4KICA8L3JkZjpEZXNjcmlwdGlvbj4KIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+Cjw/eHBhY2tldCBlbmQ9InIiPz5+otFHAAAMUmlDQ1BEaXNwbGF5AABIiaVXd1hTyRafW1JJaIEISAm9CSJIlxJCiyAgHWyEJJBAiDEhiNiVRQXXLipY0VURRdcCiB2xuyj2vlhQWVkXCzZU3oQEdPV77593vm/u/eXMmd8pOffeGQB0dkr4eQpUF4A8ab48PiKElZqWziI9BQgwB9rAFeA8vkLGjouLBlD67/+WdzegNZSrLiqun+f/p+gJhAo+AEgcxPkCBT8P4mYA8GK+TJ4PADES6q0n58tUWAKxgRwGCPEsFc5W4xUqnKnG2/tsEuM5EB8GgEzj8eTZAGifhXpWAT8b8mg/h9hNKhBLAdAxgjiQL+IJIE6FeEhe3kQVLobYIfM7nux/cWYOcPJ42QNYnUufkEPFCpmEN6U/TzIIBWKgADIgATwwoP7/JU+i7PdpBwdNJI+MV9UA1vFW7sQoFaZB3CnNjImFWB/iD2JBnz3EKFWkjExS26OmfAUH1hAwIXYT8EKjIDaFOFwqiYnW6DOzxOFciGHHoIXifG6iZu18oSIsQcO5Vj4xPrYfZ8k5bM3aWp68z6/KvlmZm8TW8N8SCbn9/G+LRIkp6pgxaoE4OQZibYiZityEKLUNZlMk4sT028iV8ar4bSD2E0ojQtT82PgseXi8xl6u6UoYDzZfJObGaHBFvigxUsOzk8/rix/2A9YglLKT+nmEitTo/lwEwtAwde7YZaE0SZMv1ibLD4nXrH0tk8Rp7HGqUBKh0ltBbKooSNCsxQPzYYOq+fEYWX5cojpOPDOHNzJOHQ9eCKIBB/YMCyjhyAQTQQ4Qt3TWd8Jf6plw2EdykA2EwEWj6V+R0jcjhdcEUAT+hkgIO69/XUjfrBAUQP2XAa366gKy+mYL+lbkgqcQ54Eo2LNCGIdqlXTAWzJ4AjXin7zzYawSOFRzP+vYUBOt0Sj7eVk6/ZbEMGIoMZIYTnTETfBA3B+PhtdgONxxH9y3P9pv9oSnhFbCI8J1Qhvh9gTxHPkP+bDAKNAGPYRrcs78PmfcDrJ64iF4AOSH3DgTNwEu+HDoiY0HQd+eUMvRRK7K/kfuf+XwXdU1dhQ3CkoZRAmmOPy4UttJ23OARVXT7yukjjVzoK6cgZkf/XO+q7QA3qN+tMTmY/uwM9gJ7Bx2GKsHLOwY1oBdxI6o8EAXPenron5v8X3x5EIe8U/+eBqfqkoq3GrcOtw+q+fyhYX5qgeMM1E2RS7OFuWz2DKZRMjiSvmuQ1jubu7uAKi+K+rX1Btm3/cCYZ7/ppu7HoCA/b29vYe+6aIaAdhXBgD15jed/XT4OjgBwNlKvlJeoNbhqgsBUIEOfKKM4XfLGjjAfNyBF/AHwSAMjASxIBGkgfGwyiLYz3IwGUwDs0EJKANLwEpQATaAzWA72AX2gnpwGJwAp8EFcBlcB3dh97SDF6ALvAM9CIKQEDrCQIwRC8QWcUbcER8kEAlDopF4JA3JQLIRKaJEpiFzkTJkGVKBbEKqkd+Rg8gJ5BzSitxGHiIdyGvkE4qhNNQANUPt0KGoD8pGo9BEdByajU5Ci9BidBG6Gq1Cd6J16An0AnodbUNfoN0YwLQwJmaJuWA+GAeLxdKxLEyOzcBKsXKsCqvFGuH/fBVrwzqxjzgRZ+As3AV2cCSehPPxSfgMfCFegW/H6/Bm/Cr+EO/CvxLoBFOCM8GPwCWkErIJkwklhHLCVsIBwin4NLUT3hGJRCbRnugNn8Y0Yg5xKnEhcR1xN/E4sZX4mNhNIpGMSc6kAFIsiUfKJ5WQ1pB2ko6RrpDaSR/IWmQLsjs5nJxOlpLnkMvJO8hHyVfIz8g9FF2KLcWPEksRUKZQFlO2UBoplyjtlB6qHtWeGkBNpOZQZ1NXU2upp6j3qG+0tLSstHy1RmuJtWZprdbao3VW66HWR5o+zYnGoY2lKWmLaNtox2m3aW/odLodPZieTs+nL6JX00/SH9A/aDO0XbW52gLtmdqV2nXaV7Rf6lB0bHXYOuN1inTKdfbpXNLp1KXo2ulydHm6M3QrdQ/q3tTt1mPoDdOL1cvTW6i3Q++c3nN9kr6dfpi+QL9Yf7P+Sf3HDIxhzeAw+Iy5jC2MU4x2A6KBvQHXIMegzGCXQYtBl6G+4XDDZMNCw0rDI4ZtTIxpx+QyJczFzL3MG8xPg8wGsQcJBy0YVDvoyqD3RoONgo2ERqVGu42uG30yZhmHGecaLzWuN75vgps4mYw2mWyy3uSUSedgg8H+g/mDSwfvHXzHFDV1Mo03nWq62fSiabeZuVmEmcxsjdlJs05zpnmweY75CvOj5h0WDItAC7HFCotjFn+xDFlsloS1mtXM6rI0tYy0VFpusmyx7LGyt0qymmO12+q+NdXaxzrLeoV1k3WXjYXNKJtpNjU2d2wptj62IttVtmds39vZ26XYzbOrt3tub2TPtS+yr7G/50B3CHKY5FDlcM2R6OjjmOu4zvGyE+rk6SRyqnS65Iw6ezmLndc5tw4hDPEdIh1SNeSmC82F7VLgUuPy0JXpGu06x7Xe9eVQm6HpQ5cOPTP0q5unm8Rti9vdYfrDRg6bM6xx2Gt3J3e+e6X7NQ+6R7jHTI8Gj1fDnYcLh68ffsuT4TnKc55nk+cXL28vuVetV4e3jXeG91rvmz4GPnE+C33O+hJ8Q3xn+h72/ejn5Zfvt9fvH38X/1z/Hf7PR9iPEI7YMuJxgFUAL2BTQFsgKzAjcGNgW5BlEC+oKuhRsHWwIHhr8DO2IzuHvZP9MsQtRB5yIOQ9x48znXM8FAuNCC0NbQnTD0sKqwh7EG4Vnh1eE94V4RkxNeJ4JCEyKnJp5E2uGZfPreZ2jfQeOX1kcxQtKiGqIupRtFO0PLpxFDpq5Kjlo+7F2MZIY+pjQSw3dnns/Tj7uElxh0YTR8eNrhz9NH5Y/LT4MwmMhAkJOxLeJYYkLk68m+SQpExqStZJHptcnfw+JTRlWUpb6tDU6akX0kzSxGkN6aT05PSt6d1jwsasHNM+1nNsydgb4+zHFY47N95kvGT8kQk6E3gT9mUQMlIydmR85sXyqnjdmdzMtZldfA5/Ff+FIFiwQtAhDBAuEz7LCshalvU8OyB7eXaHKEhULuoUc8QV4lc5kTkbct7nxuZuy+2VpEh255HzMvIOSvWludLmieYTCye2ypxlJbK2SX6TVk7qkkfJtyoQxThFQ74B3MBfVDoof1E+LAgsqCz4MDl58r5CvUJp4cUpTlMWTHlWFF7021R8Kn9q0zTLabOnPZzOnr5pBjIjc0bTTOuZxTPbZ0XM2j6bOjt39h9z3OYsm/N2bsrcxmKz4lnFj3+J+KWmRLtEXnJznv+8DfPx+eL5LQs8FqxZ8LVUUHq+zK2svOzzQv7C878O+3X1r72Lsha1LPZavH4JcYl0yY2lQUu3L9NbVrTs8fJRy+tWsFaUrni7csLKc+XDyzesoq5SrmpbHb26YY3NmiVrPleIKq5XhlTuXmu6dsHa9+sE666sD15fu8FsQ9mGTxvFG29tithUV2VXVb6ZuLlg89MtyVvO/ObzW/VWk61lW79sk25r2x6/vbnau7p6h+mOxTVojbKmY+fYnZd3he5qqHWp3bSbubtsD9ij3PPX7xm/39gbtbdpn8++2v22+9ceYBworUPqptR11Yvq2xrSGloPjjzY1OjfeOCQ66Fthy0PVx4xPLL4KPVo8dHeY0XHuo/LjneeyD7xuGlC092TqSevNY9ubjkVders6fDTJ8+wzxw7G3D28Dm/cwfP+5yvv+B1oe6i58UDf3j+caDFq6Xukvelhsu+lxtbR7QevRJ05cTV0Kunr3GvXbgec731RtKNWzfH3my7Jbj1/Lbk9qs7BXd67s66R7hXel/3fvkD0wdVfzr+ubvNq+3Iw9CHFx8lPLr7mP/4xRPFk8/txU/pT8ufWTyrfu7+/HBHeMflv8b81f5C9qKns+Rvvb/XvnR4uf+f4H8udqV2tb+Sv+p9vfCN8Zttb4e/beqO637wLu9dz/vSD8Yftn/0+XjmU8qnZz2TP5M+r/7i+KXxa9TXe715vb0ynpzXtxXA4ECzsgB4vQ0AehoAjMtw/zBGfe7rE0R9Vu1D4L9h9dmwT7wAqIU31XadcxyAPXDYBUNueFdt1RODAerhMTA0osjycFdz0eCJh/Cht/eNGQAkuJ/5Iu/t7VnX2/tlCwz2NgDHJ6nPmyohwrPBRjcVumKxD/wo/wHG7YR+zo7I9AAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAulJREFUaIHtmT1oFEEYhp8TL6MJnqj414jiSRAhQoprTCNio4VWghAExaC12oiVYiNWJqAEwSoqprEU7CxEREELLSRq4d/FQ1DUqBP1YjFZ2Mzu7e23R2Ym4AsLxzvv9+17HzOz81NiFhpKmKdMfszk0DQV/BHkzEQp+qHzvbwoGsBL65kAnkr/jCvDrfAeuAKMKviUJ8C34QhfgOMKbrUThmI4wlXgmMrwssihmTwYAi5kCUKrcIRBBdfTGkI1/AaoKvhtN4TWJSJsAA6nNXRa4THgksWVgY1AFdgC7AeWFch9X8GATS4ukCiOSQWPU/gH0Q8N6zEDaZBYgXKgpqFHwVScnPcuoaCu4BBwUhhaBnbYpMs+PAw8EcZUbcKZYQV/gVPCsJU24XqWeCTUr7IJp4YVfAMmBSFdNuFjHp4QaN/ZhA/DSwTatzbhw3Bi5GfAb4W1GUQrBCHeK7xVoP1MAIbPCbTXFEzbpDPD2izOd+aUN4HLaQ2dLn7aQpt3HAEuCsLuKHid1jAvhjV0A5uAfuAM0CsInwLOtmrsdD3cAOoWtw5YWyAXGLN7FdxrJQhpi9TWLISxRfqJ2bkMtDMLDgZdBp4Bo8CYMgcpueCzwhWgD9itU9a9rRBKH24CI8BpZbpIS4RiOMIL4KDK2Ep1anjahCawlOLj4xWwTaXn7bgPDyuo2A/GcC+wD7ghzLkZONFWpWGmwJPrc6vhgIavgrzfNSxPy+VkllAwDpwXhPQAtbQGl9PaCMnPeBb8Gp6drm4LQrxXGOC5QNufRoZseE0a6drwR4G2S5vBNweuDf8S6r2fraV+vTKQOAgPvcLdNhF6hb0bXlgVVmbdK7kMr9iEjx2HpMreZwmQ9eMgDC+4Cv8QaBNHsz4MNwTaICr8QaBdbRM+DCcOqTNQ05ZpH4bHBdoycFPH+rJzwwoeIrvC3QXUNeyBuWcHQ5jVUV+Ma3f7LtnyxHEU2J5TW8Fc5twt+K7/EOEfR3jDwAxlYgEAAAAASUVORK5CYII=';

    break;
    
}

//
// BASE64 LAST MODIFIED
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['lastmodified_base64_PNG'] = '2022-08-28 16:20:02.876610';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['lastmodified_base64_JPEG'] = '2022-08-28 16:20:02.879020';

//
// BASE64 HASH/CHECKSUM
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_crc'] = '2595858551';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_md5'] = '2fdbe6955b5ab212c439274e36ebe42c';

self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_crc'] = '0';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_md5'] = 'd41d8cd98f00b204e9800998ecf8427e';

//
// HASHES FOR BASE64 SOURCE PNG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['md5'] = 'eed81b0cda988d2af59bc032d3ca8fec';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['sha1'] = '0db01e97bf66b441ffb9411798b5d56671414de6';

//
// HASHES FOR BASE64 SOURCE JPEG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['md5'] = '';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['sha1'] = '';


# # # # # 
# # # # # END OF CRNRSTN :: GENERATED SYSTEM FILE
# # # # # [2022-08-28 16:20:02.879188] [rtime 1.8012] 
