<?php
/* 
// J5
// Code is Poetry */
# # C # R # N # R # S # T # N # : : # # # #
#
# CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
#
# DATE GENERATED: 2022-08-28 16:20:01.578827
# FILE NAME: powered_by_apache_1_3.php
# FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/base64/system/powered_by_apache_1_3.php
# FILE SERIAL: 1100000101110110101100001110110010110101011000101011010000100100
#
# SERVER IP: 172.16.225.139
# CLIENT IP: 172.16.225.1 (172.16.225.1)
# PHPSESSION: qkuh0gsqn5rnn4ffr3c7t177a1
# GENERATING SERVER INFORMATION: Ubuntu 18.04.1 LTS, Apache v2.4.29, MySQLi v5.7.39, php v7.0.33, OpenSSL v1.1.1, NuSOAP0.9.5
#
# # # # #
# PNG FILE (ORIGINAL) :: powered_by_apache_1_3.png
# PNG IMAGE DIMENSIONS: 259 pixels in width X 32 pixels in height.
# PNG FILE EXTENSION: png
# PNG FILE MIME TYPE: image/png
# PNG FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/png/system/powered_by_apache_1_3.png
# PNG FILE SIZE: 4.73926 KiB
# PNG FILE LAST MODIFIED: 2021-03-07 04:02:32
# PNG FILE MD5: 0ddbd21a7448d4e718d5d912716ad2ef
# PNG FILE SHA1: 1f491f1fe6aa97eee2adec16cb6e9f26fae28aac
# PNG FILE ENCODED LENGTH (BASE64): 6,494 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
# JPEG FILE (ORIGINAL) :: 
# JPEG IMAGE DIMENSIONS:  pixels in width X  pixels in height.
# JPEG FILE EXTENSION: 
# JPEG FILE MIME TYPE: 
# JPEG FILE PATH: 
# JPEG FILE SIZE: 0 bytes
# JPEG FILE LAST MODIFIED: 1969-12-31 19:00:00
# JPEG FILE MD5: 
# JPEG FILE SHA1: 
# JPEG FILE ENCODED LENGTH (BASE64): 0 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
/*
        CCCCCCCCCCCCCRRRRRRRRRRRRRRRRR   NNNNNNNN        NNNNNNNNRRRRRRRRRRRRRRRRR      SSSSSSSSSSSSSSS TTTTTTTTTTTTTTTTTTTTTTTNNNNNNNN        NNNNNNNN
     CCC::::::::::::CR::::::::::::::::R  N:::::::N       N::::::NR::::::::::::::::R   SS:::::::::::::::ST:::::::::::::::::::::TN:::::::N       N::::::N
   CC:::::::::::::::CR::::::RRRRRR:::::R N::::::::N      N::::::NR::::::RRRRRR:::::R S:::::SSSSSS::::::ST:::::::::::::::::::::TN::::::::N      N::::::N
  C:::::CCCCCCCC::::CRR:::::R     R:::::RN:::::::::N     N::::::NRR:::::R     R:::::RS:::::S     SSSSSSST:::::TT:::::::TT:::::TN:::::::::N     N::::::N
 C:::::C       CCCCCC  R::::R     R:::::RN::::::::::N    N::::::N  R::::R     R:::::RS:::::S            TTTTTT  T:::::T  TTTTTTN::::::::::N    N::::::N
C:::::C                R::::R     R:::::RN:::::::::::N   N::::::N  R::::R     R:::::RS:::::S                    T:::::T        N:::::::::::N   N::::::N      ::::::  ::::::
C:::::C                R::::RRRRRR:::::R N:::::::N::::N  N::::::N  R::::RRRRRR:::::R  S::::SSSS                 T:::::T        N:::::::N::::N  N::::::N      ::::::  ::::::
C:::::C                R:::::::::::::RR  N::::::N N::::N N::::::N  R:::::::::::::RR    SS::::::SSSSS            T:::::T        N::::::N N::::N N::::::N      ::::::  ::::::
C:::::C                R::::RRRRRR:::::R N::::::N  N::::N:::::::N  R::::RRRRRR:::::R     SSS::::::::SS          T:::::T        N::::::N  N::::N:::::::N
C:::::C                R::::R     R:::::RN::::::N   N:::::::::::N  R::::R     R:::::R       SSSSSS::::S         T:::::T        N::::::N   N:::::::::::N
C:::::C                R::::R     R:::::RN::::::N    N::::::::::N  R::::R     R:::::R            S:::::S        T:::::T        N::::::N    N::::::::::N
 C:::::C       CCCCCC  R::::R     R:::::RN::::::N     N:::::::::N  R::::R     R:::::R            S:::::S        T:::::T        N::::::N     N:::::::::N      ::::::  ::::::
  C:::::CCCCCCCC::::CRR:::::R     R:::::RN::::::N      N::::::::NRR:::::R     R:::::RSSSSSSS     S:::::S      TT:::::::TT      N::::::N      N::::::::N      ::::::  ::::::
   CC:::::::::::::::CR::::::R     R:::::RN::::::N       N:::::::NR::::::R     R:::::RS::::::SSSSSS:::::S      T:::::::::T      N::::::N       N:::::::N      ::::::  ::::::
     CCC::::::::::::CR::::::R     R:::::RN::::::N        N::::::NR::::::R     R:::::RS:::::::::::::::SS       T:::::::::T      N::::::N        N::::::N
        CCCCCCCCCCCCCRRRRRRRR     RRRRRRRNNNNNNNN         NNNNNNNRRRRRRRR     RRRRRRR SSSSSSSSSSSSSSS         TTTTTTTTTTT      NNNNNNNN         NNNNNNN
                                                                                                                                                       
       
                
        
<!-- 
ASCII ARTWORK GENERATED BY CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
ARTWORK TITLE :: Doh
TIMESTAMP :: 2022-08-28 16:20:01.578243

CREATIVE SOURCE :: http://patorjk.com/software/taag/#p=display&f=Doh&t=CRNRSTN%20%3A%3A
DATE :: Sunday, Jul 31, 2022 @ 0949 hrs ::  
-->        
*/


$system_file_serial = '1100000101110110101100001110110010110101011000101011010000100100';

switch(self::$image_output_mode){
    case CRNRSTN_BASE64_JPEG:
            
        //
        // BASE64 ENCODE OF JPG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_JPEG'] = '2022-08-28 16:20:01.586233';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64'] = '';

    break;
    default:
    
        //
        // BASE64 ENCODE OF PNG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_PNG'] = '2022-08-28 16:20:01.586193';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQMAAAAgCAYAAAAWnh3nAAAFRGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpDb2xvclNwYWNlPSIxIgogICBleGlmOlBpeGVsWERpbWVuc2lvbj0iMjU5IgogICBleGlmOlBpeGVsWURpbWVuc2lvbj0iMzIiCiAgIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiCiAgIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIKICAgdGlmZjpJbWFnZUxlbmd0aD0iMzIiCiAgIHRpZmY6SW1hZ2VXaWR0aD0iMjU5IgogICB0aWZmOlJlc29sdXRpb25Vbml0PSIyIgogICB0aWZmOlhSZXNvbHV0aW9uPSI3Mi4wIgogICB0aWZmOllSZXNvbHV0aW9uPSI3Mi4wIgogICB4bXA6TWV0YWRhdGFEYXRlPSIyMDIxLTAzLTA3VDA0OjAyOjMyLTA1OjAwIgogICB4bXA6TW9kaWZ5RGF0ZT0iMjAyMS0wMy0wN1QwNDowMjozMi0wNTowMCI+CiAgIDx4bXBNTTpIaXN0b3J5PgogICAgPHJkZjpTZXE+CiAgICAgPHJkZjpsaQogICAgICB4bXBNTTphY3Rpb249InByb2R1Y2VkIgogICAgICB4bXBNTTpzb2Z0d2FyZUFnZW50PSJBZmZpbml0eSBQaG90byAoRmViICAxIDIwMjEpIgogICAgICB4bXBNTTp3aGVuPSIyMDIxLTAzLTAxVDA0OjM1OjE3LTA1OjAwIi8+CiAgICAgPHJkZjpsaQogICAgICBzdEV2dDphY3Rpb249InByb2R1Y2VkIgogICAgICBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZmZpbml0eSBQaG90byAxLjkuMSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMS0wMy0wN1QwNDowMjozMi0wNTowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+NZNqVwAAAYFpQ0NQc1JHQiBJRUM2MTk2Ni0yLjEAACiRdZHLS0JBFIc/tVDKMKhFQQuJamVRBlGbICUsiBAz6LXR6ytQu9yrhLQN2goFUZtei/oLahu0DoKiCKJd0LqoTcnt3BSUyDOcOd/8Zs5h5gxYw2klozcMQiab00IBn3thccltf8GGHQcjdEYUXZ0IBmeoa5/3WMx422/Wqn/uX2uOxXUFLA7hcUXVcsJTwjPrOdXkHeF2JRWJCZ8JezS5oPCdqUfL/GpysszfJmvhkB+srcLuZA1Ha1hJaRlheTk9mXReqdzHfIkznp2fk9gt3oVOiAA+3EwziV96MsSYzCP042VAVtTJH/zNn2VNchWZVQporJIkRQ6PqHmpHpeYED0uI03B7P/fvuqJYW+5utMHjc+G8d4L9m0oFQ3j68gwSsdge4LLbDV/7RBGP0QvVrWeA3BtwvlVVYvuwsUWdDyqES3yK9nErYkEvJ1CyyK03UDTcrlnlX1OHiC8IV91DXv70CfnXSs/Sspn2RTrUrEAAAAJcEhZcwAACxMAAAsTAQCanBgAAAvKSURBVHic7ZxNiCNbFcd/8QNnniJp3dS8hZIB9c2ISreC9Dw3pncZBJlRkAquahAk7UIzG0mW1QthZqH27CrgprKyZze9kQpuTKuL9K4HBJOVdhQk7QfMoOhxUXUrtyq3kspHz/S8V3+4VOp+nlup87/nnHsTKFCgQIECBQoUKFCgQIECBQoUmEXpdQtggu/7ks6r1+tXUtY8CIK+jMcjwDyPReUF3hj8BPhcjnrfBv6zQv8l4CvA14B3gU8B5Sh9GPh7lP4C/B7oA79aaawg6M8oYVY9lZYeJAcqliXATLJt+1LGu2xEcqu0dHmBNwYnGN5bQ/rICn3vAr/J2b+e/gBU8wzwAf1mPB5RsayFSj4ejxiPRzx96icIRAaW+L4v4hJfc040E77vY9s2AN1uF9d1BUJCcl1XbNsW13VjmX3fF9u2xbbtOM+2bWk2m3G7dHkQ9KXZbCb6AWg2m2Lbtvi+L6qdbrX4vi/NZlNMlozqU42bF2pOqk/TfFTesn0XuHQ8Bn4QpZ9vsN93gAC4k8r/HfAN4LOEFsOPgP+m6nwG+AXwwaVHVUpWsSzjSw5TJdCVR6qWCIa0jUjVEnERccllTaQsA+U2CKAr30xSSqvuXddN1FUKDUjFsmQwGEhqVU7MW8mh14nyZqwXnUQjJc1KM0jLYOgzYRml5CpwNfF1NmcZvA18yZA+rtX5JPAt4IVhvF+uOgkgJIWKZUnFskStxgqNRkNc19WVDcER27ZFcETwomsGOajkIjKYtUR0RbNtW/R7XTkqlpUoVwquK4uuaM1mM1GmiEIpeDTPGaXTk7bax/XUGNpKbZSPHGRgklm/1+d/WW5agY1gk2QwD+8A/8oY52/AdwnjCetDWQmKFIKgLyIijUZDGo1GrACCJx4igicTRJrNpkYKiigMpOAytR6q4apsUkK1YqetBEiuxMpq0dvpZJGnXpRI19fdBb2N3r8unyLRVWIGOmmlCVDlb+DrLXB5eFVk8DbwM8ADfg38IzXWvwldjG9uZDTddVCDqBdYWQcOIg4iXnSdkoMTX0Ny8MwWg0YSaUtgMBjESVcMExlogc3M1TZtCZChpCkSiaGTgelZ6ePq5JE1TrpcJ5S09aHPc+EXV+B1YlNk8FXC3Yd0ejej/ueBfxrGfBGVbQ7pl1JXNLXYK1LQ0yQiCEUUU6vBm7Ec9P4FK7YaVMxBJ4v0Z0Uaupy+74uu+ErBTP645kpkkkGWss5zL7S08JnqSQ8kpscscKWRiwzS8S9DnO57GX38D/gh8AXgo8BbwBeBH88Z98sbmZkeyc4K4BERgroqYtDJQbkROjF4GkGkfWzdarBtW6RqSXCvPONKqGCbIgOl/ClFnnngJrdEWRxZZADmIKHq12ANLE0G6VhNOhCa71sr8BqxkAzmBcK1fkrA94G/zulvUfoz8GBjMwuCvjQajfglt21bVCBREYAp6fHCbY0U0tZDkhSc+HMYe3ASboQecwjulWOrwff9OCC5rMIEQT9z92QetB2MS4X+3C97rAIbwbvAnzLSMpaBwscI3QOP8DzDHzG7AxLl/xb4KfAd4PrGZqUHztT+dqPREAC1wjuawpsETFsMtm3HV50cJjMxB2VB6LsVU2JAtx70oKRK1amb8aauqLo7swphFXhP4y3g00AF+ATwoVU7ynX0Na1E4/EIy6qwt3enJHjSwcGhwwOcuM4gup7OGWI7ZTXvRO0ahNS3G109OgDo43gzVs+zxF3druJ3e9pgY7gP9Kw4q+s8vvLHf4etoex17rBbrdLtdq+0rAXeR9BP7Kmr2joUnCgWEF51d8DRrAIW+Ddpt0LfoUgHI5OWQzoo6Umj0UgEJY1nH7QtzVVdjAIF3gtYaaUJgr7s7d0pBUFfqgf3IF6A79LBw4lW8gscynToRBaDvtoDdHIMr1sPuuXwhKkF8QjicVTfHg+4wKMcyaLwsPmcR48vorvImtgeh9dTK1GXKvRaT9nbu/PKV+SIONkBWq0RNw9uriSDF/WzCVRbI17evuB2fWcpWYatoVw/3Urk3TjeWuuZnrueAFjt9krtx67LpLIzdy5n/kBuHD1J5E3qFW7eby83/yNXKm5SzlHbndvPxKtu7HubbFVzybz2Sx4EfTk56dFqH2q5d1O1drnA4Qhw6HARkcNDpuQwYL5LobCNcEpphiSI+lCfdwm9AjWGwn2mxBGS1gl1+wV+t8qUrog+Pwvn4nbo7fZfGSlsawqs5uPWLlZSoGFrKL2DysZkA7jjn+YmhEntkZSPy8ay5/58ZTThzB/IrXptmSZzMXZdbrQfGGU48wdy69FOIu+i4rD1tLM2GQCU5rzwE68q5XEvq3gpjG7NJx6FlYMNCspCwG1zgBuRgu6/3wVOKEMcUShHhODFq7bDI+AoUvB55KDy9LJTpiSh7949SbXdBY6Ak2i8kKAcnnSJJAklPG3sc/hEyf4M2hZV7iFYon7/dVDdp9UeQfXZRq0H3SKAKcHVjsuc1yay7oqqUG2NctdNk8m1M7NypyF4wnF2+a36gDN/IMsQgokIxq6bq+21/gVce0756fT9XMqyOLXCMN1rwuhWvnleCQRBX6QanQeInH4SZwUcSZ5EdGL/X0/6roKXij8A8/bwF8Yj1NVJxSW2tTEmUfIQcV3XuOUpeCLb4QlM9RsL0+8slnl2DsmzGQDntUlCRgdZaoxhazhzAGxZ1yHddtgazm1/5g9mvlPV5rw2mSk78we55TGdWl1mLpPao5n2WeOf+QOZCWKlo945MDxyl+5n4lWTu2Ib+AXwIlya2SsDSw6O92nRDpdjmPXJE+5E6DCEfv7U31dxByB2LyDsUncDThv79J8cckoJ27bpdrsryb2NsLOgjscDDtxKODeAGsQrYA3AojfJby0EQV+6e7sJN6dDKW57XptI7bgcx0x2ADs4ydV/lpuwjmVQnRPDCM34QSJv1Kom6g9bQ6kcJE3gvC6DSflLjHO/x2f+QLZGAyaV8Ekvihmk3YRNYlk34cKa/7cEeWMDmfKs2nAZ+L4v9qhO/czGf96dIYUSYwSHqXtxl6Snr3CSkT9FRyOM+0x5SA9evrDrAFzv+nSi+EOeeIUiGXEJ5/KwG5KAslz1z4RzXEQKZ/5AHte3M4lAwUQIzRy++6uMGZiUPE0E8+qOXTL9d4V1yWAZXDUyWIS8sYFMeVZtuAriYCPtKTEoRAQREsOULMLzAtdJEoUOpeJJktAtivS9Ch6mdzuUpeFFZYpIenad610/JhHAaHmoP2EB8G9H5bVsKyFNBDohZCFddxEhbJIM5u0mmJR7FSwihHXJ4Nz15Nog3HN6ubM7d0chiwzG9z1j3y9ujY35puAhLE8Gi2IG6xABvMb/QFR+b/XkThh47B1CdTxdysHgVsyShbqfHjJSZKHvCuj3Oqb2gr4NOd1pMNc5cMe0aoYvWFkGx1BqTy0J3/cZjUa02+2EqXw/UlLTbghankKaMFTZ0Ryz3UQG88z8VbApIlC4qF2wdfzQKN+6ZDC554geQAR47h8bCSGLDOYpsQmb2k0otS9XX6/ciTZFEuPxiNFoRKt3GEbujwzKd2qFZwQMpBFCnXu4Ed/PInwxQjLRtxdPUmXqeHdIKvuNUw5vRPsVKmYwE+g2uwomImhFq66O2/Wdkim4de2szEHUfhEhXDYZZLkG6bnMw9ZogJX6erMIwUQG6+wmQDaZXDUy0GMGk61cf2sY45WcM3hVUCQRb2VGUG7HzUMLZ3+fVu+Qm2cwvE10GCokgJvWM4ZjOHDDLcEDtxJtg0bbh4lrGs+iPmA4Tpb3AieUoXbIwfE+rdoh3eePAfM/HSvfXyGv75+G7mIoHBvOIlwmGQjejGKucnYAzIFHU3/nrierHjQy4eLe3cxzA1eNDNZBHqvijSGD9wKCoC+VXtKKGVXHK59RyNPfmT+Q9LmAVU4RpmHqd12CUZF+HSaf3lRvFSwKVkKoyPr9y5e1lZ5duh+Yv1qb6q+DdeMJBQoUKFCgQIECBQoUKFCgQIH3L/4PnOMsMawpE9oAAAAASUVORK5CYII=';

    break;
    
}

//
// BASE64 LAST MODIFIED
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['lastmodified_base64_PNG'] = '2022-08-28 16:20:01.588859';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['lastmodified_base64_JPEG'] = '2022-08-28 16:20:01.591086';

//
// BASE64 HASH/CHECKSUM
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_crc'] = '3807229785';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_md5'] = '0eca3491972f8177639c3dfd561573d7';

self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_crc'] = '0';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_md5'] = 'd41d8cd98f00b204e9800998ecf8427e';

//
// HASHES FOR BASE64 SOURCE PNG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['md5'] = '0ddbd21a7448d4e718d5d912716ad2ef';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['sha1'] = '1f491f1fe6aa97eee2adec16cb6e9f26fae28aac';

//
// HASHES FOR BASE64 SOURCE JPEG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['md5'] = '';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['sha1'] = '';


# # # # # 
# # # # # END OF CRNRSTN :: GENERATED SYSTEM FILE
# # # # # [2022-08-28 16:20:01.591240] [rtime 0.513279] 
