<?php
/* 
// J5
// Code is Poetry */
# # C # R # N # R # S # T # N # : : # # # #
#
# CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
#
# DATE GENERATED: 2022-08-28 16:20:01.538878
# FILE NAME: powered_by_apache_2_2.php
# FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/base64/system/powered_by_apache_2_2.php
# FILE SERIAL: 1101101100111010000110000110111101010010110101000011011100001100
#
# SERVER IP: 172.16.225.139
# CLIENT IP: 172.16.225.1 (172.16.225.1)
# PHPSESSION: qkuh0gsqn5rnn4ffr3c7t177a1
# GENERATING SERVER INFORMATION: Ubuntu 18.04.1 LTS, Apache v2.4.29, MySQLi v5.7.39, php v7.0.33, OpenSSL v1.1.1, NuSOAP0.9.5
#
# # # # #
# PNG FILE (ORIGINAL) :: powered_by_apache_2_2.png
# PNG IMAGE DIMENSIONS: 259 pixels in width X 32 pixels in height.
# PNG FILE EXTENSION: png
# PNG FILE MIME TYPE: image/png
# PNG FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/png/system/powered_by_apache_2_2.png
# PNG FILE SIZE: 4.7207 KiB
# PNG FILE LAST MODIFIED: 2021-03-07 04:01:05
# PNG FILE MD5: 0d7408354716c562883009d882c5ca7f
# PNG FILE SHA1: 8f17c33a14b0e724e0788db519e5b21cc7c4ee0f
# PNG FILE ENCODED LENGTH (BASE64): 6,470 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
# JPEG FILE (ORIGINAL) :: 
# JPEG IMAGE DIMENSIONS:  pixels in width X  pixels in height.
# JPEG FILE EXTENSION: 
# JPEG FILE MIME TYPE: 
# JPEG FILE PATH: 
# JPEG FILE SIZE: 0 bytes
# JPEG FILE LAST MODIFIED: 1969-12-31 19:00:00
# JPEG FILE MD5: 
# JPEG FILE SHA1: 
# JPEG FILE ENCODED LENGTH (BASE64): 0 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
/*
      ___           ___           ___           ___           ___                       ___              
     /  /\         /  /\         /__/\         /  /\         /  /\          ___        /__/\             
    /  /:/        /  /::\        \  \:\       /  /::\       /  /:/_        /  /\       \  \:\          ___        ___
   /  /:/        /  /:/\:\        \  \:\     /  /:/\:\     /  /:/ /\      /  /:/        \  \:\        /__/\      /__/\    
  /  /:/  ___   /  /:/~/:/    _____\__\:\   /  /:/~/:/    /  /:/ /::\    /  /:/     _____\__\:\       \__\/      \__\/  
 /__/:/  /  /\ /__/:/ /:/___ /__/::::::::\ /__/:/ /:/___ /__/:/ /:/\:\  /  /::\    /__/::::::::\         
 \  \:\ /  /:/ \  \:\/:::::/ \  \:\~~\~~\/ \  \:\/:::::/ \  \:\/:/~/:/ /__/:/\:\   \  \:\~~\~~\/       ___        ___  
  \  \:\  /:/   \  \::/~~~~   \  \:\  ~~~   \  \::/~~~~   \  \::/ /:/  \__\/  \:\   \  \:\  ~~~       /__/\      /__/\   
   \  \:\/:/     \  \:\        \  \:\        \  \:\        \__\/ /:/        \  \:\   \  \:\           \__\/      \__\/   
    \  \::/       \  \:\        \  \:\        \  \:\         /__/:/          \__\/    \  \:\            
     \__\/         \__\/         \__\/         \__\/         \__\/                     \__\/             
        
        
        
        
<!-- 
ASCII ARTWORK GENERATED BY CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
ARTWORK TITLE :: Isometric3
TIMESTAMP :: 2022-08-28 16:20:01.538213

CREATIVE SOURCE :: http://patorjk.com/software/taag/#p=display&f=Isometric3&t=CRNRSTN%20%3A%3A
DATE :: Sunday, Jul 31, 2022 @ 0949 hrs ::  
-->        
*/


$system_file_serial = '1101101100111010000110000110111101010010110101000011011100001100';

switch(self::$image_output_mode){
    case CRNRSTN_BASE64_JPEG:
            
        //
        // BASE64 ENCODE OF JPG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_JPEG'] = '2022-08-28 16:20:01.544839';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64'] = '';

    break;
    default:
    
        //
        // BASE64 ENCODE OF PNG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_PNG'] = '2022-08-28 16:20:01.544798';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQMAAAAgCAYAAAAWnh3nAAAFRGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpDb2xvclNwYWNlPSIxIgogICBleGlmOlBpeGVsWERpbWVuc2lvbj0iMjU5IgogICBleGlmOlBpeGVsWURpbWVuc2lvbj0iMzIiCiAgIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiCiAgIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIKICAgdGlmZjpJbWFnZUxlbmd0aD0iMzIiCiAgIHRpZmY6SW1hZ2VXaWR0aD0iMjU5IgogICB0aWZmOlJlc29sdXRpb25Vbml0PSIyIgogICB0aWZmOlhSZXNvbHV0aW9uPSI3Mi4wIgogICB0aWZmOllSZXNvbHV0aW9uPSI3Mi4wIgogICB4bXA6TWV0YWRhdGFEYXRlPSIyMDIxLTAzLTA3VDA0OjAxOjA1LTA1OjAwIgogICB4bXA6TW9kaWZ5RGF0ZT0iMjAyMS0wMy0wN1QwNDowMTowNS0wNTowMCI+CiAgIDx4bXBNTTpIaXN0b3J5PgogICAgPHJkZjpTZXE+CiAgICAgPHJkZjpsaQogICAgICB4bXBNTTphY3Rpb249InByb2R1Y2VkIgogICAgICB4bXBNTTpzb2Z0d2FyZUFnZW50PSJBZmZpbml0eSBQaG90byAoRmViICAxIDIwMjEpIgogICAgICB4bXBNTTp3aGVuPSIyMDIxLTAzLTAxVDA0OjM1OjE3LTA1OjAwIi8+CiAgICAgPHJkZjpsaQogICAgICBzdEV2dDphY3Rpb249InByb2R1Y2VkIgogICAgICBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZmZpbml0eSBQaG90byAxLjkuMSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMS0wMy0wN1QwNDowMTowNS0wNTowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+btOY7gAAAYFpQ0NQc1JHQiBJRUM2MTk2Ni0yLjEAACiRdZHLS0JBFIc/tVDKMKhFQQuJamVRBlGbICUsiBAz6LXR6ytQu9yrhLQN2goFUZtei/oLahu0DoKiCKJd0LqoTcnt3BSUyDOcOd/8Zs5h5gxYw2klozcMQiab00IBn3thccltf8GGHQcjdEYUXZ0IBmeoa5/3WMx422/Wqn/uX2uOxXUFLA7hcUXVcsJTwjPrOdXkHeF2JRWJCZ8JezS5oPCdqUfL/GpysszfJmvhkB+srcLuZA1Ha1hJaRlheTk9mXReqdzHfIkznp2fk9gt3oVOiAA+3EwziV96MsSYzCP042VAVtTJH/zNn2VNchWZVQporJIkRQ6PqHmpHpeYED0uI03B7P/fvuqJYW+5utMHjc+G8d4L9m0oFQ3j68gwSsdge4LLbDV/7RBGP0QvVrWeA3BtwvlVVYvuwsUWdDyqES3yK9nErYkEvJ1CyyK03UDTcrlnlX1OHiC8IV91DXv70CfnXSs/Sspn2RTrUrEAAAAJcEhZcwAACxMAAAsTAQCanBgAAAu3SURBVHic7Zw9aCPbFcd/Sl7CbpFghxSzpVw82G0SO5DgLcek0RaBXUgxgjSzJAGZNNoiIHUZE0h2U3mbxwjSjDpvt4aQjJoQuQjIkELbSYEQrCaRCYRdUryTYuaO7ozuSKMP+/m9N3+4jOZ+nXtn5vzvOedeG0qUKFGiRIkSJUqUKFGiRIkSJeZR+awHYEIQBJLNq9frd3KsRRCGfZlMxoB5HsvKS9wdBEEg9Xp91TbAVt7t14HvAzbwPeDbwLfiBDAF/g38CxgAfwYugP+uLCkM+3NKmFdPpZWFFEDVsgSYS47j3Ii8m0Y8bpVWLi/x2SNeoDZKpkWuIL4GvAD+s4bc98CvgW8uE/IV/WYyGVO1rKVKPpmMmUzGvHkTpAhEBpYEQSDikVwLTzcHQRDgOA4A3W4Xz/MEIkLyPE8cxxHP85IxB0EgjuOI4zhJnuM40mw2k3bZ8jDsS7PZTPUD0Gw2xXEcCYJAVDv9hQZBIM1m0/iSVZ9KblGoOak+TfNReav2XWI9LLMG4pW/opKyBLKo1+tGq3cJKsAfgN8C38iUvQd+BfwY+CHwc+BvmTr3gF8CfwG+upJkpWRVy8plMqUEuvKIbYlgSPuI2JaIh4hHIWsiYxmkWFlTPiPzxv0LIJ7npeoqhQakalkyGAwksyqn5q3GodeJ8+asF51EYyXNS3PIjsHQZ8oyyoyrxA1j0fe2Sv1FbRbgY+CvOemnhvp2nmwiF2N1hGFfqpYlVcsStRorNBoN8TxPVzYEVxzHEcEVwY+vOeSgkofIYN4S0RXNcRzR73XlqFpWqlwpuK4suqI1m81UmXppSsHjec4pnZ601T6pp2RoK7VxfBQgA9OY9Xt9/jflppVYD8tciQ3chKL4LjDOkd9j0xihshIUKYRhX0REGo2GNBqNRAEEX3xEBF+miDSbTY0UFFEYSMFjZj3Y0apsUkK1YmetBEivxMpq0dvpZFGkXpzI1tfdBb2N3r8+PkWi68QMdNLKEqDK3+jFltgmlpLADRPBA+AT4FOD/CvgF0TuwubQXQclRH3AyjpwEXER8ePrjBzc5BqRg2+2GDSSyFoCg8EgSbpimMhAC2zmrrZZS4AcJc2QSAKdDEzPSperk0eenGy5TihZ60Of59IXV+LGUCSgeAsk8B3g98D/DPL7wM+A+zcmPftR6oqmFntFCnqaxgShiGJmNfhzloPev2AlVoOKOehkkf2tSEMfZxAEoiu+UjCTP665ErlkkKesi9wLLS19pnrSA4lZmSVuHwVIYKP+CpDHR8CPgD8aZH8K/An4CfADQ9pbdXxG6JHsRQ9kH5kjBp0clBuhE4OvEUTWx9atBsdxRGxLwqc7c66ECrYpMlDKn1HkuQduckuUxZFHBmAOEqp+DdbAymSQjdVkA6HF3lqJbWDZN79Kyn57y+posIA28I8N5H+yjedBGPal0WgkH7njOKICiYoATEmPF+5rpJC1HtKk4Ca/o9iDm3Ij9JhD+HQnsRqCIEgCkqsqTBj21zLptB2MG4X+3G9aVok0tkUEGBS9gGXwMfA74O/APzdMv9nKw9D355vNpjQaDQFQK7yrKbzpIWQtBsdxkqtODtO5mIOyIPTdihkxoFsPelBSJXvmZnxeV1TdnbmFiHSJLykKbTVklWgyGWNZVY6OHlcEXzq4uHR4jpvUGcTXywUi9jNW80HcrkF0hvIwvvp0ANDl+DzP9PY2dVd3bIJuTxM2gWdAz0qyuu6rO3/8d9QayVHnMYe2TbfbvdNjLfElgn5iT13V1qHgxrGA6Kq7A65mFbDEjMq6FfoORTYYmbYcskFJXxqNRiooaTz7oG1prutilCjxRcBaK00Y9uXo6HElDPtinzyNjjMA8IQOPm68kl/jskOHTmwx6Ks9QKeAeN160C2H18wsiJeQyFF9+zznGp+deCwKL5rvePnqOr6LrYn9SXS9tFJ1saHXesPR0eNbX5Fj4uQAaLXG7J3srTUGP+5nG7BbYz48uuZR/WClsYxaI7l/uZvKe3C+u9EzvfJ8AbDa7bXaTzyPafVg4VyGwUAenL1O5U3rVfaetVeb/5knVS89znHbW9jP1Le39t6mu3ahMW/8kYdhXy4uerTap1ruk0ytQ65xOQNcOlzH5PCCGTkMWOxSKOwjXFKZIwniPtTvQyKvQMlQeMaMOCLSuqDuvCfo2szoivj322guXofeYf/WSGFfU2A1H692vZYCjVoj6Z1UtzY2gMfBZWFCmNZeys75jrHsXbBYGU0YBgN5WK+t0mQhJp7Hg/Zz4xiGwUAevjxI5V1XXXbfdDYmA4DKgg9+6tuyM+nlFa+E8cPFxKPw0aaClIWA1+YELyYF3X9/AlywA0lEYScmBD9ZtV1eAmexgi8iB5Wnl10yIwl99+51pu0hcAZcxPIignJ53SUeSTTCy8Yxp6/V2N9C28LmKYIl2FFfJ/YxrfYY7LdbtR50iwBmBFc73+GqNpVNV1QFuzUuXDdLJveGZuXOQvCF8/zyh/UBw2AgqxCCiQgmnleo7b3+Ndx7x86b2fe5kmVxacF2eXUljB8Wm+edQBj2Rez4PEDs9JM6K+BK+iSim/j/etJ3FfxM/AFYtIe/NB6hrm4mLrGvyZjGyUfE8zzjlqfgi+xHJzDV31iY/s5ilWfnkj6bAXBVm6bG6CIryRi1RnMHwFZ1HbJtR63RwvbDYDD3TlWbq9p0rmwYDAqPx3RqdZW5TGsv59rnyR8GA5kLYmWj3gUwOvNW7mfq2+ldsS38BfAy3JjZKwNLTs6PadGOlmOY98lT7kTkMER+/szfV3EHIHEvIOpSdwMuG8f0X59ySQXHceh2u2uNex/hYEkdn+eceNVobgA1SFbAGoBFb1rcWgjDvnSPDlNuTodK0vaqNpXa+U4SMzkAnPCiUP95bsImloG9IIYRmfGDVN64Zafqj1ojqZ6kTeCiLoNJ+StMCn/Hw2Agu+MB02r0pJfFDLJuwjaxqptwbdkL+ysaG8gdz7oNV0EQBOKM69SHDsG77hwpVJgguMzciyekPX2Fi5z8GToaYTxjxkN68PK9E/1t+v1uQCeOPxSJVyiSEY9oLi+6EQkoy1X/TTTHZaQwDAbyqr6fSwQKJkJoFvDdbzNmYFLyLBEsqjvxyPXfFTYlg1Vw18hgGYrGBnLHs27DdZAEG2nPiEEhJoiIGGZkEZ0XuE+aKHQoFU+ThG5RZO9V8DC726EsDT8uU0TSc+rc7wYJiQBGy0P9ExaA4FFcXsu3ErJEoBNCHrJ1lxHCNslg0W6CSbnXwTJC2JQMrjxf7g2iPacPB4cLdxTyyGDyzDf2/f7hxJhvCh7C6mSwLGawCRHAZ/g/EJXfa188jgKPvVOwJ7OlHAxuxTxZqPvZISNFFvqugH6vY2Yv6NuQs50Gc50Tb0KrZnjByjI4h0p7ZkkEQcB4PKbdbqdM5Wexkpp2Q9DyFLKEocrOFpjtJjJYZOavg20RgcJ17Zrd8xfG8W1KBtOnrugBRIB3wbmREPLIYJESm7Ct3YRK+2b19c6daFMkMZmMGY/HtHqnUeT+zKB8l1Z0RsBAGhHUuYcHyf08og8jIhN9e/EiU6b+EjQilePGJacP4v0KFTOYC3SbXQUTEbTiVVfHo/pBxRTcujfc4SRuv4wQbpoM8lyD7FwWYXc8wMq83jxCMJHBJrsJkE8md40M9JjBdHdx/CCLWzlncFtQJJFsZcZQbsfeqYV7fEyrd8reEEaPiA9DRQSwZ71lNIETL9oSPPGq8TZovH2YumbxNu4DRpN0eS90ozHUTjk5P6ZVO6X77hVg/m+4yvdXKOr7Z6G7GArnhrMIN0kGgj+nmOucHQBz4NHU35Xny7oHjUy4fvok99zAXSODTVDEqvjckMEXAWHYl2ovbcWM7cnaZxSK9DcMBpI9F7DOKcIsTP1uSjAq0q/D5NOb6q2DZcFKiBRZv//wobbWs8v2A4tXa1P9TbBpPKFEiRIlSpQoUaJEiRIlSpQo8eXF/wFUs5vjZZYqbgAAAABJRU5ErkJggg==';

    break;
    
}

//
// BASE64 LAST MODIFIED
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['lastmodified_base64_PNG'] = '2022-08-28 16:20:01.546352';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['lastmodified_base64_JPEG'] = '2022-08-28 16:20:01.547876';

//
// BASE64 HASH/CHECKSUM
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_crc'] = '1305624201';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_md5'] = 'dbb63950f78da9944b10fdefdb13d26e';

self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_crc'] = '0';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_md5'] = 'd41d8cd98f00b204e9800998ecf8427e';

//
// HASHES FOR BASE64 SOURCE PNG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['md5'] = '0d7408354716c562883009d882c5ca7f';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['sha1'] = '8f17c33a14b0e724e0788db519e5b21cc7c4ee0f';

//
// HASHES FOR BASE64 SOURCE JPEG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['md5'] = '';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['sha1'] = '';


# # # # # 
# # # # # END OF CRNRSTN :: GENERATED SYSTEM FILE
# # # # # [2022-08-28 16:20:01.547998] [rtime 0.470034] 
