<?php
/* 
// J5
// Code is Poetry */
# # C # R # N # R # S # T # N # : : # # # #
#
# CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
#
# DATE GENERATED: 2022-08-28 16:20:01.878693
# FILE NAME: primary_nav_seriesblue00_120x120_menu.php
# FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/base64/system/primary_nav_seriesblue00_120x120_menu.php
# FILE SERIAL: 1001011010110001111001111100010011001110011110101010000001110101
#
# SERVER IP: 172.16.225.139
# CLIENT IP: 172.16.225.1 (172.16.225.1)
# PHPSESSION: qkuh0gsqn5rnn4ffr3c7t177a1
# GENERATING SERVER INFORMATION: Ubuntu 18.04.1 LTS, Apache v2.4.29, MySQLi v5.7.39, php v7.0.33, OpenSSL v1.1.1, NuSOAP0.9.5
#
# # # # #
# PNG FILE (ORIGINAL) :: primary_nav_seriesblue00_120x120_menu.png
# PNG IMAGE DIMENSIONS: 120 pixels in width X 120 pixels in height.
# PNG FILE EXTENSION: png
# PNG FILE MIME TYPE: image/png
# PNG FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/png/system/primary_nav_seriesblue00_120x120_menu.png
# PNG FILE SIZE: 5.57715 KiB
# PNG FILE LAST MODIFIED: 2022-07-06 05:46:32
# PNG FILE MD5: 377b60ffdb6e689bc656e285ae8adbc8
# PNG FILE SHA1: 66c581e242d4525ddba4d75c7dfc45fb69fc198d
# PNG FILE ENCODED LENGTH (BASE64): 7,638 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
# JPEG FILE (ORIGINAL) :: 
# JPEG IMAGE DIMENSIONS:  pixels in width X  pixels in height.
# JPEG FILE EXTENSION: 
# JPEG FILE MIME TYPE: 
# JPEG FILE PATH: 
# JPEG FILE SIZE: 0 bytes
# JPEG FILE LAST MODIFIED: 1969-12-31 19:00:00
# JPEG FILE MD5: 
# JPEG FILE SHA1: 
# JPEG FILE ENCODED LENGTH (BASE64): 0 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
/*
      ___           ___           ___           ___           ___                         ___              
     /\__\         /\  \         /\  \         /\  \         /\__\                       /\  \             
    /:/  /        /::\  \        \:\  \       /::\  \       /:/ _/_         ___          \:\  \          ___         ___
   /:/  /        /:/\:\__\        \:\  \     /:/\:\__\     /:/ /\  \       /\__\          \:\  \        /\__\       /\__\      
  /:/  /  ___   /:/ /:/  /    _____\:\  \   /:/ /:/  /    /:/ /::\  \     /:/  /      _____\:\  \       \/__/       \/__/          
 /:/__/  /\__\ /:/_/:/__/___ /::::::::\__\ /:/_/:/__/___ /:/_/:/\:\__\   /:/__/      /::::::::\__\         
 \:\  \ /:/  / \:\/:::::/  / \:\~~\~~\/__/ \:\/:::::/  / \:\/:/ /:/  /  /::\  \      \:\~~\~~\/__/       ___         ___
  \:\  /:/  /   \::/~~/~~~~   \:\  \        \::/~~/~~~~   \::/ /:/  /  /:/\:\  \      \:\  \            /\__\       /\__\         
   \:\/:/  /     \:\~~\        \:\  \        \:\~~\        \/_/:/  /   \/__\:\  \      \:\  \           \/__/       \/__/     
    \::/  /       \:\__\        \:\__\        \:\__\         /:/  /         \:\__\      \:\__\          
     \/__/         \/__/         \/__/         \/__/         \/__/           \/__/       \/__/      
	 
        
        
        
<!-- 
ASCII ARTWORK GENERATED BY CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
ARTWORK TITLE :: Isometric2
TIMESTAMP :: 2022-08-28 16:20:01.878007

CREATIVE SOURCE :: http://patorjk.com/software/taag/#p=display&f=Isometric2&t=CRNRSTN%20%3A%3A
DATE :: Sunday, Jul 31, 2022 @ 0949 hrs ::  
-->        
*/


$system_file_serial = '1001011010110001111001111100010011001110011110101010000001110101';

switch(self::$image_output_mode){
    case CRNRSTN_BASE64_JPEG:
            
        //
        // BASE64 ENCODE OF JPG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_JPEG'] = '2022-08-28 16:20:01.884489';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64'] = '';

    break;
    default:
    
        //
        // BASE64 ENCODE OF PNG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_PNG'] = '2022-08-28 16:20:01.884449';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAB4CAYAAAA5ZDbSAAAFYmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjEyMCIKICAgZXhpZjpQaXhlbFlEaW1lbnNpb249IjEyMCIKICAgZXhpZjpDb2xvclNwYWNlPSI2NTUzNSIKICAgdGlmZjpJbWFnZVdpZHRoPSIxMjAiCiAgIHRpZmY6SW1hZ2VMZW5ndGg9IjEyMCIKICAgdGlmZjpSZXNvbHV0aW9uVW5pdD0iMiIKICAgdGlmZjpYUmVzb2x1dGlvbj0iOTYvMSIKICAgdGlmZjpZUmVzb2x1dGlvbj0iOTYvMSIKICAgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIKICAgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9IkRpc3BsYXkiCiAgIHhtcDpNb2RpZnlEYXRlPSIyMDIyLTA3LTA2VDA1OjQ2OjMyLTA0OjAwIgogICB4bXA6TWV0YWRhdGFEYXRlPSIyMDIyLTA3LTA2VDA1OjQ2OjMyLTA0OjAwIj4KICAgPGRjOnRpdGxlPgogICAgPHJkZjpBbHQ+CiAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ij5zcXVhcmVfdGVtcGxhdGVfbWVudV9CTFVFMDA8L3JkZjpsaT4KICAgIDwvcmRmOkFsdD4KICAgPC9kYzp0aXRsZT4KICAgPHhtcE1NOkhpc3Rvcnk+CiAgICA8cmRmOlNlcT4KICAgICA8cmRmOmxpCiAgICAgIHN0RXZ0OmFjdGlvbj0icHJvZHVjZWQiCiAgICAgIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFmZmluaXR5IERlc2lnbmVyIDEuMTAuNSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMi0wNy0wNlQwNTo0NjozMi0wNDowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+sEaQLQAADFJpQ0NQRGlzcGxheQAASImlV3dYU8kWn1tSSWiBCEgJvQkiSJcSQosgIB1shCSQQIgxIYjYlUUF1y4qWNFVEUXXAogdsbso9r5YUFlZFws2VN6EBHT1e++fd75v7v3lzJnfKTn33hkAdHZK+HkKVBeAPGm+PD4ihJWals4iPQUIMAfawBXgPL5Cxo6LiwZQ+u//lnc3oDWUqy4qrp/n/6foCYQKPgBIHMT5AgU/D+JmAPBivkyeDwAxEuqtJ+fLVFgCsYEcBgjxLBXOVuMVKpypxtv7bBLjORAfBoBM4/Hk2QBon4V6VgE/G/JoP4fYTSoQSwHQMYI4kC/iCSBOhXhIXt5EFS6G2CHzO57sf3FmDnDyeNkDWJ1Ln5BDxQqZhDelP08yCAVioAAyIAE8MKD+/yVPouz3aQcHTSSPjFfVANbxVu7EKBWmQdwpzYyJhVgf4g9iQZ89xChVpIxMUtujpnwFB9YQMCF2E/BCoyA2hThcKomJ1ugzs8ThXIhhx6CF4nxuombtfKEiLEHDuVY+MT62H2fJOWzN2lqevM+vyr5ZmZvE1vDfEgm5/fxvi0SJKeqYMWqBODkGYm2ImYrchCi1DWZTJOLE9NvIlfGq+G0g9hNKI0LU/Nj4LHl4vMZerulKGA82XyTmxmhwRb4oMVLDs5PP64sf9gPWIJSyk/p5hIrU6P5cBMLQMHXu2GWhNEmTL9Ymyw+J16x9LZPEaexxqlASodJbQWyqKEjQrMUD82GDqvnxGFl+XKI6TjwzhzcyTh0PXgiiAQf2DAso4cgEE0EOELd01nfCX+qZcNhHcpANhMBFo+lfkdI3I4XXBFAE/oZICDuvf11I36wQFED9lwGt+uoCsvpmC/pW5IKnEOeBKNizQhiHapV0wFsyeAI14p+882GsEjhUcz/r2FATrdEo+3lZOv2WxDBiKDGSGE50xE3wQNwfj4bXYDjccR/ctz/ab/aEp4RWwiPCdUIb4fYE8Rz5D/mwwCjQBj2Ea3LO/D5n3A6yeuIheADkh9w4EzcBLvhw6ImNB0HfnlDL0USuyv5H7n/l8F3VNXYUNwpKGUQJpjj8uFLbSdtzgEVV0+8rpI41c6CunIGZH/1zvqu0AN6jfrTE5mP7sDPYCewcdhirByzsGNaAXcSOqPBAFz3p66J+b/F98eRCHvFP/ngan6pKKtxq3DrcPqvn8oWF+aoHjDNRNkUuzhbls9gymUTI4kr5rkNY7m7u7gCovivq19QbZt/3AmGe/6abux6AgP29vb2HvumiGgHYVwYA9eY3nf10+Do4AcDZSr5SXqDW4aoLAVCBDnyijOF3yxo4wHzcgRfwB8EgDIwEsSARpIHxsMoi2M9yMBlMA7NBCSgDS8BKUAE2gM1gO9gF9oJ6cBicAKfBBXAZXAd3Yfe0gxegC7wDPQiCkBA6wkCMEQvEFnFG3BEfJBAJQ6KReCQNyUCyESmiRKYhc5EyZBlSgWxCqpHfkYPICeQc0orcRh4iHchr5BOKoTTUADVD7dChqA/KRqPQRHQcmo1OQovQYnQRuhqtQneidegJ9AJ6HW1DX6DdGMC0MCZmiblgPhgHi8XSsSxMjs3ASrFyrAqrxRrh/3wVa8M6sY84EWfgLNwFdnAknoTz8Un4DHwhXoFvx+vwZvwq/hDvwr8S6ARTgjPBj8AlpBKyCZMJJYRywlbCAcIp+DS1E94RiUQm0Z7oDZ/GNGIOcSpxIXEdcTfxOLGV+JjYTSKRjEnOpABSLIlHyieVkNaQdpKOka6Q2kkfyFpkC7I7OZycTpaS55DLyTvIR8lXyM/IPRRdii3FjxJLEVCmUBZTtlAaKZco7ZQeqh7VnhpATaTmUGdTV1Nrqaeo96hvtLS0rLR8tUZribVmaa3W2qN1Vuuh1keaPs2JxqGNpSlpi2jbaMdpt2lv6HS6HT2Ynk7Ppy+iV9NP0h/QP2gztF21udoC7Znaldp12le0X+pQdGx12DrjdYp0ynX26VzS6dSl6NrpcnR5ujN0K3UP6t7U7dZj6A3Ti9XL01uot0PvnN5zfZK+nX6YvkC/WH+z/kn9xwyMYc3gMPiMuYwtjFOMdgOigb0B1yDHoMxgl0GLQZehvuFww2TDQsNKwyOGbUyMacfkMiXMxcy9zBvMT4PMBrEHCQctGFQ76Mqg90aDjYKNhEalRruNrht9MmYZhxnnGi81rje+b4KbOJmMNplsst7klEnnYIPB/oP5g0sH7x18xxQ1dTKNN51qutn0omm3mblZhJnMbI3ZSbNOc6Z5sHmO+Qrzo+YdFgyLQAuxxQqLYxZ/sQxZbJaEtZrVzOqyNLWMtFRabrJsseyxsrdKsppjtdvqvjXV2sc6y3qFdZN1l42FzSibaTY1NndsKbY+tiLbVbZnbN/b2dul2M2zq7d7bm9kz7Uvsq+xv+dAdwhymORQ5XDNkejo45jruM7xshPq5Okkcqp0uuSMOns5i53XObcOIQzxHSIdUjXkpgvNhe1S4FLj8tCV6RrtOse13vXlUJuh6UOXDj0z9Kubp5vEbYvb3WH6w0YOmzOscdhrdyd3vnul+zUPuke4x0yPBo9Xw52HC4evH37Lk+E5ynOeZ5PnFy9vL7lXrVeHt413hvda75s+Bj5xPgt9zvoSfEN8Z/oe9v3o5+WX77fX7x9/F/9c/x3+z0fYjxCO2DLicYBVAC9gU0BbICswI3BjYFuQZRAvqCroUbB1sCB4a/AztiM7h72T/TLELUQeciDkPcePM51zPBQLjQgtDW0J0w9LCqsIexBuFZ4dXhPeFeEZMTXieCQhMipyaeRNrhmXz63mdo30Hjl9ZHMULSohqiLqUbRTtDy6cRQ6auSo5aPuxdjGSGPqY0EsN3Z57P04+7hJcYdGE0fHja4c/TR+WPy0+DMJjIQJCTsS3iWGJC5OvJvkkKRMakrWSR6bXJ38PiU0ZVlKW+rQ1OmpF9JM0sRpDemk9OT0rendY8LGrBzTPtZzbMnYG+PsxxWOOzfeZLxk/JEJOhN4E/ZlEDJSMnZkfObF8qp43ZnczLWZXXwOfxX/hSBYsELQIQwQLhM+ywrIWpb1PDsge3l2hyhIVC7qFHPEFeJXOZE5G3Le58bmbsvtlaRIdueR8zLyDkr1pbnS5onmEwsntsqcZSWytkl+k1ZO6pJHybcqEMU4RUO+AdzAX1Q6KH9RPiwILKgs+DA5efK+Qr1CaeHFKU5TFkx5VhRe9NtUfCp/atM0y2mzpz2czp6+aQYyI3NG00zrmcUz22dFzNo+mzo7d/Yfc9zmLJvzdm7K3MZis+JZxY9/ifilpkS7RF5yc57/vA3z8fni+S0LPBasWfC1VFB6vsytrLzs80L+wvO/Dvt19a+9i7IWtSz2Wrx+CXGJdMmNpUFLty/TW1a07PHyUcvrVrBWlK54u3LCynPlw8s3rKKuUq5qWx29umGNzZolaz5XiCquV4ZU7l5runbB2vfrBOuurA9eX7vBbEPZhk8bxRtvbYrYVFdlV1W+mbi5YPPTLclbzvzm81v1VpOtZVu/bJNua9sev7252ru6eofpjsU1aI2ypmPn2J2Xd4Xuaqh1qd20m7m7bA/Yo9zz1+8Zv9/YG7W3aZ/Pvtr9tvvXHmAcKK1D6qbUddWL6tsa0hpaD4482NTo33jgkOuhbYctD1ceMTyy+Cj1aPHR3mNFx7qPy453nsg+8bhpQtPdk6knrzWPbm45FXXq7Onw0yfPsM8cOxtw9vA5v3MHz/ucr7/gdaHuoufFA394/nGgxaul7pL3pYbLvpcbW0e0Hr0SdOXE1dCrp69xr124HnO99UbSjVs3x95suyW49fy25ParOwV3eu7Ouke4V3pf9375A9MHVX86/rm7zavtyMPQhxcfJTy6+5j/+MUTxZPP7cVP6U/Ln1k8q37u/vxwR3jH5b/G/NX+Qvaip7Pkb72/1750eLn/n+B/LnaldrW/kr/qfb3wjfGbbW+Hv23qjut+8C7vXc/70g/GH7Z/9Pl45lPKp2c9kz+TPq/+4vil8WvU13u9eb29Mp6c17cVwOBAs7IAeL0NAHoaAIzLcP8wRn3u6xNEfVbtQ+C/YfXZsE+8AKiFN9V2nXMcgD1w2AVDbnhXbdUTgwHq4TEwNKLI8nBXc9HgiYfwobf3jRkAJLif+SLv7e1Z19v7ZQsM9jYAxyepz5sqIcKzwUY3FbpisQ/8KP8Bxu2Efs6OyPQAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAQ1SURBVHic7dzPaxxlHMfx90w3iY1JWpQpelIQ6cU/INqLtQXBk6VCeljsRWQ89CRo/QFVsLQKFao9jKCHlkHIqeKlBCp4ij15Cp689CCKi0W7adp1Sx4Ps9ud2Zlss5Xv08zyeUG6m53neb7T52HIM893nwEREREREREREREREREREREREREREREREREREREREREREREZJfAVqJm0ngKeBx7zFXOHugH8lMbRdR/BzAe4mbSmgHPACetYNfMl8HYaR13LIKFl4z0fo8GtcgL4yDqI6RXcTFqPAr8D85ZxaqwNPJnG0S2rANZX8B40uKPMk/WRGesB3gDuGseosy5ZH5kxHeA0jv4GLlnGqLlLvT4y42OS9Q7wg4c4dXMVeNc6iJf74GbSaiw+M53sngoObToaQ4ed673i4N77itd+wcHb/stQO8XKjlwplzuO23adwrkUog4fdy53msX/G0AYBrc7Xbey9lv3bBpH5n++vC10LF9bPwYczMUd52fcOjs9xvdLi3Pvj9WBIiIyaXxNsgLgOeAFlGy4AawCa2kcufsV/r98JBt2AwnwunWsmrkIvJXG0W3LID7ug0+jwa1yHPjEOoh1smEe+AOYtYxTYxvAE2kcta0CWF/B82hwR5nFOBljPcDrQMc4Rp11yPrIjHWy4SbwjWWMmvu610dmfEyyTgLfeYhTN5eB96yD+LoPDg88O31+phG84gbJhtJCPxUL+QwnCVxu0X/r+vnPnes3UUpWVLRVTFwM2nKFRMVwvVHnVTinMODO3U135efr3XNpHG1izGey4ShwKBd3pyYCfJS/srQ4d3KsDhQRkUnjbZJFlmjQzobezgZgdSImWc2ktUC2sP6qdayauQwct1ymBD/3wWfQ4FY5QtY3pqyTDQvAn8CMZZwa6wD7LFezrK/gOTS4o8yQ9ZEZ6wFuY/zN/ZrbIOsjM9bJhjbwlWWMmksmYZL1Adq+UuUi8KF1EG9funtx/8zn043gNQe7eh8PJxb6a/mlxfrev9Wf98uXF/vv10Z1+epdElvuaqCczHBV9ftvwoA7zrGy+uu/ZyfiS3d9y9fWDzNesmG75cYp+zDbzJf7cWlx7tT2e09ERCaQr0lWA3gZJRtgkGxYmYjto82k9TiwzGCCJZmrwLE0jv6yDOLjPvgzNLhVDgOfWgexTjbsBVpQ2tUvmS5ZssHsOR3WV/AsGtxRpjDe+WE9wP9gvJheczfJ+siMdbLhFnDBMkbNXbB8yh34mWSdInvwphR9Qd2fVZn37Wr7lzBgf+/X/GI/VC/uVy38l3Y8lI6XEhhbtD8iMfAAdYbPL5eUcIU6YRB0O113/s2XFrykUb1NgHaFwRvA02yxSB9ULdAH3ncfGMQISp89MhWsPUAXioiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIjIw/Ef8ueKaf0w+BUAAAAASUVORK5CYII=';

    break;
    
}

//
// BASE64 LAST MODIFIED
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['lastmodified_base64_PNG'] = '2022-08-28 16:20:01.886046';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['lastmodified_base64_JPEG'] = '2022-08-28 16:20:01.887577';

//
// BASE64 HASH/CHECKSUM
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_crc'] = '981014607';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_md5'] = '99dd348e91314d85a973d4a818a57d1f';

self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_crc'] = '0';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_md5'] = 'd41d8cd98f00b204e9800998ecf8427e';

//
// HASHES FOR BASE64 SOURCE PNG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['md5'] = '377b60ffdb6e689bc656e285ae8adbc8';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['sha1'] = '66c581e242d4525ddba4d75c7dfc45fb69fc198d';

//
// HASHES FOR BASE64 SOURCE JPEG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['md5'] = '';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['sha1'] = '';


# # # # # 
# # # # # END OF CRNRSTN :: GENERATED SYSTEM FILE
# # # # # [2022-08-28 16:20:01.887705] [rtime 0.809741] 
