<?php
/* 
// J5
// Code is Poetry */
# # C # R # N # R # S # T # N # : : # # # #
#
# CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
#
# DATE GENERATED: 2022-08-28 16:20:02.564879
# FILE NAME: primary_nav_seriesblue00_120x120_minimize_fivedev_sm.php
# FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/base64/system/primary_nav_seriesblue00_120x120_minimize_fivedev_sm.php
# FILE SERIAL: 0001010011010100111011010011010001111100001100110111011111011101
#
# SERVER IP: 172.16.225.139
# CLIENT IP: 172.16.225.1 (172.16.225.1)
# PHPSESSION: qkuh0gsqn5rnn4ffr3c7t177a1
# GENERATING SERVER INFORMATION: Ubuntu 18.04.1 LTS, Apache v2.4.29, MySQLi v5.7.39, php v7.0.33, OpenSSL v1.1.1, NuSOAP0.9.5
#
# # # # #
# PNG FILE (ORIGINAL) :: primary_nav_seriesblue00_120x120_minimize_fivedev_sm.png
# PNG IMAGE DIMENSIONS: 120 pixels in width X 120 pixels in height.
# PNG FILE EXTENSION: png
# PNG FILE MIME TYPE: image/png
# PNG FILE PATH: /var/www/html/lightsaber.crnrstn.evifweb.com/_crnrstn/ui/imgs/png/system/primary_nav_seriesblue00_120x120_minimize_fivedev_sm.png
# PNG FILE SIZE: 6.15527 KiB
# PNG FILE LAST MODIFIED: 2022-07-06 16:39:43
# PNG FILE MD5: fae8f8eab43ff700377278ab33ee6687
# PNG FILE SHA1: f0b2eb3c09924941f9d631ef65eec68f15a7909b
# PNG FILE ENCODED LENGTH (BASE64): 8,426 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
# JPEG FILE (ORIGINAL) :: 
# JPEG IMAGE DIMENSIONS:  pixels in width X  pixels in height.
# JPEG FILE EXTENSION: 
# JPEG FILE MIME TYPE: 
# JPEG FILE PATH: 
# JPEG FILE SIZE: 0 bytes
# JPEG FILE LAST MODIFIED: 1969-12-31 19:00:00
# JPEG FILE MD5: 
# JPEG FILE SHA1: 
# JPEG FILE ENCODED LENGTH (BASE64): 0 bytes
# PROFILE ACCESS: ANONYMOUS
# ACCESS TYPE: BASIC
#
# # # # #
/*
 ######  ########  ##    ## ########   ######  ######## ##    ##     ##   ##  
##    ## ##     ## ###   ## ##     ## ##    ##    ##    ###   ##    #### #### 
##       ##     ## ####  ## ##     ## ##          ##    ####  ##     ##   ##  
##       ########  ## ## ## ########   ######     ##    ## ## ##              
##       ##   ##   ##  #### ##   ##         ##    ##    ##  ####     ##   ##  
##    ## ##    ##  ##   ### ##    ##  ##    ##    ##    ##   ###    #### #### 
 ######  ##     ## ##    ## ##     ##  ######     ##    ##    ##     ##   ##  
        
        
        
        
<!-- 
ASCII ARTWORK GENERATED BY CRNRSTN :: v2.00.0000 PRE-ALPHA-DEV (Lightsaber)
ARTWORK TITLE :: Banner3
TIMESTAMP :: 2022-08-28 16:20:02.564040

CREATIVE SOURCE :: http://patorjk.com/software/taag/#p=display&f=Banner3&t=CRNRSTN%20%3A%3A
DATE :: Sunday, Jul 31, 2022 @ 0949 hrs ::  
-->        
*/


$system_file_serial = '0001010011010100111011010011010001111100001100110111011111011101';

switch(self::$image_output_mode){
    case CRNRSTN_BASE64_JPEG:
            
        //
        // BASE64 ENCODE OF JPG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_JPEG'] = '2022-08-28 16:20:02.574962';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64'] = '';

    break;
    default:
    
        //
        // BASE64 ENCODE OF PNG
        self::$image_filesystem_meta_ARRAY[self::$image_output_mode][self::$request_salt][$system_file_serial]['datecreated_base64_PNG'] = '2022-08-28 16:20:02.574895';
        self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64'] = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAB4CAYAAAA5ZDbSAAAFcWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS41LjAiPgogPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyIKICAgIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIKICAgIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIKICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIKICAgZXhpZjpQaXhlbFhEaW1lbnNpb249IjEyMCIKICAgZXhpZjpQaXhlbFlEaW1lbnNpb249IjEyMCIKICAgZXhpZjpDb2xvclNwYWNlPSI2NTUzNSIKICAgdGlmZjpJbWFnZVdpZHRoPSIxMjAiCiAgIHRpZmY6SW1hZ2VMZW5ndGg9IjEyMCIKICAgdGlmZjpSZXNvbHV0aW9uVW5pdD0iMiIKICAgdGlmZjpYUmVzb2x1dGlvbj0iOTYvMSIKICAgdGlmZjpZUmVzb2x1dGlvbj0iOTYvMSIKICAgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIKICAgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9IkRpc3BsYXkiCiAgIHhtcDpNb2RpZnlEYXRlPSIyMDIyLTA3LTA2VDE2OjM5OjQzLTA0OjAwIgogICB4bXA6TWV0YWRhdGFEYXRlPSIyMDIyLTA3LTA2VDE2OjM5OjQzLTA0OjAwIj4KICAgPGRjOnRpdGxlPgogICAgPHJkZjpBbHQ+CiAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ij5zcXVhcmVfdGVtcGxhdGVfbWluaW1pemVfQkxVRTAwX2ZpdmVkZXZfc208L3JkZjpsaT4KICAgIDwvcmRmOkFsdD4KICAgPC9kYzp0aXRsZT4KICAgPHhtcE1NOkhpc3Rvcnk+CiAgICA8cmRmOlNlcT4KICAgICA8cmRmOmxpCiAgICAgIHN0RXZ0OmFjdGlvbj0icHJvZHVjZWQiCiAgICAgIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFmZmluaXR5IERlc2lnbmVyIDEuMTAuNSIKICAgICAgc3RFdnQ6d2hlbj0iMjAyMi0wNy0wNlQxNjozOTo0My0wNDowMCIvPgogICAgPC9yZGY6U2VxPgogICA8L3htcE1NOkhpc3Rvcnk+CiAgPC9yZGY6RGVzY3JpcHRpb24+CiA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSJyIj8+WvZangAADFJpQ0NQRGlzcGxheQAASImlV3dYU8kWn1tSSWiBCEgJvQkiSJcSQosgIB1shCSQQIgxIYjYlUUF1y4qWNFVEUXXAogdsbso9r5YUFlZFws2VN6EBHT1e++fd75v7v3lzJnfKTn33hkAdHZK+HkKVBeAPGm+PD4ihJWals4iPQUIMAfawBXgPL5Cxo6LiwZQ+u//lnc3oDWUqy4qrp/n/6foCYQKPgBIHMT5AgU/D+JmAPBivkyeDwAxEuqtJ+fLVFgCsYEcBgjxLBXOVuMVKpypxtv7bBLjORAfBoBM4/Hk2QBon4V6VgE/G/JoP4fYTSoQSwHQMYI4kC/iCSBOhXhIXt5EFS6G2CHzO57sf3FmDnDyeNkDWJ1Ln5BDxQqZhDelP08yCAVioAAyIAE8MKD+/yVPouz3aQcHTSSPjFfVANbxVu7EKBWmQdwpzYyJhVgf4g9iQZ89xChVpIxMUtujpnwFB9YQMCF2E/BCoyA2hThcKomJ1ugzs8ThXIhhx6CF4nxuombtfKEiLEHDuVY+MT62H2fJOWzN2lqevM+vyr5ZmZvE1vDfEgm5/fxvi0SJKeqYMWqBODkGYm2ImYrchCi1DWZTJOLE9NvIlfGq+G0g9hNKI0LU/Nj4LHl4vMZerulKGA82XyTmxmhwRb4oMVLDs5PP64sf9gPWIJSyk/p5hIrU6P5cBMLQMHXu2GWhNEmTL9Ymyw+J16x9LZPEaexxqlASodJbQWyqKEjQrMUD82GDqvnxGFl+XKI6TjwzhzcyTh0PXgiiAQf2DAso4cgEE0EOELd01nfCX+qZcNhHcpANhMBFo+lfkdI3I4XXBFAE/oZICDuvf11I36wQFED9lwGt+uoCsvpmC/pW5IKnEOeBKNizQhiHapV0wFsyeAI14p+882GsEjhUcz/r2FATrdEo+3lZOv2WxDBiKDGSGE50xE3wQNwfj4bXYDjccR/ctz/ab/aEp4RWwiPCdUIb4fYE8Rz5D/mwwCjQBj2Ea3LO/D5n3A6yeuIheADkh9w4EzcBLvhw6ImNB0HfnlDL0USuyv5H7n/l8F3VNXYUNwpKGUQJpjj8uFLbSdtzgEVV0+8rpI41c6CunIGZH/1zvqu0AN6jfrTE5mP7sDPYCewcdhirByzsGNaAXcSOqPBAFz3p66J+b/F98eRCHvFP/ngan6pKKtxq3DrcPqvn8oWF+aoHjDNRNkUuzhbls9gymUTI4kr5rkNY7m7u7gCovivq19QbZt/3AmGe/6abux6AgP29vb2HvumiGgHYVwYA9eY3nf10+Do4AcDZSr5SXqDW4aoLAVCBDnyijOF3yxo4wHzcgRfwB8EgDIwEsSARpIHxsMoi2M9yMBlMA7NBCSgDS8BKUAE2gM1gO9gF9oJ6cBicAKfBBXAZXAd3Yfe0gxegC7wDPQiCkBA6wkCMEQvEFnFG3BEfJBAJQ6KReCQNyUCyESmiRKYhc5EyZBlSgWxCqpHfkYPICeQc0orcRh4iHchr5BOKoTTUADVD7dChqA/KRqPQRHQcmo1OQovQYnQRuhqtQneidegJ9AJ6HW1DX6DdGMC0MCZmiblgPhgHi8XSsSxMjs3ASrFyrAqrxRrh/3wVa8M6sY84EWfgLNwFdnAknoTz8Un4DHwhXoFvx+vwZvwq/hDvwr8S6ARTgjPBj8AlpBKyCZMJJYRywlbCAcIp+DS1E94RiUQm0Z7oDZ/GNGIOcSpxIXEdcTfxOLGV+JjYTSKRjEnOpABSLIlHyieVkNaQdpKOka6Q2kkfyFpkC7I7OZycTpaS55DLyTvIR8lXyM/IPRRdii3FjxJLEVCmUBZTtlAaKZco7ZQeqh7VnhpATaTmUGdTV1Nrqaeo96hvtLS0rLR8tUZribVmaa3W2qN1Vuuh1keaPs2JxqGNpSlpi2jbaMdpt2lv6HS6HT2Ynk7Ppy+iV9NP0h/QP2gztF21udoC7Znaldp12le0X+pQdGx12DrjdYp0ynX26VzS6dSl6NrpcnR5ujN0K3UP6t7U7dZj6A3Ti9XL01uot0PvnN5zfZK+nX6YvkC/WH+z/kn9xwyMYc3gMPiMuYwtjFOMdgOigb0B1yDHoMxgl0GLQZehvuFww2TDQsNKwyOGbUyMacfkMiXMxcy9zBvMT4PMBrEHCQctGFQ76Mqg90aDjYKNhEalRruNrht9MmYZhxnnGi81rje+b4KbOJmMNplsst7klEnnYIPB/oP5g0sH7x18xxQ1dTKNN51qutn0omm3mblZhJnMbI3ZSbNOc6Z5sHmO+Qrzo+YdFgyLQAuxxQqLYxZ/sQxZbJaEtZrVzOqyNLWMtFRabrJsseyxsrdKsppjtdvqvjXV2sc6y3qFdZN1l42FzSibaTY1NndsKbY+tiLbVbZnbN/b2dul2M2zq7d7bm9kz7Uvsq+xv+dAdwhymORQ5XDNkejo45jruM7xshPq5Okkcqp0uuSMOns5i53XObcOIQzxHSIdUjXkpgvNhe1S4FLj8tCV6RrtOse13vXlUJuh6UOXDj0z9Kubp5vEbYvb3WH6w0YOmzOscdhrdyd3vnul+zUPuke4x0yPBo9Xw52HC4evH37Lk+E5ynOeZ5PnFy9vL7lXrVeHt413hvda75s+Bj5xPgt9zvoSfEN8Z/oe9v3o5+WX77fX7x9/F/9c/x3+z0fYjxCO2DLicYBVAC9gU0BbICswI3BjYFuQZRAvqCroUbB1sCB4a/AztiM7h72T/TLELUQeciDkPcePM51zPBQLjQgtDW0J0w9LCqsIexBuFZ4dXhPeFeEZMTXieCQhMipyaeRNrhmXz63mdo30Hjl9ZHMULSohqiLqUbRTtDy6cRQ6auSo5aPuxdjGSGPqY0EsN3Z57P04+7hJcYdGE0fHja4c/TR+WPy0+DMJjIQJCTsS3iWGJC5OvJvkkKRMakrWSR6bXJ38PiU0ZVlKW+rQ1OmpF9JM0sRpDemk9OT0rendY8LGrBzTPtZzbMnYG+PsxxWOOzfeZLxk/JEJOhN4E/ZlEDJSMnZkfObF8qp43ZnczLWZXXwOfxX/hSBYsELQIQwQLhM+ywrIWpb1PDsge3l2hyhIVC7qFHPEFeJXOZE5G3Le58bmbsvtlaRIdueR8zLyDkr1pbnS5onmEwsntsqcZSWytkl+k1ZO6pJHybcqEMU4RUO+AdzAX1Q6KH9RPiwILKgs+DA5efK+Qr1CaeHFKU5TFkx5VhRe9NtUfCp/atM0y2mzpz2czp6+aQYyI3NG00zrmcUz22dFzNo+mzo7d/Yfc9zmLJvzdm7K3MZis+JZxY9/ifilpkS7RF5yc57/vA3z8fni+S0LPBasWfC1VFB6vsytrLzs80L+wvO/Dvt19a+9i7IWtSz2Wrx+CXGJdMmNpUFLty/TW1a07PHyUcvrVrBWlK54u3LCynPlw8s3rKKuUq5qWx29umGNzZolaz5XiCquV4ZU7l5runbB2vfrBOuurA9eX7vBbEPZhk8bxRtvbYrYVFdlV1W+mbi5YPPTLclbzvzm81v1VpOtZVu/bJNua9sev7252ru6eofpjsU1aI2ypmPn2J2Xd4Xuaqh1qd20m7m7bA/Yo9zz1+8Zv9/YG7W3aZ/Pvtr9tvvXHmAcKK1D6qbUddWL6tsa0hpaD4482NTo33jgkOuhbYctD1ceMTyy+Cj1aPHR3mNFx7qPy453nsg+8bhpQtPdk6knrzWPbm45FXXq7Onw0yfPsM8cOxtw9vA5v3MHz/ucr7/gdaHuoufFA394/nGgxaul7pL3pYbLvpcbW0e0Hr0SdOXE1dCrp69xr124HnO99UbSjVs3x95suyW49fy25ParOwV3eu7Ouke4V3pf9375A9MHVX86/rm7zavtyMPQhxcfJTy6+5j/+MUTxZPP7cVP6U/Ln1k8q37u/vxwR3jH5b/G/NX+Qvaip7Pkb72/1750eLn/n+B/LnaldrW/kr/qfb3wjfGbbW+Hv23qjut+8C7vXc/70g/GH7Z/9Pl45lPKp2c9kz+TPq/+4vil8WvU13u9eb29Mp6c17cVwOBAs7IAeL0NAHoaAIzLcP8wRn3u6xNEfVbtQ+C/YfXZsE+8AKiFN9V2nXMcgD1w2AVDbnhXbdUTgwHq4TEwNKLI8nBXc9HgiYfwobf3jRkAJLif+SLv7e1Z19v7ZQsM9jYAxyepz5sqIcKzwUY3FbpisQ/8KP8Bxu2Efs6OyPQAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAZ2SURBVHic7dxNT1NLHAbw5zSnpbQ9tAVCK0UMkELUWJImRk1wwcJoYm5i+A6u7he4i7s1936Am9xF9y6MfgDjRkNaXDU0UuJbaRSrUt5KyzlYEM5deEEtM5WXnjPt9P9LXHjmMDP0CdM5M9MChBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQ0toUqypOJBJ/WlW3lX779+/aS2Y4nbtXe/FzfOR31Lx+4XTuH8Z9ta8Dsz6rWBJwIpFQAOxZUbfVGAEjnM4dep0+x0dMxo87wumc+cM9zNeBVZ9VHHY1RMSggCVHAUuOApYcBSw5ClhyFLDkKGDJUcCSU0V3AACGh4fR3d1taRuZTAY7OzuWttGMmiLgWCyG3t5eS9uYn59vy4CFD9GKoiAQCIjuhrSEBxwMBqGqTTGQSEl4wFYPze1OeMBWT67anfCxsaenh3l9dnYWGxsbDWtne3u7YXW1EuEBB4NB5vUXL16gWq3a3Bv5CB2ivV4v3G73oeuVSoXCbRChAfMmWKurqzb3RF4UsOSEBsybQS8vL9vcE3lRwJITFrDL5YKmaYeu0wSrsYQFzHv+pfffxhIWMG+CtbKyYnNP5CZsoYP3F8wL2Ol0IhgMHmxOGIaBra0trK+v05Beh7CAeStYP06whoeHMTY2hkAgAK/Xy7zfNE0Ui0V8+PABr169gmEYlvS3VQkJ2OFwMAPen2CdO3cO8Xic+1f+I0VREAqFEAqFMD4+jmw2i0wm07Zrz7WEBBwMBuFwHH77393dxZ07d068haiqKsbHxxGNRvHkyRN63IKgSRYvwEAg0JD9YY/Hg9u3b2NkZOTUdbU6IQEfZehlMU3WJzbZVFXF5ORk24csZIg+6iZ/oVDAmzdvsL6+jkqlgp2dHfj9fvT09KC7uxu9vb2IRCJ167h+/TpKpVLbPl83ZcCLi4tIpVKoVCqHykqlEkqlEnK5HABgcHAQExMT8Hg8zLpUVcWNGzfw8OFDfP369fSdbzG2D9GapsHlcjHL9vb28Pz5czx+/JgZLsv79+/x6NEjvH37lnuPz+fDxYsXT9TfVmd7wPUmUalUCnNzc8eus1qt4unTp8jn89x7Ll261JanN23/jd+9e4cHDx6gq6sLXV1d0DQNPp8PpVIJL1++PFXdMzMziEQizBHC7XZjdHQU8/Pzp2qj1dge8N7eHsrlMsrlcsPrNgwD6XQaV69eZZZHIpG2C1j4sdlGy2az3NOYZ86cgaLY9gU3TUG6gE3T5G5YuFwu7hq4rKQLGPj2KMXDe5ySVdsFzDqmKzMKWHJSBlxvq7DdVrOkDLje542/fPliY0/Ea4qAG73CRAF/Z+tCx8DAAKLRKNxu98G/jo4OqKqK+/fvN+y4jd/vZ143TRNra2sNaaNV2BpwR0cHd392cHDw1EuV+3gBr62ttd1RHluH6HpHaM6ePduQNjweD/r6+phlS0tLDWmjldgacLlc5r4H9vf3M89pHdeVK1fgdDqZZfW2FGVl+ySLt6XndDoRi8VOVXc4HOa+BRSLRRSLxVPV34psD/j169fcsng8zh1ef0VRFFy7do1bfpJ9ZhnYHvDy8jI+fvzILHM4HJicnOQOsTydnZ24desW9zBfoVDAwsLCsfsqAyHPwclkEru7u8wyTdMwNTV15EnXwMAApqamuIfvtre3MT09feK+tjohZ1g2NjaQTqdx+fJlZrmmabh58yby+Tyy2SxWV1d/+hpCTdPQ19eH/v5+jI2NcdsxTRPT09PY3Nxs+O/QKoQdUspkMvB6vbhw4QL3nqGhIQwNDQEANjc3oes6/H7/kTYMTNP85TmtdiD0FFoqlYKiKDh//vwv7/X5fPD5fEeq1zRNPHv27OBobTsTfswwmUzi06dPmJiY4B6nPY6VlRUkk0n6XNL/hAcMAAsLC1haWkIsFsPo6OixZ9HAt02E2dlZZLPZY33ERXZNETAA6LqOmZkZpNNpRKNRhMNhhEIhdHZ2cn/GMAwsLi4in8+jUChQsAxNE/C+arWKubm5g4WJ/W/Dc7vdcLlc2NragmEY0HWd+6hFvmu6gGvpug5d10V3o2U1xYY/sQ4FLDkKWHIUsOQoYMlRwJKjgCVHAUvOkoWOu3fvmolE4p4Vddug9stBeOuffwH46cPG4XTOrP3/5/jIH0esjxBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgjDf63mDoofRDwuAAAAAElFTkSuQmCC';

    break;
    
}

//
// BASE64 LAST MODIFIED
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['lastmodified_base64_PNG'] = '2022-08-28 16:20:02.578103';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['lastmodified_base64_JPEG'] = '2022-08-28 16:20:02.580940';

//
// BASE64 HASH/CHECKSUM
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_crc'] = '2507662620';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['base64_md5'] = 'da275857d2225e0783c3fe9e025791e6';

self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_crc'] = '0';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['base64_md5'] = 'd41d8cd98f00b204e9800998ecf8427e';

//
// HASHES FOR BASE64 SOURCE PNG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['md5'] = 'fae8f8eab43ff700377278ab33ee6687';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_PNG][self::$request_salt][$system_file_serial]['sha1'] = 'f0b2eb3c09924941f9d631ef65eec68f15a7909b';

//
// HASHES FOR BASE64 SOURCE JPEG FILE
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['md5'] = '';
self::$image_filesystem_meta_ARRAY[CRNRSTN_BASE64_JPEG][self::$request_salt][$system_file_serial]['sha1'] = '';


# # # # # 
# # # # # END OF CRNRSTN :: GENERATED SYSTEM FILE
# # # # # [2022-08-28 16:20:02.581141] [rtime 1.50320] 
