<div class="hidden"><h1>requiredDetectionMatches()</h1>
		<p>In order for crnrstn to properly initialize itself within the hosting environment, a specified number of predefined $_SERVER parameters need to match against the $resourceKeys that will have been communicated to the C<span class="the_R">R</span>NRSTN Suite :: in the configuration file via <a href="../../../classes/crnrstn/defineenvresource/" target="_self">defineEnvResource()</a>. The <a href="../../../classes/crnrstn/requireddetectionmatches/" target="_self">requiredDetectionMatches()</a> method will convey this number to the environmental detection process.<br />
<br />
Successfully matching this specified number of predefined $_SERVER parameters against the user defined $resourceKeys (see <a href="../../../classes/crnrstn/defineenvresource/" target="_self">defineEnvResource()</a>) will result in the successful configuration of the C<span class="the_R">R</span>NRSTN Suite :: with the user defined environment (see <a href="../../../classes/crnrstn/addenvironment/" target="_self">addEnvironment()</a>) at runtime.<br />
<br />
The integer value that is passed to <a href="../../../classes/crnrstn/requireddetectionmatches/" target="_self">requiredDetectionMatches()</a> will give the C<span class="the_R">R</span>NRSTN Suite :: the target quota that needs to be satisfied before it can acknowledge/recognize the running environment. For example, passing in three (3) would indicate to the C<span class="the_R">R</span>NRSTN Suite :: that at least 3 of the around 25 predefined $_SERVER parameters (e.g. DOCUMENT_ROOT, SERVER_NAME, REMOTE_ADDR, REMOTE_PORT, SERVER_PROTOCOL,...etc.) will need to be successfully matched against the $resourceKeys which will have been defined in the configuration file through <a href="../../../classes/crnrstn/defineenvresource/" target="_self">defineEnvResource()</a>. <br />
<br />
If NULL is passed to <a href="../../../classes/crnrstn/requireddetectionmatches/" target="_self">requiredDetectionMatches()</a>, the user defined environment encountered having settings with the strongest correlation to your server settings (highest number of matches) will be taken. In this case, ALL $_SERVER parameters will be compared to ALL environments in order to satisfy the requirements of the environmental detection process.<br />
<br />
Conversely, if zero (0) is passed in, the very first $_SERVER-to-$resourceKey match will be taken as an indication of successful environmental match. ProTip: If there is only one (1) environment for the application to run within, set this to 0...not NULL...for a slight boost to application performance.<br />
<br />
If an integer value > 0 is passed in, the FIRST environment to successfully match that quantity of $resourceKeys to the $_SERVER super global will be taken immediately with no further evaluation being made of any other user defined environments. By this logic, it should be obvious that (1) passing an integer value to <a href="../../../classes/crnrstn/requireddetectionmatches/" target="_self">requiredDetectionMatches()</a> is slightly more efficient than passing NULL and that (2) a production application can break due to initialization error if this number is too low (relative to the matching number of properly defined server settings for all other environments) or too high.<br />
<br />
Therefore...knoweth thy $_SERVER!</p>
		<p>Version: </p>
		<p>Method Definition: requiredDetectionMatches($integerValue=NULL)</p>
		<p>Invoking class: crnrstn</p><h2>Technical Specifications:<h2><p>Currently tested on an ubuntu 4.2 server running PHP Version 5.2.6 and Apache 2.2.11</p><p>It is recommended that you upgrade to the latest version of PHP to take advantage of the latest gains in security and processing efficiency.</p><h2>Parameters:</h2><h3>$integerValue</h3><p>Integer number representing the quantity of $_SERVER parameters that need to be matched against the $_SERVER values initialized through defineEnvResource() for successful configuration of the C<span class="the_R">R</span>NRSTN Suite :: with the running environment.</p><p>Last upated: 2017-04-11 02:27:21</p></div>