<?php
echo "<div>";
echo "<div id=\"emailheader\">";


	echo "<div id=\"emailbutton\">";
	echo "<form action=\"testing.php\" method=\"post\" ENCTYPE=\"multipart/form-data\">";
	echo "<input type=\"hidden\" name=\"email_mod\" value=\"send\">";
	echo " <input type=\"submit\" name=\"Submit\" value=\"Send Test\"></form>";
	echo "</div>";
echo "<h1>Testing Options</h1>";

echo "</div>";
echo "<hr><br>";
echo "</div>";
?>