<div class="hidden"><h1>initCookieEncryption()</h1>
		<p>The C<span class="the_R">R</span>NRSTN Suite :: has hooks for encryption baked into the fabric of its' cookie management policy. When invoking <a href="../../../classes/crnrstn/initcookieencryption/" target="_self">initCookieEncryption()</a>, cookie encryption can be initialized through either (1) the specification of a cipher name or (2) a 0-8 scale representing desired encryption strength (where 0 turns session encryption off and 8 is maximum strength). If you don't want the performance hit of encryption and desire to turn it off, you must specify zero (0) for $cipherStrength. Leaving $cipherStrength empty or NULL will be the same as specifying the lightest/weakest encryption strength of one (1). When cookie encryption is initialized via <a href="../../../classes/crnrstn/initcookieencryption/" target="_self">initCookieEncryption()</a>, if a cipher name is provided, that will be used for cookie data encryption regardless of whether or not $cipherStrength (0-8) is specified.<br />
<br />
Some supported and common ciphers recognized by the C<span class="the_R">R</span>NRSTN Suite :: and sorted by encryption strength (or resource consumption) from low-to-high are as follows. Please note that typically, the lower the encryption strength...the faster the processing:<br />
$cipherName=*[cast-128, gost, twofish, rijndael-128, cast-256, loki97, saferplus, rijndael-192, serpent, xtea, rijndael-256, blowfish-compat, rc2, blowfish, des, tripledes]<br />
*(where cast-128 is the weakest/fastest/lightest and tripledes, the strongest/slowest/heaviest)<br />
<br />
Some additional notes:<br />
<p><ul><li>Set $cipherStrength to 0 (ZED) to turn off cipher encryption/decryption for cookie data.</li><li>Setting $cipherStrength to NULL is treated as the lowest strength encryption..i.e. the same as $cipherStrength=1.</li><li>And again, if a cipher name is provided, that will be used regardless of any specified strength[0-8].</li></ul></p></p>
		<p>Version: </p>
		<p>Method Definition: initCookieEncryption($envKey, $cipherStrength, $cipherName)</p>
		<p>Invoking class: crnrstn</p><h2>Technical Specifications:<h2><p>See mcrypt_list_algorithms() for additional details about server mcrypt configuration.</p><p>It is recommended that you upgrade to the latest version of PHP to take advantage of the latest gains in security and processing efficiency.</p><p>DIR is the mcrypt install directory. Also be sure to compile libmcrypt with the option --disable-posix-threads.</p><p>PHP must be compiled with the --with-mcrypt[=DIR] parameter to enable the mcrypt extension.</p><p>Currently tested on an ubuntu 4.2 server running PHP Version 5.2.6 and Apache 2.2.11</p><p>initCookieEncryption() currently tested in PHP 5.4.4 running Apache 2.4</p><h2>Parameters:</h2><h3>$envKey</h3><p>A user-defined custom string identifying a specific hosting environment or server profile. E.g. "LOCALHOST_MY_OLD_MAC_TOWER", "LOCALHOST_PC" or "PROD_01".</p><h3>$cipherStrength</h3><p>An integer or string of value 0 to 8 representing the desired cipher encryption strength. Setting $cipherStrength to NULL is treated as the lowest strength encryption..i.e. the same as $cipherStrength=1.<br />
If $cipherStrength=0, all session data will be in clear text.</p><h3>$cipherName</h3><p>If a cipher name is provided, that will be used regardless of any specified strength[0-8].<br />
For a list of available ciphers, check mcrypt_list_algorithms().<br />
Ciphers supported by the C<span class="the_R">R</span>NRSTN Suite :: and ordered (below) from weak[0] to strong[8] include:<br />
<ul><li>cast-128</li><li>gost</li><li>twofish</li><li>rijndael-128</li><li>cast-256</li><li>loki97</li><li>saferplus</li><li>rijndael-192</li><li>serpent</li><li>xtea</li><li>rijndael-256</li><li>blowfish-compat</li><li>rc2</li><li>blowfish</li><li>des</li><li>tripledes</li></ul></p><p>Last upated: 2017-04-11 02:27:21</p></div>