<?php
/*
DATA HANDLING ARCHITECTURES
-----
G :: HTTP $_GET REQUEST.
P :: HTTP $_POST REQUEST.
H :: PHP SERVER SESSION ($_SESSION SUPER GLOBAL ARRAY).
S :: CRNRSTN :: SSDTLA PACKET (SOAP WRAPPED ENCRYPTED PSSDTLA PACKET. THE BROWSER WILL TALK LIKE A SERVER).
J :: CRNRSTN :: PSSDTLA PACKET (OPENSSL ENCRYPTED JSON OBJECT).
C :: CARRIER PIGEON (AVIAN OF HOMING VARIANT)...OR BROWSER COOKIE...
D :: DATABASE (MySQLi CONNECTION).
R :: RUNTIME.
O :: SIMPLE OBJECT ACCESS PROTOCOL (NuSOAP 0.9.5, SOAP 1.1).
F :: SERVER LOCAL FILE SYSTEM.

GPHSJCDROF

//
// CHANNEL CONSTANTS.
CRNRSTN_CHANNEL_ALL, CRNRSTN_CHANNEL_RUNTIME, CRNRSTN_CHANNEL_DATABASE, CRNRSTN_CHANNEL_SSDTLA,
CRNRSTN_CHANNEL_PSSDTLA, CRNRSTN_CHANNEL_SESSION, CRNRSTN_CHANNEL_COOKIE, CRNRSTN_CHANNEL_SOAP,
CRNRSTN_CHANNEL_GET, CRNRSTN_CHANNEL_POST,  CRNRSTN_CHANNEL_FILE

//
// CRNRSTN :: INITIALIZE SECURITY PROFILES FOR MULTI-CHANNEL RESOURCE ACCESS [IPv4 and IPv6]
$oCRNRSTN->initialize_ip_address_profile([environment-key], [channel-constant], [ip], [deny-access-boolean]);

// WITH [deny-access-boolean], false[*DEFAULT*] = EXCLUSIVE ACCESS (AUTHORIZED TO PROVIDED IP/IP RANGE) AND
// true = DENY ACCESS (AUTHORIZED TO PROVIDED IP/IP RANGE).
$this->init_ip_authorization_profile(CRNRSTN_RESOURCE_ALL, CRNRSTN_AUTHORIZE_ALL, '127.0.0.1');

*/

//
// THIS CRNRSTN :: 1.0.0 TECH SHOULD BE PROMOTED DOWN TO A LOWER LEVEL FOR
// MULTI-CHANNEL SUPPORT AT THIS TIME. SAME METHOD NAMES. SAME INPUT PARAMS.
// Monday, September 4th, 2023 1046 hrs.
//
// INITIALIZE SECURITY PROTOCOLS FOR RESOURCE ACCESS [IPv4 and IPv6]
//
// GRANT ACCESS
// 
# $this->oCRNRSTN_IPSECURITY_MGR->grantAccess([environment-key], [ip]);
//$this->oCRNRSTN_IPSECURITY_MGR->grantAccess('LOCALHOST_PC','127.0.0.1');
//$this->oCRNRSTN_IPSECURITY_MGR->grantAccess('LOCALHOST_MAC','192.168.172.1,192.168.172.135');
#$this->oCRNRSTN_IPSECURITY_MGR->grantAccess('STAGE','FE80::230:80FF:FEF3:4701');
#$this->oCRNRSTN_IPSECURITY_MGR->grantAccess('PREPROD','127.0.0.1, 127.*, 128.0.4.50-128.0.4.60, 129.*-130.50.*, 130.51.10.*');
#$this->oCRNRSTN_IPSECURITY_MGR->grantAccess('PRODUCTION','127.0.0.1, 130.*, 128.0.4.50-129.0.*, 129.*-130.50.10.10, 130.51.10.*');

//
// DENY ACCESS
//
#$this->oCRNRSTN_IPSECURITY_MGR->denyAccess([environment-key], [ip]);
#$this->oCRNRSTN_IPSECURITY_MGR->denyAccess('LOCALHOST_MAC','192.168.172.1');
#$this->oCRNRSTN_IPSECURITY_MGR->denyAccess('LOCALHOST_PC','FE80::230:80FF:FEF3:4701');
#$this->oCRNRSTN_IPSECURITY_MGR->denyAccess('PREPROD','127.0.0.1, 127.*, 128.0.4.50-128.0.4.60, 129.*-130.50.*, 130.51.10.*');
#$this->oCRNRSTN_IPSECURITY_MGR->denyAccess('PRODUCTION','127.0.0.1, 130.*, 128.0.4.50-129.0.*, 129.*-130.50.10.10, 130.51.10.*');