<div class="mainNav"><a href="mastercontrol.php">Main</div>
<div class="mainNav"><a href="admintool.php">Administrative Tools</a></div>
<div class="mainNav"><a href="clientcontrol.php">Client Managment</a></div>
<div class="mainNav"><a href="ttcontrol.php">Trouble Tickets</a></div>
<div class="mainNav"><a href="billingcontrol.php">Billing</a></div>
<div class="mainNav"><a href="contactcontrol.php">Contact</a></div>
<div class="mainNav"><a href="resourcecontrol.php">Resources</a></div>
<div class="mainNav"><a href="loggoff.php">Sign Out</a></div>
