<div id="lbox">
	<div id="lnav">
		<div class="lmenu" style="margin-top:3px;"><a href="viewaccount.php">View User Accounts</a></div>
		<div class="lmenu" style="margin-top:3px;"><a href="../client/fileupload.php">Upload a file</a></div>
		<div class="lmenu" style="margin-top:3px;"><a href="testing.php">Email Testing</a></div>
<br><br>	
		<div class="lmenu" style="margin-top:3px;"><a href="http://pimpinainteasy.net/" target="_blank">Mambo Live</a></div>
		<div class="lmenu" style="margin-top:3px;"><a href="http://demo.mamboserver.com/administrator/" target="_blank">Mambo Demo Admin</a></div>
		<div class="lmenu" style="margin-top:3px;"><a href="http://demo.mamboserver.com/" target="_blank">Mambo Demo Front-End</a></div>
<br><br>
		<div class="lmenu" style="margin-top:3px;"><a href="http://pimpinainteasy.net/crm/index.php?action=Login&module=Users" target="_blank">SugarCRM Live</a></div>
		<div class="lmenu" style="margin-top:3px;"><a href="http://demo.sugarondemand.com/sugarcrm_os/index.php?action=Login&module=Users" target="_blank">SugarCRM Demo Admin</a></div>
		<div class="lmenu" style="margin-top:3px;"><a href="http://www.sugarcrm.com/crm/demo/outlook-plugin.html" target="_blank">SugarCRM and Outlook</a></div>
	</div>
</div>







